-- ============================================================================
-- CSS Language Challenges (Complete)
-- ============================================================================
-- Generated: 2025-11-01T14:07:10.140Z
-- ============================================================================

-- ====================================
-- CSS Language Challenges - Part 1
-- Levels 1-50 (EASY 50개)
-- ====================================

-- Unit 1: 기본 선택자와 스타일 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-element-selector$$, $$css$$, $$syntax$$, 1, $$요소 선택자$$, $$태그 이름으로 선택$$, $$challenge$$, 1,
$$모든 p 태그의 글자색을 파란색으로 만드세요.$$,
$$- 요소 선택자 사용\n- color 속성$$,
$$[{"input": "", "output": "파란색 문단"}]$$,
$$/* 모든 p 태그를 파란색으로 */\n$$,
$$p {\n    color: blue;\n}$$,
$$[{"input": "", "expected": "p color blue"}]$$,
$$["요소 선택자는 태그 이름을 직접 사용합니다"]$$,
$$["selector", "basics"]$$, 5),

($$css-class-selector$$, $$css$$, $$syntax$$, 2, $$클래스 선택자$$, $$.으로 클래스 선택$$, $$challenge$$, 1,
$$.highlight 클래스의 배경색을 노란색으로 만드세요.$$,
$$- 클래스 선택자 (.클래스명)\n- background-color 속성$$,
$$[{"input": "", "output": "노란 배경"}]$$,
$$/* .highlight 클래스에 노란 배경 */\n$$,
$$.highlight {\n    background-color: yellow;\n}$$,
$$[{"input": "", "expected": "highlight yellow bg"}]$$,
$$["클래스 선택자는 .으로 시작합니다"]$$,
$$["selector", "class"]$$, 5),

($$css-id-selector$$, $$css$$, $$syntax$$, 3, $$ID 선택자$$, $$#으로 ID 선택$$, $$challenge$$, 1,
$$#header ID의 글자 크기를 24px로 만드세요.$$,
$$- ID 선택자 (#아이디명)\n- font-size 속성$$,
$$[{"input": "", "output": "큰 글자"}]$$,
$$/* #header ID의 글자 크기 */\n$$,
$$#header {\n    font-size: 24px;\n}$$,
$$[{"input": "", "expected": "header 24px"}]$$,
$$["ID 선택자는 #으로 시작합니다"]$$,
$$["selector", "id"]$$, 5),

($$css-multiple-selectors$$, $$css$$, $$syntax$$, 4, $$여러 선택자$$, $$쉼표로 그룹화$$, $$challenge$$, 1,
$$h1, h2, h3 태그의 글자색을 검은색으로 만드세요.$$,
$$- 쉼표로 여러 선택자 그룹화\n- color: black$$,
$$[{"input": "", "output": "검은색 제목들"}]$$,
$$/* h1, h2, h3를 검은색으로 */\n$$,
$$h1, h2, h3 {\n    color: black;\n}$$,
$$[{"input": "", "expected": "headings black"}]$$,
$$["쉼표로 여러 선택자에 같은 스타일을 적용할 수 있습니다"]$$,
$$["selector", "grouping"]$$, 5),

($$css-universal-selector$$, $$css$$, $$syntax$$, 5, $$전체 선택자$$, $$* 선택자$$, $$challenge$$, 1,
$$모든 요소의 margin을 0으로 리셋하세요.$$,
$$- * 전체 선택자\n- margin: 0$$,
$$[{"input": "", "output": "margin 리셋"}]$$,
$$/* 모든 요소의 margin 제거 */\n$$,
$$* {\n    margin: 0;\n}$$,
$$[{"input": "", "expected": "all margin 0"}]$$,
$$["* 선택자는 모든 요소를 선택합니다"]$$,
$$["selector", "universal"]$$, 5);

-- Unit 2: 색상과 배경 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-color-name$$, $$css$$, $$syntax$$, 6, $$색상 이름$$, $$기본 색상명 사용$$, $$challenge$$, 1,
$$글자색을 red로 설정하세요.$$,
$$- color 속성\n- 색상 이름 사용$$,
$$[{"input": "", "output": "빨간 글자"}]$$,
$$.text {\n    /* 빨간색으로 */\n}$$,
$$.text {\n    color: red;\n}$$,
$$[{"input": "", "expected": "red text"}]$$,
$$["CSS는 140개 이상의 색상 이름을 지원합니다"]$$,
$$["color", "basics"]$$, 5),

($$css-color-hex$$, $$css$$, $$syntax$$, 7, $$HEX 색상$$, $$#RRGGBB 형식$$, $$challenge$$, 1,
$$배경색을 HEX 코드 #FF5733으로 설정하세요.$$,
$$- background-color\n- #RRGGBB 형식$$,
$$[{"input": "", "output": "HEX 배경색"}]$$,
$$.box {\n    /* HEX 배경색 */\n}$$,
$$.box {\n    background-color: #FF5733;\n}$$,
$$[{"input": "", "expected": "hex bg color"}]$$,
$$["HEX 코드는 #으로 시작합니다"]$$,
$$["color", "hex"]$$, 5),

($$css-color-rgb$$, $$css$$, $$syntax$$, 8, $$RGB 색상$$, $$rgb() 함수$$, $$challenge$$, 1,
$$글자색을 rgb(100, 150, 200)으로 설정하세요.$$,
$$- color 속성\n- rgb(r, g, b) 형식$$,
$$[{"input": "", "output": "RGB 글자색"}]$$,
$$.text {\n    /* RGB 색상 */\n}$$,
$$.text {\n    color: rgb(100, 150, 200);\n}$$,
$$[{"input": "", "expected": "rgb color"}]$$,
$$["RGB는 0-255 범위의 값을 사용합니다"]$$,
$$["color", "rgb"]$$, 5),

($$css-background-image$$, $$css$$, $$syntax$$, 9, $$배경 이미지$$, $$background-image$$, $$challenge$$, 1,
$$배경 이미지를 설정하세요.$$,
$$- background-image: url()\n- 이미지 경로$$,
$$[{"input": "", "output": "배경 이미지"}]$$,
$$.banner {\n    /* 배경 이미지 */\n}$$,
$$.banner {\n    background-image: url("background.jpg");\n}$$,
$$[{"input": "", "expected": "bg image"}]$$,
$$["url() 함수로 이미지 경로를 지정합니다"]$$,
$$["background", "image"]$$, 5),

($$css-background-repeat$$, $$css$$, $$syntax$$, 10, $$배경 반복$$, $$background-repeat$$, $$challenge$$, 1,
$$배경 이미지가 반복되지 않게 하세요.$$,
$$- background-repeat: no-repeat\n- 한 번만 표시$$,
$$[{"input": "", "output": "반복 없음"}]$$,
$$.box {\n    background-image: url("pattern.png");\n    /* 반복 방지 */\n}$$,
$$.box {\n    background-image: url("pattern.png");\n    background-repeat: no-repeat;\n}$$,
$$[{"input": "", "expected": "no-repeat"}]$$,
$$["repeat, repeat-x, repeat-y, no-repeat 값을 사용할 수 있습니다"]$$,
$$["background", "repeat"]$$, 5);

-- Unit 3: 텍스트 스타일 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-font-family$$, $$css$$, $$syntax$$, 11, $$글꼴 설정$$, $$font-family$$, $$challenge$$, 1,
$$글꼴을 Arial, sans-serif로 설정하세요.$$,
$$- font-family 속성\n- 폴백 글꼴 포함$$,
$$[{"input": "", "output": "Arial 글꼴"}]$$,
$$body {\n    /* 글꼴 설정 */\n}$$,
$$body {\n    font-family: Arial, sans-serif;\n}$$,
$$[{"input": "", "expected": "arial font"}]$$,
$$["여러 글꼴을 나열하면 폴백으로 동작합니다"]$$,
$$["text", "font"]$$, 5),

($$css-font-size$$, $$css$$, $$syntax$$, 12, $$글자 크기$$, $$font-size$$, $$challenge$$, 1,
$$글자 크기를 16px로 설정하세요.$$,
$$- font-size: 16px\n- px 단위 사용$$,
$$[{"input": "", "output": "16px 글자"}]$$,
$$p {\n    /* 글자 크기 */\n}$$,
$$p {\n    font-size: 16px;\n}$$,
$$[{"input": "", "expected": "16px font"}]$$,
$$["px, em, rem, % 등 다양한 단위를 사용할 수 있습니다"]$$,
$$["text", "font-size"]$$, 5),

($$css-font-weight$$, $$css$$, $$syntax$$, 13, $$글자 두께$$, $$font-weight$$, $$challenge$$, 1,
$$글자를 굵게(bold) 만드세요.$$,
$$- font-weight: bold\n- 또는 숫자 700$$,
$$[{"input": "", "output": "굵은 글자"}]$$,
$$h1 {\n    /* 굵게 */\n}$$,
$$h1 {\n    font-weight: bold;\n}$$,
$$[{"input": "", "expected": "bold text"}]$$,
$$["normal(400), bold(700) 또는 100-900 숫자를 사용합니다"]$$,
$$["text", "font-weight"]$$, 5),

($$css-text-align$$, $$css$$, $$syntax$$, 14, $$텍스트 정렬$$, $$text-align$$, $$challenge$$, 1,
$$텍스트를 가운데 정렬하세요.$$,
$$- text-align: center\n- 좌우 정렬$$,
$$[{"input": "", "output": "중앙 정렬"}]$$,
$$.title {\n    /* 가운데 정렬 */\n}$$,
$$.title {\n    text-align: center;\n}$$,
$$[{"input": "", "expected": "center aligned"}]$$,
$$["left, center, right, justify 값을 사용할 수 있습니다"]$$,
$$["text", "alignment"]$$, 5),

($$css-text-decoration$$, $$css$$, $$syntax$$, 15, $$텍스트 장식$$, $$text-decoration$$, $$challenge$$, 1,
$$링크의 밑줄을 제거하세요.$$,
$$- text-decoration: none\n- 밑줄 제거$$,
$$[{"input": "", "output": "밑줄 없는 링크"}]$$,
$$a {\n    /* 밑줄 제거 */\n}$$,
$$a {\n    text-decoration: none;\n}$$,
$$[{"input": "", "expected": "no underline"}]$$,
$$["none, underline, overline, line-through 값을 사용합니다"]$$,
$$["text", "decoration"]$$, 5);

-- Unit 4: 박스 모델 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-width-height$$, $$css$$, $$syntax$$, 16, $$너비와 높이$$, $$width, height$$, $$challenge$$, 1,
$$박스의 너비 200px, 높이 100px로 설정하세요.$$,
$$- width: 200px\n- height: 100px$$,
$$[{"input": "", "output": "200x100 박스"}]$$,
$$.box {\n    /* 너비와 높이 */\n}$$,
$$.box {\n    width: 200px;\n    height: 100px;\n}$$,
$$[{"input": "", "expected": "200x100 size"}]$$,
$$["px, %, em, rem, vw, vh 등의 단위를 사용할 수 있습니다"]$$,
$$["box-model", "size"]$$, 5),

($$css-padding$$, $$css$$, $$syntax$$, 17, $$안쪽 여백$$, $$padding$$, $$challenge$$, 1,
$$모든 방향에 20px 패딩을 추가하세요.$$,
$$- padding: 20px\n- 안쪽 여백$$,
$$[{"input": "", "output": "20px 패딩"}]$$,
$$.box {\n    /* 패딩 추가 */\n}$$,
$$.box {\n    padding: 20px;\n}$$,
$$[{"input": "", "expected": "20px padding"}]$$,
$$["padding은 콘텐츠와 테두리 사이 공간입니다"]$$,
$$["box-model", "padding"]$$, 5),

($$css-margin$$, $$css$$, $$syntax$$, 18, $$바깥 여백$$, $$margin$$, $$challenge$$, 1,
$$요소를 가운데 정렬하기 위해 margin을 auto로 설정하세요.$$,
$$- margin: 0 auto\n- 좌우 자동 여백$$,
$$[{"input": "", "output": "중앙 정렬"}]$$,
$$.container {\n    width: 800px;\n    /* 가운데 정렬 */\n}$$,
$$.container {\n    width: 800px;\n    margin: 0 auto;\n}$$,
$$[{"input": "", "expected": "centered with margin"}]$$,
$$["margin auto는 block 요소를 가운데 정렬합니다"]$$,
$$["box-model", "margin"]$$, 8),

($$css-border$$, $$css$$, $$syntax$$, 19, $$테두리$$, $$border$$, $$challenge$$, 1,
$$2px 실선 검은색 테두리를 추가하세요.$$,
$$- border: 2px solid black\n- 두께 스타일 색상$$,
$$[{"input": "", "output": "검은 테두리"}]$$,
$$.box {\n    /* 테두리 */\n}$$,
$$.box {\n    border: 2px solid black;\n}$$,
$$[{"input": "", "expected": "2px solid border"}]$$,
$$["border는 width, style, color 순서로 작성합니다"]$$,
$$["box-model", "border"]$$, 5),

($$css-box-sizing$$, $$css$$, $$syntax$$, 20, $$box-sizing$$, $$border-box 모델$$, $$challenge$$, 1,
$$box-sizing을 border-box로 설정하세요.$$,
$$- box-sizing: border-box\n- padding/border 포함 크기$$,
$$[{"input": "", "output": "border-box"}]$$,
$$* {\n    /* box-sizing 설정 */\n}$$,
$$* {\n    box-sizing: border-box;\n}$$,
$$[{"input": "", "expected": "border-box sizing"}]$$,
$$["border-box는 width에 padding과 border를 포함합니다"]$$,
$$["box-model", "box-sizing"]$$, 8);

-- Unit 5: Display와 Position (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-display-block$$, $$css$$, $$syntax$$, 21, $$block 디스플레이$$, $$display: block$$, $$challenge$$, 1,
$$인라인 요소를 블록으로 변경하세요.$$,
$$- display: block\n- 한 줄 차지$$,
$$[{"input": "", "output": "블록 요소"}]$$,
$$span {\n    /* 블록으로 */\n}$$,
$$span {\n    display: block;\n}$$,
$$[{"input": "", "expected": "block display"}]$$,
$$["block 요소는 전체 너비를 차지합니다"]$$,
$$["layout", "display"]$$, 5),

($$css-display-inline$$, $$css$$, $$syntax$$, 22, $$inline 디스플레이$$, $$display: inline$$, $$challenge$$, 1,
$$블록 요소를 인라인으로 변경하세요.$$,
$$- display: inline\n- 한 줄에 나란히$$,
$$[{"input": "", "output": "인라인 요소"}]$$,
$$div {\n    /* 인라인으로 */\n}$$,
$$div {\n    display: inline;\n}$$,
$$[{"input": "", "expected": "inline display"}]$$,
$$["inline 요소는 width/height를 가질 수 없습니다"]$$,
$$["layout", "display"]$$, 5),

($$css-display-none$$, $$css$$, $$syntax$$, 23, $$요소 숨기기$$, $$display: none$$, $$challenge$$, 1,
$$요소를 완전히 숨기세요.$$,
$$- display: none\n- 공간도 차지하지 않음$$,
$$[{"input": "", "output": "숨겨진 요소"}]$$,
$$.hidden {\n    /* 숨기기 */\n}$$,
$$.hidden {\n    display: none;\n}$$,
$$[{"input": "", "expected": "display none"}]$$,
$$["visibility: hidden과 달리 공간을 차지하지 않습니다"]$$,
$$["layout", "display", "visibility"]$$, 5),

($$css-position-relative$$, $$css$$, $$syntax$$, 24, $$상대 위치$$, $$position: relative$$, $$challenge$$, 1,
$$요소를 원래 위치에서 위로 10px 이동하세요.$$,
$$- position: relative\n- top: -10px$$,
$$[{"input": "", "output": "상대 이동"}]$$,
$$.box {\n    /* 위로 10px 이동 */\n}$$,
$$.box {\n    position: relative;\n    top: -10px;\n}$$,
$$[{"input": "", "expected": "relative position"}]$$,
$$["relative는 원래 위치 기준으로 이동합니다"]$$,
$$["layout", "position"]$$, 8),

($$css-position-absolute$$, $$css$$, $$syntax$$, 25, $$절대 위치$$, $$position: absolute$$, $$challenge$$, 1,
$$요소를 부모의 오른쪽 상단에 배치하세요.$$,
$$- position: absolute\n- top: 0, right: 0$$,
$$[{"input": "", "output": "절대 위치"}]$$,
$$.badge {\n    /* 오른쪽 상단 */\n}$$,
$$.badge {\n    position: absolute;\n    top: 0;\n    right: 0;\n}$$,
$$[{"input": "", "expected": "absolute position"}]$$,
$$["absolute는 position이 있는 가장 가까운 조상 기준입니다"]$$,
$$["layout", "position"]$$, 8);

-- Unit 6: Flexbox 기본 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-flex-container$$, $$css$$, $$syntax$$, 26, $$Flex 컨테이너$$, $$display: flex$$, $$challenge$$, 1,
$$컨테이너를 flex로 만드세요.$$,
$$- display: flex\n- flex 레이아웃 활성화$$,
$$[{"input": "", "output": "flex 컨테이너"}]$$,
$$.container {\n    /* flex 활성화 */\n}$$,
$$.container {\n    display: flex;\n}$$,
$$[{"input": "", "expected": "flex container"}]$$,
$$["display: flex는 자식들을 flex 아이템으로 만듭니다"]$$,
$$["flexbox", "basics"]$$, 5),

($$css-justify-content$$, $$css$$, $$syntax$$, 27, $$주축 정렬$$, $$justify-content$$, $$challenge$$, 1,
$$아이템을 가운데 정렬하세요.$$,
$$- justify-content: center\n- 주축(가로) 정렬$$,
$$[{"input": "", "output": "가운데 정렬"}]$$,
$$.container {\n    display: flex;\n    /* 가운데 정렬 */\n}$$,
$$.container {\n    display: flex;\n    justify-content: center;\n}$$,
$$[{"input": "", "expected": "centered items"}]$$,
$$["flex-start, center, flex-end, space-between, space-around 등"]$$,
$$["flexbox", "alignment"]$$, 8),

($$css-align-items$$, $$css$$, $$syntax$$, 28, $$교차축 정렬$$, $$align-items$$, $$challenge$$, 1,
$$아이템을 세로 가운데 정렬하세요.$$,
$$- align-items: center\n- 교차축(세로) 정렬$$,
$$[{"input": "", "output": "세로 중앙"}]$$,
$$.container {\n    display: flex;\n    height: 200px;\n    /* 세로 가운데 */\n}$$,
$$.container {\n    display: flex;\n    height: 200px;\n    align-items: center;\n}$$,
$$[{"input": "", "expected": "vertically centered"}]$$,
$$["stretch, flex-start, center, flex-end, baseline"]$$,
$$["flexbox", "alignment"]$$, 8),

($$css-flex-direction$$, $$css$$, $$syntax$$, 29, $$Flex 방향$$, $$flex-direction$$, $$challenge$$, 1,
$$아이템을 세로로 배치하세요.$$,
$$- flex-direction: column\n- 세로 방향$$,
$$[{"input": "", "output": "세로 배치"}]$$,
$$.container {\n    display: flex;\n    /* 세로 배치 */\n}$$,
$$.container {\n    display: flex;\n    flex-direction: column;\n}$$,
$$[{"input": "", "expected": "column direction"}]$$,
$$["row(기본), column, row-reverse, column-reverse"]$$,
$$["flexbox", "direction"]$$, 8),

($$css-flex-gap$$, $$css$$, $$syntax$$, 30, $$Flex 간격$$, $$gap 속성$$, $$challenge$$, 1,
$$아이템 사이에 20px 간격을 추가하세요.$$,
$$- gap: 20px\n- 아이템 간 간격$$,
$$[{"input": "", "output": "20px 간격"}]$$,
$$.container {\n    display: flex;\n    /* 간격 추가 */\n}$$,
$$.container {\n    display: flex;\n    gap: 20px;\n}$$,
$$[{"input": "", "expected": "20px gap"}]$$,
$$["gap은 margin보다 간격 조절이 편리합니다"]$$,
$$["flexbox", "gap"]$$, 8);

-- Unit 7: 리스트와 테이블 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-list-style-type$$, $$css$$, $$syntax$$, 31, $$리스트 스타일$$, $$list-style-type$$, $$challenge$$, 1,
$$리스트 마커를 사각형으로 변경하세요.$$,
$$- list-style-type: square\n- 리스트 불릿 스타일$$,
$$[{"input": "", "output": "사각형 마커"}]$$,
$$ul {\n    /* 사각형 마커 */\n}$$,
$$ul {\n    list-style-type: square;\n}$$,
$$[{"input": "", "expected": "square markers"}]$$,
$$["disc, circle, square, none, decimal 등"]$$,
$$["list", "style"]$$, 5),

($$css-list-style-none$$, $$css$$, $$syntax$$, 32, $$리스트 마커 제거$$, $$list-style: none$$, $$challenge$$, 1,
$$리스트 마커를 완전히 제거하세요.$$,
$$- list-style: none\n- 마커 숨김$$,
$$[{"input": "", "output": "마커 없음"}]$$,
$$ul {\n    /* 마커 제거 */\n}$$,
$$ul {\n    list-style: none;\n}$$,
$$[{"input": "", "expected": "no markers"}]$$,
$$["네비게이션 메뉴를 만들 때 자주 사용합니다"]$$,
$$["list", "style"]$$, 5),

($$css-table-border-collapse$$, $$css$$, $$syntax$$, 33, $$테이블 테두리 병합$$, $$border-collapse$$, $$challenge$$, 1,
$$테이블 테두리를 하나로 합치세요.$$,
$$- border-collapse: collapse\n- 이중 테두리 제거$$,
$$[{"input": "", "output": "병합된 테두리"}]$$,
$$table {\n    /* 테두리 병합 */\n}$$,
$$table {\n    border-collapse: collapse;\n}$$,
$$[{"input": "", "expected": "collapsed borders"}]$$,
$$["collapse는 인접한 테두리를 하나로 만듭니다"]$$,
$$["table", "border"]$$, 5),

($$css-table-width$$, $$css$$, $$syntax$$, 34, $$테이블 너비$$, $$100% 너비$$, $$challenge$$, 1,
$$테이블이 전체 너비를 차지하게 하세요.$$,
$$- width: 100%\n- 부모 너비만큼$$,
$$[{"input": "", "output": "전체 너비"}]$$,
$$table {\n    /* 전체 너비 */\n}$$,
$$table {\n    width: 100%;\n}$$,
$$[{"input": "", "expected": "full width table"}]$$,
$$["테이블은 기본적으로 콘텐츠 크기만큼만 차지합니다"]$$,
$$["table", "width"]$$, 5),

($$css-td-padding$$, $$css$$, $$syntax$$, 35, $$테이블 셀 패딩$$, $$td 스타일$$, $$challenge$$, 1,
$$테이블 셀에 10px 패딩을 추가하세요.$$,
$$- td, th 선택자\n- padding: 10px$$,
$$[{"input": "", "output": "셀 패딩"}]$$,
$$td, th {\n    /* 패딩 추가 */\n}$$,
$$td, th {\n    padding: 10px;\n}$$,
$$[{"input": "", "expected": "cell padding"}]$$,
$$["셀 패딩은 테이블 가독성을 향상시킵니다"]$$,
$$["table", "padding"]$$, 5);

-- Unit 8: 가상 클래스 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-hover$$, $$css$$, $$syntax$$, 36, $$호버 효과$$, $$:hover 가상 클래스$$, $$challenge$$, 1,
$$마우스를 올렸을 때 배경색을 파란색으로 변경하세요.$$,
$$- :hover 가상 클래스\n- 마우스 오버 상태$$,
$$[{"input": "", "output": "호버 시 파란 배경"}]$$,
$$button {\n    /* 호버 효과 */\n}$$,
$$button:hover {\n    background-color: blue;\n}$$,
$$[{"input": "", "expected": "hover blue bg"}]$$,
$$[":hover는 마우스 포인터가 요소 위에 있을 때 적용됩니다"]$$,
$$["pseudo-class", "hover"]$$, 5),

($$css-active$$, $$css$$, $$syntax$$, 37, $$활성 상태$$, $$:active 가상 클래스$$, $$challenge$$, 1,
$$클릭하는 순간 글자색을 흰색으로 변경하세요.$$,
$$- :active 가상 클래스\n- 클릭 중 상태$$,
$$[{"input": "", "output": "클릭 시 흰 글자"}]$$,
$$button {\n    /* 활성 상태 */\n}$$,
$$button:active {\n    color: white;\n}$$,
$$[{"input": "", "expected": "active white text"}]$$,
$$[":active는 요소를 클릭하는 동안 적용됩니다"]$$,
$$["pseudo-class", "active"]$$, 5),

($$css-focus$$, $$css$$, $$syntax$$, 38, $$포커스 상태$$, $$:focus 가상 클래스$$, $$challenge$$, 1,
$$입력 필드에 포커스 시 테두리를 파란색으로 변경하세요.$$,
$$- :focus 가상 클래스\n- 포커스 상태$$,
$$[{"input": "", "output": "포커스 시 파란 테두리"}]$$,
$$input {\n    /* 포커스 스타일 */\n}$$,
$$input:focus {\n    border-color: blue;\n}$$,
$$[{"input": "", "expected": "focus blue border"}]$$,
$$[":focus는 키보드나 클릭으로 포커스된 요소에 적용됩니다"]$$,
$$["pseudo-class", "focus"]$$, 5),

($$css-first-child$$, $$css$$, $$syntax$$, 39, $$첫 번째 자식$$, $$:first-child$$, $$challenge$$, 1,
$$첫 번째 li 요소의 글자를 굵게 만드세요.$$,
$$- :first-child 가상 클래스\n- 첫 자식 선택$$,
$$[{"input": "", "output": "첫 항목 굵게"}]$$,
$$li {\n    /* 첫 번째만 굵게 */\n}$$,
$$li:first-child {\n    font-weight: bold;\n}$$,
$$[{"input": "", "expected": "first child bold"}]$$,
$$[":first-child는 부모의 첫 번째 자식을 선택합니다"]$$,
$$["pseudo-class", "first-child"]$$, 8),

($$css-last-child$$, $$css$$, $$syntax$$, 40, $$마지막 자식$$, $$:last-child$$, $$challenge$$, 1,
$$마지막 p 요소의 margin-bottom을 0으로 만드세요.$$,
$$- :last-child 가상 클래스\n- 마지막 자식 선택$$,
$$[{"input": "", "output": "마지막 여백 제거"}]$$,
$$p {\n    /* 마지막만 margin 0 */\n}$$,
$$p:last-child {\n    margin-bottom: 0;\n}$$,
$$[{"input": "", "expected": "last child no margin"}]$$,
$$["마지막 요소의 여백을 제거하면 레이아웃이 깔끔해집니다"]$$,
$$["pseudo-class", "last-child"]$$, 8);

-- Unit 9: 단위와 값 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-percentage$$, $$css$$, $$syntax$$, 41, $$퍼센트 단위$$, $$% 크기$$, $$challenge$$, 1,
$$너비를 부모의 50%로 설정하세요.$$,
$$- width: 50%\n- 부모 기준 비율$$,
$$[{"input": "", "output": "50% 너비"}]$$,
$$.half {\n    /* 50% 너비 */\n}$$,
$$.half {\n    width: 50%;\n}$$,
$$[{"input": "", "expected": "50% width"}]$$,
$$["%는 부모 요소를 기준으로 계산됩니다"]$$,
$$["units", "percentage"]$$, 5),

($$css-em-unit$$, $$css$$, $$syntax$$, 42, $$em 단위$$, $$상대적 크기$$, $$challenge$$, 1,
$$글자 크기를 부모의 1.5배로 설정하세요.$$,
$$- font-size: 1.5em\n- 부모 글자 크기 기준$$,
$$[{"input": "", "output": "1.5배 크기"}]$$,
$$.large {\n    /* 1.5배 크기 */\n}$$,
$$.large {\n    font-size: 1.5em;\n}$$,
$$[{"input": "", "expected": "1.5em font"}]$$,
$$["em은 부모 요소의 font-size를 기준으로 합니다"]$$,
$$["units", "em"]$$, 8),

($$css-rem-unit$$, $$css$$, $$syntax$$, 43, $$rem 단위$$, $$루트 기준 크기$$, $$challenge$$, 1,
$$글자 크기를 루트의 2배로 설정하세요.$$,
$$- font-size: 2rem\n- html 요소 기준$$,
$$[{"input": "", "output": "2배 크기"}]$$,
$$.heading {\n    /* 2rem 크기 */\n}$$,
$$.heading {\n    font-size: 2rem;\n}$$,
$$[{"input": "", "expected": "2rem font"}]$$,
$$["rem은 html 요소의 font-size를 기준으로 합니다"]$$,
$$["units", "rem"]$$, 8),

($$css-vw-vh$$, $$css$$, $$syntax$$, 44, $$Viewport 단위$$, $$vw, vh$$, $$challenge$$, 1,
$$너비를 뷰포트의 100vw로 설정하세요.$$,
$$- width: 100vw\n- 뷰포트 너비 100%$$,
$$[{"input": "", "output": "전체 뷰포트 너비"}]$$,
$$.full-width {\n    /* 100vw */\n}$$,
$$.full-width {\n    width: 100vw;\n}$$,
$$[{"input": "", "expected": "100vw width"}]$$,
$$["vw는 뷰포트 너비의 1%, vh는 뷰포트 높이의 1%"]$$,
$$["units", "viewport"]$$, 8),

($$css-calc$$, $$css$$, $$syntax$$, 45, $$calc() 함수$$, $$계산식 사용$$, $$challenge$$, 1,
$$너비를 "100% - 50px"로 계산하세요.$$,
$$- calc() 함수\n- 단위 혼합 계산$$,
$$[{"input": "", "output": "계산된 너비"}]$$,
$$.box {\n    /* calc 사용 */\n}$$,
$$.box {\n    width: calc(100% - 50px);\n}$$,
$$[{"input": "", "expected": "calc width"}]$$,
$$["calc()로 서로 다른 단위를 계산할 수 있습니다"]$$,
$$["units", "calc"]$$, 10);

-- Unit 10: 기타 스타일 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-opacity$$, $$css$$, $$syntax$$, 46, $$투명도$$, $$opacity$$, $$challenge$$, 1,
$$요소를 50% 투명하게 만드세요.$$,
$$- opacity: 0.5\n- 0(투명) ~ 1(불투명)$$,
$$[{"input": "", "output": "반투명"}]$$,
$$.transparent {\n    /* 50% 투명도 */\n}$$,
$$.transparent {\n    opacity: 0.5;\n}$$,
$$[{"input": "", "expected": "0.5 opacity"}]$$,
$$["opacity는 요소 전체의 투명도를 조절합니다"]$$,
$$["effects", "opacity"]$$, 5),

($$css-cursor$$, $$css$$, $$syntax$$, 47, $$커서 스타일$$, $$cursor$$, $$challenge$$, 1,
$$마우스 커서를 포인터로 변경하세요.$$,
$$- cursor: pointer\n- 손가락 모양$$,
$$[{"input": "", "output": "포인터 커서"}]$$,
$$button {\n    /* 포인터 커서 */\n}$$,
$$button {\n    cursor: pointer;\n}$$,
$$[{"input": "", "expected": "pointer cursor"}]$$,
$$["pointer, default, move, text, wait 등 다양한 커서가 있습니다"]$$,
$$["interaction", "cursor"]$$, 5),

($$css-overflow-hidden$$, $$css$$, $$syntax$$, 48, $$넘침 숨김$$, $$overflow: hidden$$, $$challenge$$, 1,
$$넘치는 콘텐츠를 숨기세요.$$,
$$- overflow: hidden\n- 넘침 잘라내기$$,
$$[{"input": "", "output": "넘침 숨김"}]$$,
$$.box {\n    /* 넘침 숨김 */\n}$$,
$$.box {\n    overflow: hidden;\n}$$,
$$[{"input": "", "expected": "overflow hidden"}]$$,
$$["visible, hidden, scroll, auto 값을 사용할 수 있습니다"]$$,
$$["overflow", "hidden"]$$, 5),

($$css-border-radius$$, $$css$$, $$syntax$$, 49, $$둥근 모서리$$, $$border-radius$$, $$challenge$$, 1,
$$모서리를 10px 둥글게 만드세요.$$,
$$- border-radius: 10px\n- 둥근 테두리$$,
$$[{"input": "", "output": "둥근 모서리"}]$$,
$$.card {\n    /* 둥근 모서리 */\n}$$,
$$.card {\n    border-radius: 10px;\n}$$,
$$[{"input": "", "expected": "10px radius"}]$$,
$$["50%로 설정하면 원이 됩니다"]$$,
$$["border", "radius"]$$, 5),

($$css-box-shadow$$, $$css$$, $$syntax$$, 50, $$그림자$$, $$box-shadow$$, $$challenge$$, 1,
$$박스에 그림자를 추가하세요.$$,
$$- box-shadow: 0 2px 4px rgba(0,0,0,0.1)\n- x, y, blur, color$$,
$$[{"input": "", "output": "그림자 효과"}]$$,
$$.card {\n    /* 그림자 */\n}$$,
$$.card {\n    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n}$$,
$$[{"input": "", "expected": "box shadow"}]$$,
$$["box-shadow는 x-offset, y-offset, blur, spread, color 순입니다"]$$,
$$["effects", "shadow"]$$, 8);

-- ====================================
-- 완료 메시지
-- ====================================

-- ====================================
-- CSS Language Challenges - Part 2
-- Levels 51-100 (MEDIUM 30개 + HARD 20개)
-- ====================================

-- Unit 11: 고급 Flexbox (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-flex-wrap$$, $$css$$, $$syntax$$, 51, $$Flex 줄바꿈$$, $$flex-wrap$$, $$challenge$$, 2,
$$아이템이 넘치면 다음 줄로 넘기세요.$$,
$$- flex-wrap: wrap\n- 여러 줄 허용$$,
$$[{"input": "", "output": "줄바꿈 flex"}]$$,
$$.container {\n    display: flex;\n    /* 줄바꿈 허용 */\n}$$,
$$.container {\n    display: flex;\n    flex-wrap: wrap;\n}$$,
$$[{"input": "", "expected": "flex wrap"}]$$,
$$["nowrap(기본), wrap, wrap-reverse 값을 사용할 수 있습니다"]$$,
$$["flexbox", "wrap"]$$, 10),

($$css-flex-grow$$, $$css$$, $$syntax$$, 52, $$Flex 성장$$, $$flex-grow$$, $$challenge$$, 2,
$$특정 아이템이 남은 공간을 모두 차지하게 하세요.$$,
$$- flex-grow: 1\n- 성장 비율$$,
$$[{"input": "", "output": "성장하는 아이템"}]$$,
$$.item {\n    /* 남은 공간 차지 */\n}$$,
$$.item {\n    flex-grow: 1;\n}$$,
$$[{"input": "", "expected": "flex-grow 1"}]$$,
$$["flex-grow는 남은 공간을 비율로 나눕니다"]$$,
$$["flexbox", "flex-grow"]$$, 12),

($$css-flex-shrink$$, $$css$$, $$syntax$$, 53, $$Flex 축소$$, $$flex-shrink$$, $$challenge$$, 2,
$$아이템이 축소되지 않게 하세요.$$,
$$- flex-shrink: 0\n- 축소 방지$$,
$$[{"input": "", "output": "축소 안 됨"}]$$,
$$.item {\n    /* 축소 방지 */\n}$$,
$$.item {\n    flex-shrink: 0;\n}$$,
$$[{"input": "", "expected": "no shrink"}]$$,
$$["flex-shrink: 0은 고정 크기 아이템을 만듭니다"]$$,
$$["flexbox", "flex-shrink"]$$, 12),

($$css-align-self$$, $$css$$, $$syntax$$, 54, $$개별 정렬$$, $$align-self$$, $$challenge$$, 2,
$$특정 아이템만 다르게 정렬하세요.$$,
$$- align-self: flex-end\n- 개별 아이템 정렬$$,
$$[{"input": "", "output": "개별 정렬"}]$$,
$$.special {\n    /* 하단 정렬 */\n}$$,
$$.special {\n    align-self: flex-end;\n}$$,
$$[{"input": "", "expected": "align-self end"}]$$,
$$["align-self는 개별 아이템의 align-items를 재정의합니다"]$$,
$$["flexbox", "align-self"]$$, 12),

($$css-order$$, $$css$$, $$syntax$$, 55, $$Flex 순서$$, $$order 속성$$, $$challenge$$, 2,
$$아이템의 시각적 순서를 변경하세요.$$,
$$- order: -1\n- 표시 순서 조정$$,
$$[{"input": "", "output": "순서 변경"}]$$,
$$.first {\n    /* 맨 앞으로 */\n}$$,
$$.first {\n    order: -1;\n}$$,
$$[{"input": "", "expected": "order -1"}]$$,
$$["order 값이 작을수록 앞에 배치됩니다"]$$,
$$["flexbox", "order"]$$, 12);

-- Unit 12: Grid 기본 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-grid-container$$, $$css$$, $$syntax$$, 56, $$Grid 컨테이너$$, $$display: grid$$, $$challenge$$, 2,
$$Grid 레이아웃을 활성화하세요.$$,
$$- display: grid\n- grid 컨테이너 생성$$,
$$[{"input": "", "output": "grid 컨테이너"}]$$,
$$.container {\n    /* grid 활성화 */\n}$$,
$$.container {\n    display: grid;\n}$$,
$$[{"input": "", "expected": "grid container"}]$$,
$$["display: grid는 2차원 레이아웃을 만듭니다"]$$,
$$["grid", "basics"]$$, 10),

($$css-grid-template-columns$$, $$css$$, $$syntax$$, 57, $$Grid 열$$, $$grid-template-columns$$, $$challenge$$, 2,
$$3개의 동일한 너비 열을 만드세요.$$,
$$- grid-template-columns: 1fr 1fr 1fr\n- 또는 repeat(3, 1fr)$$,
$$[{"input": "", "output": "3열 그리드"}]$$,
$$.container {\n    display: grid;\n    /* 3개 열 */\n}$$,
$$.container {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n}$$,
$$[{"input": "", "expected": "3 columns"}]$$,
$$["fr은 fraction 단위로 비율을 나타냅니다"]$$,
$$["grid", "columns"]$$, 12),

($$css-grid-gap$$, $$css$$, $$syntax$$, 58, $$Grid 간격$$, $$gap$$, $$challenge$$, 2,
$$그리드 아이템 사이에 20px 간격을 추가하세요.$$,
$$- gap: 20px\n- 행과 열 간격$$,
$$[{"input": "", "output": "20px 간격"}]$$,
$$.container {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n    /* 간격 추가 */\n}$$,
$$.container {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n    gap: 20px;\n}$$,
$$[{"input": "", "expected": "20px gap"}]$$,
$$["gap은 row-gap과 column-gap의 단축 속성입니다"]$$,
$$["grid", "gap"]$$, 10),

($$css-grid-column-span$$, $$css$$, $$syntax$$, 59, $$열 병합$$, $$grid-column$$, $$challenge$$, 2,
$$아이템이 2개 열을 차지하게 하세요.$$,
$$- grid-column: span 2\n- 열 병합$$,
$$[{"input": "", "output": "2열 병합"}]$$,
$$.wide {\n    /* 2열 차지 */\n}$$,
$$.wide {\n    grid-column: span 2;\n}$$,
$$[{"input": "", "expected": "span 2 columns"}]$$,
$$["span은 몇 개의 셀을 차지할지 지정합니다"]$$,
$$["grid", "span"]$$, 12),

($$css-grid-template-areas$$, $$css$$, $$syntax$$, 60, $$Grid 영역$$, $$grid-template-areas$$, $$challenge$$, 2,
$$이름이 있는 그리드 영역을 정의하세요.$$,
$$- grid-template-areas\n- 시각적 레이아웃 정의$$,
$$[{"input": "", "output": "명명된 영역"}]$$,
$$.container {\n    display: grid;\n    /* 영역 정의 */\n}$$,
$func$.container {\n    display: grid;\n    grid-template-areas:\n        "header header"\n        "sidebar main"\n        "footer footer";\n}$func$,
$$[{"input": "", "expected": "template areas"}]$$,
$$["grid-area로 요소를 영역에 배치합니다"]$$,
$$["grid", "areas"]$$, 15);

-- Unit 13: 변형과 애니메이션 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-transform-rotate$$, $$css$$, $$syntax$$, 61, $$회전 변형$$, $$transform: rotate$$, $$challenge$$, 2,
$$요소를 45도 회전하세요.$$,
$$- transform: rotate(45deg)\n- 회전 변환$$,
$$[{"input": "", "output": "45도 회전"}]$$,
$$.rotated {\n    /* 45도 회전 */\n}$$,
$$.rotated {\n    transform: rotate(45deg);\n}$$,
$$[{"input": "", "expected": "45deg rotation"}]$$,
$$["deg, rad, turn 단위를 사용할 수 있습니다"]$$,
$$["transform", "rotate"]$$, 10),

($$css-transform-scale$$, $$css$$, $$syntax$$, 62, $$크기 변형$$, $$transform: scale$$, $$challenge$$, 2,
$$호버 시 요소를 1.2배 확대하세요.$$,
$$- transform: scale(1.2)\n- 크기 조정$$,
$$[{"input": "", "output": "확대 효과"}]$$,
$$.card:hover {\n    /* 1.2배 확대 */\n}$$,
$$.card:hover {\n    transform: scale(1.2);\n}$$,
$$[{"input": "", "expected": "scale 1.2"}]$$,
$$["scale(x, y)로 가로세로 다르게 확대할 수 있습니다"]$$,
$$["transform", "scale"]$$, 10),

($$css-transition$$, $$css$$, $$syntax$$, 63, $$전환 효과$$, $$transition$$, $$challenge$$, 2,
$$모든 속성 변화에 0.3초 전환 효과를 추가하세요.$$,
$$- transition: all 0.3s\n- 부드러운 변화$$,
$$[{"input": "", "output": "전환 효과"}]$$,
$$.button {\n    /* 전환 효과 */\n}$$,
$$.button {\n    transition: all 0.3s;\n}$$,
$$[{"input": "", "expected": "transition 0.3s"}]$$,
$$["transition은 속성, 시간, 타이밍 함수를 지정합니다"]$$,
$$["transition", "animation"]$$, 12),

($$css-keyframes$$, $$css$$, $$syntax$$, 64, $$키프레임 애니메이션$$, $$@keyframes$$, $$challenge$$, 2,
$$페이드인 애니메이션을 정의하세요.$$,
$$- @keyframes 규칙\n- opacity 변화$$,
$$[{"input": "", "output": "페이드인"}]$$,
$$/* 페이드인 애니메이션 */\n$$,
$$@keyframes fadeIn {\n    from {\n        opacity: 0;\n    }\n    to {\n        opacity: 1;\n    }\n}$$,
$$[{"input": "", "expected": "fadeIn keyframes"}]$$,
$$["from/to 또는 0%/100% 키워드를 사용합니다"]$$,
$$["animation", "keyframes"]$$, 15),

($$css-animation$$, $$css$$, $$syntax$$, 65, $$애니메이션 적용$$, $$animation$$, $$challenge$$, 2,
$$fadeIn 애니메이션을 1초 동안 재생하세요.$$,
$$- animation: fadeIn 1s\n- 애니메이션 실행$$,
$$[{"input": "", "output": "애니메이션 실행"}]$$,
$$.element {\n    /* 애니메이션 적용 */\n}$$,
$$.element {\n    animation: fadeIn 1s;\n}$$,
$$[{"input": "", "expected": "animation applied"}]$$,
$$["animation은 이름, 시간, 타이밍, 반복 등을 지정합니다"]$$,
$$["animation", "apply"]$$, 12);

-- Unit 14: 반응형 디자인 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-media-query-basic$$, $$css$$, $$syntax$$, 66, $$미디어 쿼리$$, $$@media$$, $$challenge$$, 2,
$$화면이 768px 이하일 때 글자 크기를 14px로 변경하세요.$$,
$$- @media (max-width: 768px)\n- 반응형 중단점$$,
$$[{"input": "", "output": "모바일 글자 크기"}]$$,
$$body {\n    font-size: 16px;\n}\n\n/* 768px 이하 */\n$$,
$func$body {\n    font-size: 16px;\n}\n\n@media (max-width: 768px) {\n    body {\n        font-size: 14px;\n    }\n}$func$,
$$[{"input": "", "expected": "media query"}]$$,
$$["max-width는 이하, min-width는 이상을 의미합니다"]$$,
$$["responsive", "media-query"]$$, 12),

($$css-mobile-first$$, $$css$$, $$syntax$$, 67, $$모바일 우선$$, $$min-width 미디어 쿼리$$, $$challenge$$, 2,
$$모바일 우선으로 태블릿 이상에서 3열 그리드를 만드세요.$$,
$$- 기본: 1열\n- min-width: 768px에서 3열$$,
$$[{"input": "", "output": "모바일 우선"}]$$,
$$.container {\n    /* 기본: 1열 */\n}\n\n/* 768px 이상 */\n$$,
$func$.container {\n    display: grid;\n    grid-template-columns: 1fr;\n}\n\n@media (min-width: 768px) {\n    .container {\n        grid-template-columns: repeat(3, 1fr);\n    }\n}$func$,
$$[{"input": "", "expected": "mobile first grid"}]$$,
$$["모바일 우선은 min-width를 사용합니다"]$$,
$$["responsive", "mobile-first"]$$, 15),

($$css-responsive-images$$, $$css$$, $$syntax$$, 68, $$반응형 이미지$$, $$max-width: 100%$$, $$challenge$$, 2,
$$이미지가 부모를 넘지 않게 하세요.$$,
$$- max-width: 100%\n- height: auto$$,
$$[{"input": "", "output": "반응형 이미지"}]$$,
$$img {\n    /* 반응형 설정 */\n}$$,
$$img {\n    max-width: 100%;\n    height: auto;\n}$$,
$$[{"input": "", "expected": "responsive img"}]$$,
$$["max-width: 100%는 이미지가 부모를 넘지 않게 합니다"]$$,
$$["responsive", "images"]$$, 10),

($$css-container-query$$, $$css$$, $$syntax$$, 69, $$컨테이너 쿼리$$, $$@container$$, $$challenge$$, 2,
$$컨테이너 너비 기준으로 스타일을 변경하세요.$$,
$$- container-type: inline-size\n- @container 쿼리$$,
$$[{"input": "", "output": "컨테이너 쿼리"}]$$,
$$.parent {\n    /* 컨테이너 설정 */\n}\n\n/* 컨테이너 400px 이상 */\n$$,
$func$.parent {\n    container-type: inline-size;\n}\n\n@container (min-width: 400px) {\n    .child {\n        font-size: 18px;\n    }\n}$func$,
$$[{"input": "", "expected": "container query"}]$$,
$$["컨테이너 쿼리는 부모 크기 기준으로 반응합니다"]$$,
$$["responsive", "container-query"]$$, 18),

($$css-clamp$$, $$css$$, $$syntax$$, 70, $$유동적 크기$$, $$clamp() 함수$$, $$challenge$$, 2,
$$글자 크기를 최소 16px, 최대 24px로 제한하세요.$$,
$$- clamp(min, preferred, max)\n- 유동적 크기$$,
$$[{"input": "", "output": "clamp 크기"}]$$,
$$h1 {\n    /* clamp 사용 */\n}$$,
$$h1 {\n    font-size: clamp(16px, 5vw, 24px);\n}$$,
$$[{"input": "", "expected": "clamp font size"}]$$,
$$["clamp는 최소, 선호, 최대 값 사이를 유지합니다"]$$,
$$["responsive", "clamp"]$$, 15);

-- Unit 15: 고급 선택자 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-descendant-selector$$, $$css$$, $$syntax$$, 71, $$자손 선택자$$, $$공백 선택자$$, $$challenge$$, 2,
$$nav 안의 모든 a 태그를 선택하세요.$$,
$$- 공백으로 자손 선택\n- nav a$$,
$$[{"input": "", "output": "nav 링크"}]$$,
$$/* nav 안의 a 선택 */\n$$,
$$nav a {\n    color: blue;\n}$$,
$$[{"input": "", "expected": "nav a selected"}]$$,
$$["자손 선택자는 모든 하위 요소를 선택합니다"]$$,
$$["selector", "descendant"]$$, 10),

($$css-child-selector$$, $$css$$, $$syntax$$, 72, $$자식 선택자$$, $$> 선택자$$, $$challenge$$, 2,
$$div의 직접 자식인 p만 선택하세요.$$,
$$- > 선택자\n- 직접 자식만$$,
$$[{"input": "", "output": "직접 자식"}]$$,
$$/* div > p */\n$$,
$$div > p {\n    margin-bottom: 10px;\n}$$,
$$[{"input": "", "expected": "direct children"}]$$,
$$["자식 선택자는 직접 자식만 선택합니다"]$$,
$$["selector", "child"]$$, 10),

($$css-adjacent-sibling$$, $$css$$, $$syntax$$, 73, $$인접 형제 선택자$$, $$+ 선택자$$, $$challenge$$, 2,
$$h2 바로 다음의 p를 선택하세요.$$,
$$- + 선택자\n- 바로 다음 형제$$,
$$[{"input": "", "output": "인접 형제"}]$$,
$$/* h2 + p */\n$$,
$$h2 + p {\n    margin-top: 0;\n}$$,
$$[{"input": "", "expected": "adjacent sibling"}]$$,
$$["+는 바로 다음 형제만 선택합니다"]$$,
$$["selector", "adjacent"]$$, 12),

($$css-general-sibling$$, $$css$$, $$syntax$$, 74, $$일반 형제 선택자$$, $$~ 선택자$$, $$challenge$$, 2,
$$h2 이후의 모든 p를 선택하세요.$$,
$$- ~ 선택자\n- 뒤의 모든 형제$$,
$$[{"input": "", "output": "모든 형제"}]$$,
$$/* h2 ~ p */\n$$,
$$h2 ~ p {\n    color: gray;\n}$$,
$$[{"input": "", "expected": "general siblings"}]$$,
$$["~는 이후의 모든 형제를 선택합니다"]$$,
$$["selector", "sibling"]$$, 12),

($$css-attribute-selector$$, $$css$$, $$syntax$$, 75, $$속성 선택자$$, $$[속성] 선택자$$, $$challenge$$, 2,
$$target 속성이 있는 a 태그를 선택하세요.$$,
$$- [속성] 선택자\n- 속성 존재 확인$$,
$$[{"input": "", "output": "속성 선택"}]$$,
$$/* target 속성이 있는 a */\n$$,
$$a[target] {\n    font-weight: bold;\n}$$,
$$[{"input": "", "expected": "attribute selector"}]$$,
$$["[속성=값], [속성^=값], [속성$=값] 등 다양한 형태가 있습니다"]$$,
$$["selector", "attribute"]$$, 12);

-- Unit 16: 가상 요소 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-before$$, $$css$$, $$syntax$$, 76, $$::before 가상 요소$$, $$앞에 콘텐츠 추가$$, $$challenge$$, 3,
$$모든 링크 앞에 "→" 아이콘을 추가하세요.$$,
$$- ::before 가상 요소\n- content 속성$$,
$$[{"input": "", "output": "아이콘 추가"}]$$,
$$a {\n    /* before 추가 */\n}$$,
$$a::before {\n    content: "→ ";\n}$$,
$$[{"input": "", "expected": "before content"}]$$,
$$["::before는 요소 앞에 콘텐츠를 삽입합니다"]$$,
$$["pseudo-element", "before", "hard"]$$, 15),

($$css-after$$, $$css$$, $$syntax$$, 77, $$::after 가상 요소$$, $$뒤에 콘텐츠 추가$$, $$challenge$$, 3,
$$외부 링크 뒤에 "↗" 아이콘을 추가하세요.$$,
$$- ::after 가상 요소\n- [target="_blank"] 선택자$$,
$$[{"input": "", "output": "외부 링크 표시"}]$$,
$$a[target="_blank"] {\n    /* after 추가 */\n}$$,
$$a[target="_blank"]::after {\n    content: " ↗";\n}$$,
$$[{"input": "", "expected": "after content"}]$$,
$$["::after는 요소 뒤에 콘텐츠를 삽입합니다"]$$,
$$["pseudo-element", "after", "hard"]$$, 15),

($$css-first-letter$$, $$css$$, $$syntax$$, 78, $$::first-letter$$, $$첫 글자 스타일$$, $$challenge$$, 3,
$$문단의 첫 글자를 크게 만드세요.$$,
$$- ::first-letter\n- font-size, color 변경$$,
$$[{"input": "", "output": "드롭캡"}]$$,
$$p::first-letter {\n    /* 첫 글자 스타일 */\n}$$,
$$p::first-letter {\n    font-size: 2em;\n    font-weight: bold;\n}$$,
$$[{"input": "", "expected": "first letter styled"}]$$,
$$["::first-letter는 드롭캡 효과를 만듭니다"]$$,
$$["pseudo-element", "first-letter", "hard"]$$, 15),

($$css-selection$$, $$css$$, $$syntax$$, 79, $$::selection$$, $$선택 영역 스타일$$, $$challenge$$, 3,
$$텍스트 선택 시 배경색을 노란색으로 변경하세요.$$,
$$- ::selection 가상 요소\n- background-color$$,
$$[{"input": "", "output": "선택 스타일"}]$$,
$$::selection {\n    /* 선택 스타일 */\n}$$,
$$::selection {\n    background-color: yellow;\n    color: black;\n}$$,
$$[{"input": "", "expected": "selection styled"}]$$,
$$["::selection은 사용자가 선택한 텍스트에 적용됩니다"]$$,
$$["pseudo-element", "selection", "hard"]$$, 15),

($$css-placeholder$$, $$css$$, $$syntax$$, 80, $$::placeholder$$, $$플레이스홀더 스타일$$, $$challenge$$, 3,
$$input의 placeholder 색상을 회색으로 변경하세요.$$,
$$- ::placeholder 가상 요소\n- color 변경$$,
$$[{"input": "", "output": "placeholder 스타일"}]$$,
$$input::placeholder {\n    /* placeholder 색상 */\n}$$,
$$input::placeholder {\n    color: gray;\n    opacity: 0.7;\n}$$,
$$[{"input": "", "expected": "placeholder styled"}]$$,
$$["::placeholder는 입력 힌트 텍스트를 스타일링합니다"]$$,
$$["pseudo-element", "placeholder", "hard"]$$, 15);

-- Unit 17: 고급 레이아웃 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-position-sticky$$, $$css$$, $$syntax$$, 81, $$Sticky 위치$$, $$position: sticky$$, $$challenge$$, 3,
$$스크롤 시 헤더를 상단에 고정하세요.$$,
$$- position: sticky\n- top: 0$$,
$$[{"input": "", "output": "고정 헤더"}]$$,
$$header {\n    /* sticky 위치 */\n}$$,
$$header {\n    position: sticky;\n    top: 0;\n    background: white;\n}$$,
$$[{"input": "", "expected": "sticky header"}]$$,
$$["sticky는 스크롤에 따라 relative와 fixed 사이를 전환합니다"]$$,
$$["layout", "position", "sticky", "hard"]$$, 18),

($$css-z-index$$, $$css$$, $$syntax$$, 82, $$쌓임 순서$$, $$z-index$$, $$challenge$$, 3,
$$모달을 다른 요소 위에 배치하세요.$$,
$$- z-index: 1000\n- position 필수$$,
$$[{"input": "", "output": "최상위 모달"}]$$,
$$.modal {\n    position: fixed;\n    /* z-index 설정 */\n}$$,
$$.modal {\n    position: fixed;\n    z-index: 1000;\n}$$,
$$[{"input": "", "expected": "high z-index"}]$$,
$$["z-index는 position이 static이 아닐 때만 동작합니다"]$$,
$$["layout", "z-index", "hard"]$$, 15),

($$css-columns$$, $$css$$, $$syntax$$, 83, $$다단 레이아웃$$, $$columns$$, $$challenge$$, 3,
$$텍스트를 3단으로 나누세요.$$,
$$- columns: 3\n- column-gap 설정$$,
$$[{"input": "", "output": "3단 레이아웃"}]$$,
$$.article {\n    /* 3단 레이아웃 */\n}$$,
$$.article {\n    columns: 3;\n    column-gap: 2em;\n}$$,
$$[{"input": "", "expected": "3 columns"}]$$,
$$["columns는 신문 스타일 레이아웃을 만듭니다"]$$,
$$["layout", "columns", "hard"]$$, 18),

($$css-aspect-ratio$$, $$css$$, $$syntax$$, 84, $$종횡비$$, $$aspect-ratio$$, $$challenge$$, 3,
$$요소의 종횡비를 16:9로 유지하세요.$$,
$$- aspect-ratio: 16 / 9\n- 비율 유지$$,
$$[{"input": "", "output": "16:9 비율"}]$$,
$$.video-container {\n    /* 16:9 비율 */\n}$$,
$$.video-container {\n    aspect-ratio: 16 / 9;\n}$$,
$$[{"input": "", "expected": "16:9 aspect ratio"}]$$,
$$["aspect-ratio는 너비에 맞춰 높이를 자동 조정합니다"]$$,
$$["layout", "aspect-ratio", "hard"]$$, 18),

($$css-object-fit$$, $$css$$, $$syntax$$, 85, $$객체 맞춤$$, $$object-fit$$, $$challenge$$, 3,
$$이미지가 컨테이너를 꽉 채우되 비율을 유지하세요.$$,
$$- object-fit: cover\n- 비율 유지하며 채우기$$,
$$[{"input": "", "output": "cover 이미지"}]$$,
$$img {\n    width: 100%;\n    height: 300px;\n    /* object-fit */\n}$$,
$$img {\n    width: 100%;\n    height: 300px;\n    object-fit: cover;\n}$$,
$$[{"input": "", "expected": "object-fit cover"}]$$,
$$["contain, cover, fill, none, scale-down 값이 있습니다"]$$,
$$["layout", "object-fit", "hard"]$$, 18);

-- Unit 18: 고급 효과 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-filter$$, $$css$$, $$syntax$$, 86, $$Filter 효과$$, $$filter 속성$$, $$challenge$$, 3,
$$이미지에 흐림 효과를 추가하세요.$$,
$$- filter: blur(5px)\n- 시각 효과$$,
$$[{"input": "", "output": "흐림 이미지"}]$$,
$$img {\n    /* 흐림 효과 */\n}$$,
$$img {\n    filter: blur(5px);\n}$$,
$$[{"input": "", "expected": "blur filter"}]$$,
$$["blur, brightness, contrast, grayscale 등 다양한 필터가 있습니다"]$$,
$$["effects", "filter", "hard"]$$, 18),

($$css-backdrop-filter$$, $$css$$, $$syntax$$, 87, $$배경 필터$$, $$backdrop-filter$$, $$challenge$$, 3,
$$배경을 흐리게 하는 유리 효과를 만드세요.$$,
$$- backdrop-filter: blur(10px)\n- 배경 효과$$,
$$[{"input": "", "output": "유리 효과"}]$$,
$$.glass {\n    /* 배경 흐림 */\n}$$,
$$.glass {\n    background: rgba(255, 255, 255, 0.5);\n    backdrop-filter: blur(10px);\n}$$,
$$[{"input": "", "expected": "backdrop blur"}]$$,
$$["backdrop-filter는 요소 뒤의 배경에 효과를 적용합니다"]$$,
$$["effects", "backdrop-filter", "hard"]$$, 20),

($$css-text-shadow$$, $$css$$, $$syntax$$, 88, $$텍스트 그림자$$, $$text-shadow$$, $$challenge$$, 3,
$$텍스트에 그림자를 추가하세요.$$,
$$- text-shadow: x y blur color\n- 텍스트 효과$$,
$$[{"input": "", "output": "그림자 텍스트"}]$$,
$$h1 {\n    /* 텍스트 그림자 */\n}$$,
$$h1 {\n    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);\n}$$,
$$[{"input": "", "expected": "text shadow"}]$$,
$$["여러 그림자를 쉼표로 구분하여 추가할 수 있습니다"]$$,
$$["effects", "text-shadow", "hard"]$$, 15),

($$css-gradient$$, $$css$$, $$syntax$$, 89, $$그라디언트$$, $$linear-gradient$$, $$challenge$$, 3,
$$선형 그라디언트 배경을 만드세요.$$,
$$- background: linear-gradient()\n- 색상 전환$$,
$$[{"input": "", "output": "그라디언트 배경"}]$$,
$$.hero {\n    /* 그라디언트 배경 */\n}$$,
$$.hero {\n    background: linear-gradient(to right, #667eea, #764ba2);\n}$$,
$$[{"input": "", "expected": "gradient bg"}]$$,
$$["linear-gradient, radial-gradient, conic-gradient가 있습니다"]$$,
$$["effects", "gradient", "hard"]$$, 18),

($$css-blend-mode$$, $$css$$, $$syntax$$, 90, $$혼합 모드$$, $$mix-blend-mode$$, $$challenge$$, 3,
$$요소를 배경과 혼합하세요.$$,
$$- mix-blend-mode: multiply\n- 레이어 혼합$$,
$$[{"input": "", "output": "혼합 효과"}]$$,
$$.overlay {\n    /* 혼합 모드 */\n}$$,
$$.overlay {\n    mix-blend-mode: multiply;\n}$$,
$$[{"input": "", "expected": "blend mode"}]$$,
$$["multiply, screen, overlay, darken, lighten 등이 있습니다"]$$,
$$["effects", "blend-mode", "hard"]$$, 20);

-- Unit 19: 변수와 함수 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-variables$$, $$css$$, $$syntax$$, 91, $$CSS 변수$$, $$커스텀 속성$$, $$challenge$$, 3,
$$CSS 변수로 메인 색상을 정의하고 사용하세요.$$,
$$- --변수명: 값\n- var(--변수명) 사용$$,
$$[{"input": "", "output": "CSS 변수"}]$$,
$$:root {\n    /* 변수 정의 */\n}\n\n.button {\n    /* 변수 사용 */\n}$$,
$func$:root {\n    --primary-color: #007bff;\n}\n\n.button {\n    background-color: var(--primary-color);\n}$func$,
$$[{"input": "", "expected": "css variables"}]$$,
$$[":root에 정의하면 전역에서 사용할 수 있습니다"]$$,
$$["advanced", "variables", "hard"]$$, 18),

($$css-var-fallback$$, $$css$$, $$syntax$$, 92, $$변수 폴백$$, $$var() 기본값$$, $$challenge$$, 3,
$$변수가 없을 때 폴백 값을 지정하세요.$$,
$$- var(--변수, 폴백값)\n- 기본값 제공$$,
$$[{"input": "", "output": "폴백 값"}]$$,
$$.element {\n    /* 폴백 포함 */\n}$$,
$$.element {\n    color: var(--text-color, black);\n}$$,
$$[{"input": "", "expected": "var with fallback"}]$$,
$$["var()의 두 번째 인자로 폴백 값을 지정합니다"]$$,
$$["advanced", "variables", "hard"]$$, 18),

($$css-min-max$$, $$css$$, $$syntax$$, 93, $$min/max 함수$$, $$최소/최대 값$$, $$challenge$$, 3,
$$너비를 최소 300px, 최대 50%로 제한하세요.$$,
$$- min(), max() 함수\n- 값 제한$$,
$$[{"input": "", "output": "min/max 제한"}]$$,
$$.container {\n    /* min/max 사용 */\n}$$,
$$.container {\n    width: min(50%, 600px);\n}$$,
$$[{"input": "", "expected": "min width"}]$$,
$$["min()은 가장 작은 값을, max()는 가장 큰 값을 선택합니다"]$$,
$$["advanced", "functions", "hard"]$$, 20),

($$css-attr$$, $$css$$, $$syntax$$, 94, $$attr() 함수$$, $$속성 값 사용$$, $$challenge$$, 3,
$$data 속성의 값을 content로 표시하세요.$$,
$$- attr() 함수\n- HTML 속성 접근$$,
$$[{"input": "", "output": "속성 값 표시"}]$$,
$$a::after {\n    /* data-label 표시 */\n}$$,
$$a::after {\n    content: " (" attr(data-label) ")";\n}$$,
$$[{"input": "", "expected": "attr content"}]$$,
$$["attr()로 HTML 속성 값을 CSS에서 사용할 수 있습니다"]$$,
$$["advanced", "functions", "hard"]$$, 20),

($$css-counter$$, $$css$$, $$syntax$$, 95, $$CSS 카운터$$, $$counter() 함수$$, $$challenge$$, 3,
$$섹션 번호를 자동으로 매기세요.$$,
$$- counter-reset\n- counter-increment\n- counter()$$,
$$[{"input": "", "output": "자동 번호"}]$$,
$$body {\n    /* 카운터 리셋 */\n}\n\nsection::before {\n    /* 카운터 사용 */\n}$$,
$func$body {\n    counter-reset: section;\n}\n\nsection {\n    counter-increment: section;\n}\n\nsection::before {\n    content: "Section " counter(section) ": ";\n}$func$,
$$[{"input": "", "expected": "counter numbering"}]$$,
$$["CSS 카운터로 자동 번호 매기기를 구현할 수 있습니다"]$$,
$$["advanced", "counter", "hard"]$$, 25);

-- Unit 20: 최신 CSS (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$css-subgrid$$, $$css$$, $$syntax$$, 96, $$Subgrid$$, $$중첩 그리드 정렬$$, $$challenge$$, 3,
$$자식 그리드가 부모 그리드 라인을 따르게 하세요.$$,
$$- grid-template-columns: subgrid\n- 부모 그리드 상속$$,
$$[{"input": "", "output": "subgrid"}]$$,
$$.child {\n    display: grid;\n    /* subgrid 사용 */\n}$$,
$$.child {\n    display: grid;\n    grid-template-columns: subgrid;\n}$$,
$$[{"input": "", "expected": "subgrid layout"}]$$,
$$["subgrid는 자식이 부모의 그리드 트랙을 상속합니다"]$$,
$$["modern", "grid", "subgrid", "hard"]$$, 25),

($$css-is-where$$, $$css$$, $$syntax$$, 97, $$:is()와 :where()$$, $$선택자 목록$$, $$challenge$$, 3,
$$:is()로 여러 선택자를 간결하게 작성하세요.$$,
$$- :is() 가상 클래스\n- 선택자 그룹화$$,
$$[{"input": "", "output": "is selector"}]$$,
$$/* h1, h2, h3의 a를 선택 */\n$$,
$$:is(h1, h2, h3) a {\n    color: blue;\n}$$,
$$[{"input": "", "expected": "is selector"}]$$,
$$[":is()는 명시도를 가지지만 :where()는 명시도가 0입니다"]$$,
$$["modern", "selector", "is", "hard"]$$, 20),

($$css-has$$, $$css$$, $$syntax$$, 98, $$:has() 선택자$$, $$부모 선택자$$, $$challenge$$, 3,
$$이미지가 있는 article을 선택하세요.$$,
$$- :has() 가상 클래스\n- 자식 기준 부모 선택$$,
$$[{"input": "", "output": "has selector"}]$$,
$$/* 이미지가 있는 article */\n$$,
$$article:has(img) {\n    border: 2px solid blue;\n}$$,
$$[{"input": "", "expected": "has img selector"}]$$,
$$[":has()는 부모 선택자로, 특정 자식을 가진 요소를 선택합니다"]$$,
$$["modern", "selector", "has", "hard"]$$, 25),

($$css-scroll-snap$$, $$css$$, $$syntax$$, 99, $$Scroll Snap$$, $$스크롤 스냅$$, $$challenge$$, 3,
$$스크롤 시 섹션에 스냅되게 하세요.$$,
$$- scroll-snap-type\n- scroll-snap-align$$,
$$[{"input": "", "output": "scroll snap"}]$$,
$$.container {\n    /* scroll snap container */\n}\n\n.section {\n    /* snap point */\n}$$,
$func$.container {\n    scroll-snap-type: y mandatory;\n    overflow-y: scroll;\n}\n\n.section {\n    scroll-snap-align: start;\n}$func$,
$$[{"input": "", "expected": "scroll snap"}]$$,
$$["scroll-snap은 풀 페이지 스크롤이나 캐러셀에 유용합니다"]$$,
$$["modern", "scroll", "hard"]$$, 25),

($$css-layer$$, $$css$$, $$syntax$$, 100, $$@layer$$, $$레이어 순서$$, $$challenge$$, 3,
$$CSS 레이어로 명시도를 관리하세요.$$,
$$- @layer 규칙\n- 레이어 순서 정의$$,
$$[{"input": "", "output": "cascade layers"}]$$,
$$/* 레이어 정의 */\n$$,
$func$@layer reset, base, components;\n\n@layer reset {\n    * { margin: 0; }\n}\n\n@layer base {\n    body { font-family: sans-serif; }\n}$func$,
$$[{"input": "", "expected": "layer defined"}]$$,
$$["@layer는 명시도 대신 순서로 우선순위를 관리합니다"]$$,
$$["modern", "layer", "hard"]$$, 25);

-- ====================================
-- 완료 메시지
-- ====================================

