-- ============================================================================
-- HTML Language Challenges (Complete)
-- ============================================================================
-- Generated: 2025-11-01T14:07:10.157Z
-- ============================================================================

-- ====================================
-- HTML Language Challenges - Part 1
-- Levels 1-50 (EASY 50개)
-- ====================================

-- Unit 1: 기본 구조 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-basic-structure$$, $$html$$, $$syntax$$, 1, $$기본 HTML 문서$$, $$첫 HTML 문서 작성하기$$, $$challenge$$, 1,
$$가장 기본적인 HTML 문서 구조를 작성하세요.$$,
$$- <!DOCTYPE html> 선언\n- html, head, body 태그 사용$$,
$$[{"input": "", "output": "기본 HTML 구조"}]$$,
$$<!-- HTML 기본 구조를 작성하세요 -->\n$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <title>My First Page</title>\n</head>\n<body>\n    <h1>Hello, World!</h1>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "valid html structure"}]$$,
$$["DOCTYPE은 HTML5를 의미합니다", "html 태그가 모든 것을 감싸야 합니다"]$$,
$$["basics", "structure"]$$, 5),

($$html-title-tag$$, $$html$$, $$syntax$$, 2, $$페이지 제목$$, $$title 태그 사용$$, $$challenge$$, 1,
$$페이지 제목을 "My Website"로 설정하세요.$$,
$$- <title> 태그는 head 안에\n- 브라우저 탭에 표시되는 제목$$,
$$[{"input": "", "output": "페이지 제목 설정"}]$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <!-- 여기에 title 태그를 추가하세요 -->\n</head>\n<body>\n</body>\n</html>$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Website</title>\n</head>\n<body>\n</body>\n</html>$$,
$$[{"input": "", "expected": "title is My Website"}]$$,
$$["title 태그는 head 섹션에 위치합니다"]$$,
$$["basics", "title"]$$, 5),

($$html-meta-charset$$, $$html$$, $$syntax$$, 3, $$문자 인코딩$$, $$meta charset 설정$$, $$challenge$$, 1,
$$UTF-8 문자 인코딩을 설정하세요.$$,
$$- <meta charset="UTF-8">\n- head 태그 안에 위치$$,
$$[{"input": "", "output": "UTF-8 인코딩 설정"}]$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <!-- 여기에 meta charset을 추가하세요 -->\n</head>\n<body>\n</body>\n</html>$func$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <meta charset="UTF-8">\n</head>\n<body>\n</body>\n</html>$$,
$$[{"input": "", "expected": "charset utf-8"}]$$,
$$["meta 태그는 self-closing입니다"]$$,
$$["basics", "meta"]$$, 5),

($$html-viewport$$, $$html$$, $$syntax$$, 4, $$뷰포트 설정$$, $$반응형 메타 태그$$, $$challenge$$, 1,
$$반응형 웹을 위한 viewport 메타 태그를 추가하세요.$$,
$$- name="viewport"\n- content="width=device-width, initial-scale=1.0"$$,
$$[{"input": "", "output": "viewport 설정"}]$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <meta charset="UTF-8">\n    <!-- viewport meta 태그를 추가하세요 -->\n</head>\n<body>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n</head>\n<body>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "responsive viewport"}]$$,
$$["viewport는 모바일 반응형에 필수입니다"]$$,
$$["basics", "viewport", "responsive"]$$, 5),

($$html-comment$$, $$html$$, $$syntax$$, 5, $$HTML 주석$$, $$주석 작성하기$$, $$challenge$$, 1,
$$"This is a comment"라는 주석을 추가하세요.$$,
$$- <!-- 주석 내용 -->\n- 브라우저에 표시되지 않음$$,
$$[{"input": "", "output": "주석 추가"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- 여기에 주석을 작성하세요 -->\n</body>\n</html>$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- This is a comment -->\n</body>\n</html>$$,
$$[{"input": "", "expected": "comment exists"}]$$,
$$["주석은 <!-- 로 시작하고 -->로 끝납니다"]$$,
$$["basics", "comment"]$$, 3);

-- Unit 2: 텍스트 태그 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-heading-h1$$, $$html$$, $$syntax$$, 6, $$제목 태그$$, $$h1 태그 사용$$, $$challenge$$, 1,
$$"Welcome"이라는 h1 제목을 만드세요.$$,
$$- <h1> 태그 사용\n- 가장 중요한 제목$$,
$$[{"input": "", "output": "h1 제목"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- h1 태그로 Welcome을 작성하세요 -->\n</body>\n</html>$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <h1>Welcome</h1>\n</body>\n</html>$$,
$$[{"input": "", "expected": "h1 with Welcome"}]$$,
$$["h1은 한 페이지에 하나만 사용하는 것이 좋습니다"]$$,
$$["text", "heading"]$$, 5),

($$html-multiple-headings$$, $$html$$, $$syntax$$, 7, $$여러 제목 레벨$$, $$h1~h6 계층$$, $$challenge$$, 1,
$$h1부터 h3까지 제목을 만드세요.$$,
$$- h1: "Main Title"\n- h2: "Subtitle"\n- h3: "Section"$$,
$$[{"input": "", "output": "제목 계층 구조"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- h1, h2, h3를 순서대로 작성하세요 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <h1>Main Title</h1>\n    <h2>Subtitle</h2>\n    <h3>Section</h3>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "h1 h2 h3 hierarchy"}]$$,
$$["제목은 h1부터 h6까지 있으며, 숫자가 클수록 작습니다"]$$,
$$["text", "heading"]$$, 5),

($$html-paragraph$$, $$html$$, $$syntax$$, 8, $$문단 태그$$, $$p 태그 사용$$, $$challenge$$, 1,
$$"This is a paragraph."라는 문단을 만드세요.$$,
$$- <p> 태그 사용\n- 텍스트 블록 표현$$,
$$[{"input": "", "output": "p 태그로 문단"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- p 태그로 문단을 작성하세요 -->\n</body>\n</html>$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <p>This is a paragraph.</p>\n</body>\n</html>$$,
$$[{"input": "", "expected": "paragraph element"}]$$,
$$["p 태그는 자동으로 위아래 여백을 만듭니다"]$$,
$$["text", "paragraph"]$$, 5),

($$html-line-break$$, $$html$$, $$syntax$$, 9, $$줄바꿈$$, $$br 태그$$, $$challenge$$, 1,
$$두 줄의 텍스트를 br 태그로 구분하세요.$$,
$$- <br> 태그 사용\n- self-closing 태그$$,
$$[{"input": "", "output": "줄바꿈"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <p>\n        First line\n        <!-- br 태그를 추가하세요 -->\n        Second line\n    </p>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <p>\n        First line<br>\n        Second line\n    </p>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "line break"}]$$,
$$["br 태그는 닫는 태그가 없습니다"]$$,
$$["text", "line-break"]$$, 5),

($$html-horizontal-rule$$, $$html$$, $$syntax$$, 10, $$수평선$$, $$hr 태그$$, $$challenge$$, 1,
$$두 문단 사이에 수평선을 추가하세요.$$,
$$- <hr> 태그 사용\n- 콘텐츠 구분선$$,
$$[{"input": "", "output": "수평선"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <p>Above the line</p>\n    <!-- hr 태그를 추가하세요 -->\n    <p>Below the line</p>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <p>Above the line</p>\n    <hr>\n    <p>Below the line</p>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "horizontal rule"}]$$,
$$["hr은 테마적 구분을 나타냅니다"]$$,
$$["text", "hr"]$$, 5);

-- Unit 3: 텍스트 서식 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-bold$$, $$html$$, $$syntax$$, 11, $$굵은 텍스트$$, $$strong 태그$$, $$challenge$$, 1,
$$"Important"를 굵게 표시하세요.$$,
$$- <strong> 태그 사용\n- 의미적으로 중요한 텍스트$$,
$$[{"input": "", "output": "굵은 텍스트"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <p>This is <strong>important</strong>.</p>\n</body>\n</html>$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <p>This is <strong>Important</strong>.</p>\n</body>\n</html>$$,
$$[{"input": "", "expected": "strong tag"}]$$,
$$["strong은 의미적 중요도를, b는 단순 스타일입니다"]$$,
$$["text", "formatting", "strong"]$$, 5),

($$html-italic$$, $$html$$, $$syntax$$, 12, $$이탤릭 텍스트$$, $$em 태그$$, $$challenge$$, 1,
$$"emphasized"를 이탤릭으로 표시하세요.$$,
$$- <em> 태그 사용\n- 강조 의미$$,
$$[{"input": "", "output": "이탤릭 텍스트"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <p>This is <!-- em 태그로 감싸세요 -->emphasized.</p>\n</body>\n</html>$func$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <p>This is <em>emphasized</em>.</p>\n</body>\n</html>$$,
$$[{"input": "", "expected": "em tag"}]$$,
$$["em은 강조를, i는 단순 스타일입니다"]$$,
$$["text", "formatting", "em"]$$, 5),

($$html-mark$$, $$html$$, $$syntax$$, 13, $$하이라이트$$, $$mark 태그$$, $$challenge$$, 1,
$$"highlighted"를 하이라이트 표시하세요.$$,
$$- <mark> 태그 사용\n- 배경색이 있는 강조$$,
$$[{"input": "", "output": "하이라이트"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <p>This is <!-- mark 태그 -->highlighted text.</p>\n</body>\n</html>$func$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <p>This is <mark>highlighted</mark> text.</p>\n</body>\n</html>$$,
$$[{"input": "", "expected": "mark tag"}]$$,
$$["mark는 주로 노란 배경색으로 표시됩니다"]$$,
$$["text", "formatting", "mark"]$$, 5),

($$html-small$$, $$html$$, $$syntax$$, 14, $$작은 텍스트$$, $$small 태그$$, $$challenge$$, 1,
$$부가 정보를 small 태그로 표시하세요.$$,
$$- <small> 태그 사용\n- 더 작은 글씨$$,
$$[{"input": "", "output": "작은 텍스트"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <p>Regular text <small>small print</small></p>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <p>Regular text <small>small print</small></p>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "small tag"}]$$,
$$["small은 법적 고지나 저작권 표시에 자주 사용됩니다"]$$,
$$["text", "formatting", "small"]$$, 5),

($$html-del-ins$$, $$html$$, $$syntax$$, 15, $$삭제/삽입$$, $$del과 ins 태그$$, $$challenge$$, 1,
$$삭제된 텍스트와 삽입된 텍스트를 표시하세요.$$,
$$- <del> 삭제선\n- <ins> 밑줄$$,
$$[{"input": "", "output": "del, ins 태그"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <p>Price: <del>$100</del> <ins>$80</ins></p>\n</body>\n</html>$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <p>Price: <del>$100</del> <ins>$80</ins></p>\n</body>\n</html>$$,
$$[{"input": "", "expected": "del and ins tags"}]$$,
$$["del은 삭제선, ins는 밑줄로 표시됩니다"]$$,
$$["text", "formatting", "del", "ins"]$$, 5);

-- Unit 4: 링크와 이미지 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-link-basic$$, $$html$$, $$syntax$$, 16, $$기본 링크$$, $$a 태그 사용$$, $$challenge$$, 1,
$$"Visit Google"이라는 텍스트로 구글 링크를 만드세요.$$,
$$- <a> 태그 사용\n- href 속성에 URL$$,
$$[{"input": "", "output": "하이퍼링크"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- 구글 링크를 만드세요 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <a href="https://www.google.com">Visit Google</a>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "link to google"}]$$,
$$["href는 hypertext reference의 약자입니다"]$$,
$$["link", "anchor"]$$, 5),

($$html-link-target$$, $$html$$, $$syntax$$, 17, $$새 탭에서 열기$$, $$target 속성$$, $$challenge$$, 1,
$$링크를 새 탭에서 열리도록 설정하세요.$$,
$$- target="_blank"\n- 새 창/탭에서 열림$$,
$$[{"input": "", "output": "새 탭 링크"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <a href="https://example.com">Example</a>\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <a href="https://example.com" target="_blank">Example</a>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "target blank"}]$$,
$$["_blank는 새 브라우징 컨텍스트를 의미합니다"]$$,
$$["link", "target"]$$, 5),

($$html-image-basic$$, $$html$$, $$syntax$$, 18, $$이미지 삽입$$, $$img 태그$$, $$challenge$$, 1,
$$이미지를 삽입하세요.$$,
$$- <img> 태그 사용\n- src와 alt 속성 필수$$,
$$[{"input": "", "output": "이미지"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- 이미지를 삽입하세요 -->\n</body>\n</html>$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <img src="image.jpg" alt="Description">\n</body>\n</html>$$,
$$[{"input": "", "expected": "img tag"}]$$,
$$["alt는 접근성을 위해 필수입니다"]$$,
$$["image", "img"]$$, 5),

($$html-image-size$$, $$html$$, $$syntax$$, 19, $$이미지 크기$$, $$width와 height$$, $$challenge$$, 1,
$$이미지 크기를 300x200으로 설정하세요.$$,
$$- width와 height 속성\n- 픽셀 단위$$,
$$[{"input": "", "output": "크기 지정 이미지"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <img src="photo.jpg" alt="Photo">\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <img src="photo.jpg" alt="Photo" width="300" height="200">\n</body>\n</html>$func$,
$$[{"input": "", "expected": "300x200 image"}]$$,
$$["width와 height로 레이아웃 시프트를 방지할 수 있습니다"]$$,
$$["image", "size"]$$, 5),

($$html-link-image$$, $$html$$, $$syntax$$, 20, $$이미지 링크$$, $$이미지를 클릭 가능하게$$, $$challenge$$, 1,
$$이미지를 클릭하면 링크로 이동하게 만드세요.$$,
$$- a 태그 안에 img 태그\n- 이미지가 링크 역할$$,
$$[{"input": "", "output": "클릭 가능한 이미지"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <img src="logo.png" alt="Logo">\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <a href="https://example.com">\n        <img src="logo.png" alt="Logo">\n    </a>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "clickable image"}]$$,
$$["a 태그로 img를 감싸면 이미지가 링크가 됩니다"]$$,
$$["link", "image"]$$, 8);

-- Unit 5: 리스트 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-ul-list$$, $$html$$, $$syntax$$, 21, $$순서 없는 목록$$, $$ul과 li$$, $$challenge$$, 1,
$$3개 항목의 순서 없는 목록을 만드세요.$$,
$$- <ul> 태그 사용\n- <li> 항목들$$,
$$[{"input": "", "output": "불릿 목록"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- ul 목록을 만드세요 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <ul>\n        <li>Item 1</li>\n        <li>Item 2</li>\n        <li>Item 3</li>\n    </ul>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "ul with 3 li"}]$$,
$$["ul은 unordered list의 약자입니다"]$$,
$$["list", "ul"]$$, 5),

($$html-ol-list$$, $$html$$, $$syntax$$, 22, $$순서 있는 목록$$, $$ol과 li$$, $$challenge$$, 1,
$$3개 항목의 순서 있는 목록을 만드세요.$$,
$$- <ol> 태그 사용\n- 자동으로 번호 매김$$,
$$[{"input": "", "output": "번호 목록"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- ol 목록을 만드세요 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <ol>\n        <li>First</li>\n        <li>Second</li>\n        <li>Third</li>\n    </ol>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "ol with 3 li"}]$$,
$$["ol은 ordered list의 약자입니다"]$$,
$$["list", "ol"]$$, 5),

($$html-nested-list$$, $$html$$, $$syntax$$, 23, $$중첩 목록$$, $$목록 안의 목록$$, $$challenge$$, 1,
$$목록 항목 안에 다른 목록을 넣으세요.$$,
$$- li 안에 ul 또는 ol\n- 계층 구조 표현$$,
$$[{"input": "", "output": "중첩 목록"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <ul>\n        <li>Main item\n            <!-- 여기에 중첩 목록 추가 -->\n        </li>\n    </ul>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <ul>\n        <li>Main item\n            <ul>\n                <li>Sub item 1</li>\n                <li>Sub item 2</li>\n            </ul>\n        </li>\n    </ul>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "nested list"}]$$,
$$["중첩 목록은 li 태그 안에 새로운 ul/ol을 넣습니다"]$$,
$$["list", "nested"]$$, 8),

($$html-dl-list$$, $$html$$, $$syntax$$, 24, $$정의 목록$$, $$dl, dt, dd$$, $$challenge$$, 1,
$$용어와 설명으로 구성된 정의 목록을 만드세요.$$,
$$- <dl> 정의 목록\n- <dt> 용어, <dd> 설명$$,
$$[{"input": "", "output": "정의 목록"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- 정의 목록을 만드세요 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <dl>\n        <dt>HTML</dt>\n        <dd>Hypertext Markup Language</dd>\n        <dt>CSS</dt>\n        <dd>Cascading Style Sheets</dd>\n    </dl>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "definition list"}]$$,
$$["dl은 definition list, dt는 term, dd는 description입니다"]$$,
$$["list", "dl"]$$, 8),

($$html-ol-start$$, $$html$$, $$syntax$$, 25, $$목록 시작 번호$$, $$start 속성$$, $$challenge$$, 1,
$$5번부터 시작하는 순서 목록을 만드세요.$$,
$$- <ol start="5">\n- 시작 번호 지정$$,
$$[{"input": "", "output": "5번부터 시작"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <ol>\n        <li>Item</li>\n        <li>Item</li>\n    </ol>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <ol start="5">\n        <li>Item</li>\n        <li>Item</li>\n    </ol>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "ol starting at 5"}]$$,
$$["start 속성으로 시작 번호를 변경할 수 있습니다"]$$,
$$["list", "ol", "start"]$$, 5);

-- Unit 6: 테이블 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-table-basic$$, $$html$$, $$syntax$$, 26, $$기본 테이블$$, $$table, tr, td$$, $$challenge$$, 1,
$$2x2 테이블을 만드세요.$$,
$$- <table> 태그\n- <tr> 행, <td> 셀$$,
$$[{"input": "", "output": "간단한 테이블"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- 2x2 테이블을 만드세요 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr>\n            <td>Cell 1</td>\n            <td>Cell 2</td>\n        </tr>\n        <tr>\n            <td>Cell 3</td>\n            <td>Cell 4</td>\n        </tr>\n    </table>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "2x2 table"}]$$,
$$["tr은 table row, td는 table data입니다"]$$,
$$["table", "basics"]$$, 8),

($$html-table-header$$, $$html$$, $$syntax$$, 27, $$테이블 헤더$$, $$th 태그$$, $$challenge$$, 1,
$$헤더가 있는 테이블을 만드세요.$$,
$$- <th> 태그 사용\n- 첫 행을 헤더로$$,
$$[{"input": "", "output": "헤더 테이블"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr>\n            <!-- th 태그로 헤더 만들기 -->\n        </tr>\n    </table>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr>\n            <th>Name</th>\n            <th>Age</th>\n        </tr>\n        <tr>\n            <td>John</td>\n            <td>30</td>\n        </tr>\n    </table>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "table with th"}]$$,
$$["th는 table header로 기본적으로 굵게 표시됩니다"]$$,
$$["table", "th"]$$, 8),

($$html-table-border$$, $$html$$, $$syntax$$, 28, $$테이블 테두리$$, $$border 속성$$, $$challenge$$, 1,
$$테두리가 있는 테이블을 만드세요.$$,
$$- border="1"\n- CSS 없이 간단한 테두리$$,
$$[{"input": "", "output": "테두리 테이블"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr><td>A</td><td>B</td></tr>\n    </table>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table border="1">\n        <tr><td>A</td><td>B</td></tr>\n    </table>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "table with border"}]$$,
$$["border 속성은 HTML5에서는 CSS를 사용하는 것이 권장됩니다"]$$,
$$["table", "border"]$$, 5),

($$html-table-colspan$$, $$html$$, $$syntax$$, 29, $$셀 병합 (가로)$$, $$colspan 속성$$, $$challenge$$, 1,
$$2개 열을 병합한 셀을 만드세요.$$,
$$- colspan="2"\n- 가로로 셀 병합$$,
$$[{"input": "", "output": "colspan 테이블"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table border="1">\n        <tr>\n            <td>Merged Cell</td>\n        </tr>\n        <tr>\n            <td>A</td><td>B</td>\n        </tr>\n    </table>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table border="1">\n        <tr>\n            <td colspan="2">Merged Cell</td>\n        </tr>\n        <tr>\n            <td>A</td><td>B</td>\n        </tr>\n    </table>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "colspan 2"}]$$,
$$["colspan은 column span으로 열을 병합합니다"]$$,
$$["table", "colspan"]$$, 8),

($$html-table-rowspan$$, $$html$$, $$syntax$$, 30, $$셀 병합 (세로)$$, $$rowspan 속성$$, $$challenge$$, 1,
$$2개 행을 병합한 셀을 만드세요.$$,
$$- rowspan="2"\n- 세로로 셀 병합$$,
$$[{"input": "", "output": "rowspan 테이블"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table border="1">\n        <tr>\n            <td>A</td><td>B</td>\n        </tr>\n        <tr>\n            <td>C</td><td>D</td>\n        </tr>\n    </table>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table border="1">\n        <tr>\n            <td rowspan="2">A</td>\n            <td>B</td>\n        </tr>\n        <tr>\n            <td>D</td>\n        </tr>\n    </table>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "rowspan 2"}]$$,
$$["rowspan은 row span으로 행을 병합합니다"]$$,
$$["table", "rowspan"]$$, 8);

-- Unit 7: 폼 기본 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-form-basic$$, $$html$$, $$syntax$$, 31, $$기본 폼$$, $$form 태그$$, $$challenge$$, 1,
$$기본 폼을 만드세요.$$,
$$- <form> 태그\n- action과 method 속성$$,
$$[{"input": "", "output": "폼 구조"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- form을 만드세요 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form action="/submit" method="post">\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "form with action and method"}]$$,
$$["action은 데이터를 보낼 URL, method는 HTTP 메서드입니다"]$$,
$$["form", "basics"]$$, 5),

($$html-input-text$$, $$html$$, $$syntax$$, 32, $$텍스트 입력$$, $$input type=text$$, $$challenge$$, 1,
$$이름을 입력받는 텍스트 필드를 만드세요.$$,
$$- <input type="text">\n- name과 placeholder 속성$$,
$$[{"input": "", "output": "텍스트 입력 필드"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <!-- input 필드 추가 -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="text" name="username" placeholder="Enter name">\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "text input"}]$$,
$$["placeholder는 힌트 텍스트입니다"]$$,
$$["form", "input", "text"]$$, 5),

($$html-label$$, $$html$$, $$syntax$$, 33, $$라벨$$, $$label 태그$$, $$challenge$$, 1,
$$입력 필드에 라벨을 연결하세요.$$,
$$- <label> 태그\n- for 속성과 input id 연결$$,
$$[{"input": "", "output": "라벨과 입력"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="text" id="email">\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label for="email">Email:</label>\n        <input type="text" id="email" name="email">\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "label with for"}]$$,
$$["label의 for와 input의 id를 같게 하면 연결됩니다"]$$,
$$["form", "label"]$$, 8),

($$html-input-password$$, $$html$$, $$syntax$$, 34, $$비밀번호 입력$$, $$input type=password$$, $$challenge$$, 1,
$$비밀번호 입력 필드를 만드세요.$$,
$$- type="password"\n- 입력 내용 숨김 표시$$,
$$[{"input": "", "output": "비밀번호 필드"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label for="pwd">Password:</label>\n        <!-- password input 추가 -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label for="pwd">Password:</label>\n        <input type="password" id="pwd" name="password">\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "password input"}]$$,
$$["password 타입은 입력 값을 점으로 표시합니다"]$$,
$$["form", "input", "password"]$$, 5),

($$html-submit-button$$, $$html$$, $$syntax$$, 35, $$제출 버튼$$, $$input type=submit$$, $$challenge$$, 1,
$$폼 제출 버튼을 만드세요.$$,
$$- type="submit"\n- value로 버튼 텍스트$$,
$$[{"input": "", "output": "제출 버튼"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="text" name="name">\n        <!-- submit 버튼 추가 -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="text" name="name">\n        <input type="submit" value="Submit">\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "submit button"}]$$,
$$["submit 버튼을 클릭하면 폼이 제출됩니다"]$$,
$$["form", "button", "submit"]$$, 5);

-- Unit 8: 폼 입력 타입 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-input-email$$, $$html$$, $$syntax$$, 36, $$이메일 입력$$, $$input type=email$$, $$challenge$$, 1,
$$이메일 입력 필드를 만드세요.$$,
$$- type="email"\n- 자동 유효성 검사$$,
$$[{"input": "", "output": "이메일 필드"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Email:</label>\n        <!-- email input -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Email:</label>\n        <input type="email" name="email" required>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "email input"}]$$,
$$["email 타입은 @ 포함 여부를 자동 검증합니다"]$$,
$$["form", "input", "email"]$$, 5),

($$html-input-number$$, $$html$$, $$syntax$$, 37, $$숫자 입력$$, $$input type=number$$, $$challenge$$, 1,
$$나이를 입력받는 숫자 필드를 만드세요 (1-100).$$,
$$- type="number"\n- min, max 속성$$,
$$[{"input": "", "output": "숫자 필드"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Age:</label>\n        <!-- number input with range -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Age:</label>\n        <input type="number" name="age" min="1" max="100">\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "number input 1-100"}]$$,
$$["min과 max로 범위를 제한할 수 있습니다"]$$,
$$["form", "input", "number"]$$, 5),

($$html-input-date$$, $$html$$, $$syntax$$, 38, $$날짜 입력$$, $$input type=date$$, $$challenge$$, 1,
$$날짜 선택 필드를 만드세요.$$,
$$- type="date"\n- 달력 UI 제공$$,
$$[{"input": "", "output": "날짜 필드"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Birth Date:</label>\n        <!-- date input -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Birth Date:</label>\n        <input type="date" name="birthdate">\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "date input"}]$$,
$$["date 타입은 브라우저가 달력을 제공합니다"]$$,
$$["form", "input", "date"]$$, 5),

($$html-input-checkbox$$, $$html$$, $$syntax$$, 39, $$체크박스$$, $$input type=checkbox$$, $$challenge$$, 1,
$$약관 동의 체크박스를 만드세요.$$,
$$- type="checkbox"\n- checked 속성으로 기본 선택$$,
$$[{"input": "", "output": "체크박스"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Agree</label>\n        <!-- checkbox input -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="checkbox" id="agree" name="agree">\n        <label for="agree">I agree to terms</label>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "checkbox"}]$$,
$$["체크박스는 on/off 선택에 사용됩니다"]$$,
$$["form", "input", "checkbox"]$$, 5),

($$html-input-radio$$, $$html$$, $$syntax$$, 40, $$라디오 버튼$$, $$input type=radio$$, $$challenge$$, 1,
$$성별 선택 라디오 버튼을 만드세요.$$,
$$- type="radio"\n- 같은 name으로 그룹화$$,
$$[{"input": "", "output": "라디오 버튼"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <!-- radio buttons for gender -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="radio" id="male" name="gender" value="male">\n        <label for="male">Male</label>\n        <input type="radio" id="female" name="gender" value="female">\n        <label for="female">Female</label>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "radio buttons"}]$$,
$$["같은 name을 가진 라디오는 하나만 선택됩니다"]$$,
$$["form", "input", "radio"]$$, 8);

-- Unit 9: 폼 요소 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-textarea$$, $$html$$, $$syntax$$, 41, $$텍스트 영역$$, $$textarea 태그$$, $$challenge$$, 1,
$$여러 줄 텍스트 입력 영역을 만드세요.$$,
$$- <textarea> 태그\n- rows와 cols 속성$$,
$$[{"input": "", "output": "텍스트 영역"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Comments:</label>\n        <!-- textarea -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Comments:</label>\n        <textarea name="comments" rows="4" cols="50"></textarea>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "textarea"}]$$,
$$["textarea는 여러 줄 입력에 사용됩니다"]$$,
$$["form", "textarea"]$$, 5),

($$html-select$$, $$html$$, $$syntax$$, 42, $$드롭다운$$, $$select와 option$$, $$challenge$$, 1,
$$국가 선택 드롭다운을 만드세요.$$,
$$- <select> 태그\n- <option> 선택지들$$,
$$[{"input": "", "output": "드롭다운"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Country:</label>\n        <!-- select with options -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Country:</label>\n        <select name="country">\n            <option value="kr">Korea</option>\n            <option value="us">USA</option>\n            <option value="jp">Japan</option>\n        </select>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "select with options"}]$$,
$$["option의 value는 서버로 전송되는 값입니다"]$$,
$$["form", "select"]$$, 8),

($$html-select-selected$$, $$html$$, $$syntax$$, 43, $$기본 선택값$$, $$selected 속성$$, $$challenge$$, 1,
$$드롭다운의 기본 선택값을 설정하세요.$$,
$$- selected 속성\n- option에 추가$$,
$$[{"input": "", "output": "기본값 있는 드롭다운"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <select>\n        <option value="1">Option 1</option>\n        <option value="2">Option 2</option>\n    </select>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <select>\n        <option value="1">Option 1</option>\n        <option value="2" selected>Option 2</option>\n    </select>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "option 2 selected"}]$$,
$$["selected 속성으로 기본 선택을 지정합니다"]$$,
$$["form", "select", "selected"]$$, 5),

($$html-button$$, $$html$$, $$syntax$$, 44, $$button 태그$$, $$버튼 만들기$$, $$challenge$$, 1,
$$클릭 가능한 버튼을 만드세요.$$,
$$- <button> 태그\n- type 속성 (button, submit, reset)$$,
$$[{"input": "", "output": "버튼"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <!-- button 태그 -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <button type="button">Click Me</button>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "button element"}]$$,
$$["button 태그는 input type=button보다 스타일링이 쉽습니다"]$$,
$$["form", "button"]$$, 5),

($$html-fieldset$$, $$html$$, $$syntax$$, 45, $$필드셋$$, $$fieldset과 legend$$, $$challenge$$, 1,
$$폼 요소를 그룹화하세요.$$,
$$- <fieldset> 태그로 그룹화\n- <legend> 제목$$,
$$[{"input": "", "output": "그룹화된 폼"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <!-- fieldset으로 그룹화 -->\n        <input type="text" name="name">\n        <input type="email" name="email">\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <fieldset>\n            <legend>Personal Info</legend>\n            <input type="text" name="name">\n            <input type="email" name="email">\n        </fieldset>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "fieldset with legend"}]$$,
$$["fieldset은 관련 폼 요소를 시각적으로 그룹화합니다"]$$,
$$["form", "fieldset"]$$, 8);

-- Unit 10: 시맨틱 태그 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-header$$, $$html$$, $$syntax$$, 46, $$header 태그$$, $$페이지 헤더$$, $$challenge$$, 1,
$$페이지 상단 헤더를 만드세요.$$,
$$- <header> 태그\n- 로고, 네비게이션 등 포함$$,
$$[{"input": "", "output": "시맨틱 헤더"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- header 태그 추가 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <header>\n        <h1>My Website</h1>\n        <nav>Navigation</nav>\n    </header>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "header element"}]$$,
$$["header는 소개 콘텐츠나 네비게이션을 담습니다"]$$,
$$["semantic", "header"]$$, 5),

($$html-nav$$, $$html$$, $$syntax$$, 47, $$nav 태그$$, $$네비게이션$$, $$challenge$$, 1,
$$네비게이션 메뉴를 만드세요.$$,
$$- <nav> 태그\n- 주요 링크 모음$$,
$$[{"input": "", "output": "네비게이션"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- nav 태그로 메뉴 만들기 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <nav>\n        <a href="#home">Home</a>\n        <a href="#about">About</a>\n        <a href="#contact">Contact</a>\n    </nav>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "nav with links"}]$$,
$$["nav는 주요 네비게이션 링크 블록을 나타냅니다"]$$,
$$["semantic", "nav"]$$, 5),

($$html-main$$, $$html$$, $$syntax$$, 48, $$main 태그$$, $$주요 콘텐츠$$, $$challenge$$, 1,
$$페이지의 주요 콘텐츠 영역을 만드세요.$$,
$$- <main> 태그\n- 페이지당 하나만$$,
$$[{"input": "", "output": "main 콘텐츠"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <header>Header</header>\n    <!-- main 태그 추가 -->\n    <footer>Footer</footer>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <header>Header</header>\n    <main>\n        <h1>Main Content</h1>\n        <p>This is the primary content.</p>\n    </main>\n    <footer>Footer</footer>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "main element"}]$$,
$$["main은 문서의 주요 콘텐츠를 나타냅니다"]$$,
$$["semantic", "main"]$$, 5),

($$html-footer$$, $$html$$, $$syntax$$, 49, $$footer 태그$$, $$페이지 하단$$, $$challenge$$, 1,
$$페이지 하단 푸터를 만드세요.$$,
$$- <footer> 태그\n- 저작권, 연락처 등$$,
$$[{"input": "", "output": "푸터"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <main>Content</main>\n    <!-- footer 태그 추가 -->\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <main>Content</main>\n    <footer>\n        <p>&copy; 2024 My Website</p>\n    </footer>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "footer element"}]$$,
$$["footer는 문서나 섹션의 하단 정보를 담습니다"]$$,
$$["semantic", "footer"]$$, 5),

($$html-article-section$$, $$html$$, $$syntax$$, 50, $$article과 section$$, $$콘텐츠 구조화$$, $$challenge$$, 1,
$$article과 section을 사용하여 콘텐츠를 구조화하세요.$$,
$$- <article> 독립적인 콘텐츠\n- <section> 주제별 그룹$$,
$$[{"input": "", "output": "구조화된 콘텐츠"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <main>\n        <!-- article과 section 사용 -->\n    </main>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <main>\n        <article>\n            <h2>Article Title</h2>\n            <section>\n                <h3>Section 1</h3>\n                <p>Content here</p>\n            </section>\n            <section>\n                <h3>Section 2</h3>\n                <p>More content</p>\n            </section>\n        </article>\n    </main>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "article with sections"}]$$,
$$["article은 독립적 콘텐츠, section은 주제별 그룹입니다"]$$,
$$["semantic", "article", "section"]$$, 10);

-- ====================================
-- 완료 메시지
-- ====================================

-- ====================================
-- HTML Language Challenges - Part 2
-- Levels 51-100 (MEDIUM 30개 + HARD 20개)
-- ====================================

-- Unit 11: 멀티미디어 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-video$$, $$html$$, $$syntax$$, 51, $$video 태그$$, $$비디오 삽입$$, $$challenge$$, 2,
$$controls와 여러 소스를 가진 비디오를 삽입하세요.$$,
$$- <video> 태그\n- controls, width, height\n- 여러 source 태그$$,
$$[{"input": "", "output": "비디오 플레이어"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- video 태그를 추가하세요 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <video width="640" height="360" controls>\n        <source src="video.mp4" type="video/mp4">\n        <source src="video.webm" type="video/webm">\n        Your browser does not support the video tag.\n    </video>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "video with controls"}]$$,
$$["여러 포맷을 제공하면 브라우저가 지원하는 것을 선택합니다"]$$,
$$["multimedia", "video"]$$, 10),

($$html-audio$$, $$html$$, $$syntax$$, 52, $$audio 태그$$, $$오디오 삽입$$, $$challenge$$, 2,
$$autoplay와 loop가 있는 오디오를 삽입하세요.$$,
$$- <audio> 태그\n- controls, autoplay, loop$$,
$$[{"input": "", "output": "오디오 플레이어"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- audio 태그 추가 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <audio controls autoplay loop>\n        <source src="audio.mp3" type="audio/mpeg">\n        <source src="audio.ogg" type="audio/ogg">\n        Your browser does not support the audio element.\n    </audio>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "audio with autoplay"}]$$,
$$["autoplay는 사용자 경험상 신중히 사용해야 합니다"]$$,
$$["multimedia", "audio"]$$, 10),

($$html-iframe$$, $$html$$, $$syntax$$, 53, $$iframe$$, $$외부 콘텐츠 임베드$$, $$challenge$$, 2,
$$YouTube 비디오를 iframe으로 삽입하세요.$$,
$$- <iframe> 태그\n- src, width, height\n- frameborder, allowfullscreen$$,
$$[{"input": "", "output": "임베디드 비디오"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- YouTube iframe 추가 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <iframe width="560" height="315"\n        src="https://www.youtube.com/embed/VIDEO_ID"\n        frameborder="0"\n        allowfullscreen>\n    </iframe>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "youtube iframe"}]$$,
$$["iframe은 다른 HTML 페이지를 삽입할 수 있습니다"]$$,
$$["multimedia", "iframe"]$$, 12),

($$html-figure-figcaption$$, $$html$$, $$syntax$$, 54, $$figure와 figcaption$$, $$이미지 캡션$$, $$challenge$$, 2,
$$이미지에 캡션을 추가하세요.$$,
$$- <figure> 태그\n- <figcaption> 설명$$,
$$[{"input": "", "output": "캡션 있는 이미지"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <img src="photo.jpg" alt="Photo">\n    <p>Photo description</p>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <figure>\n        <img src="photo.jpg" alt="Photo">\n        <figcaption>Photo description</figcaption>\n    </figure>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "figure with figcaption"}]$$,
$$["figure는 이미지, 다이어그램, 코드 등을 감쌉니다"]$$,
$$["multimedia", "figure"]$$, 10),

($$html-picture$$, $$html$$, $$syntax$$, 55, $$picture 태그$$, $$반응형 이미지$$, $$challenge$$, 2,
$$화면 크기에 따라 다른 이미지를 보여주세요.$$,
$$- <picture> 태그\n- <source> media 쿼리\n- <img> 폴백$$,
$$[{"input": "", "output": "반응형 이미지"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- picture 태그로 반응형 이미지 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <picture>\n        <source media="(min-width: 800px)" srcset="large.jpg">\n        <source media="(min-width: 400px)" srcset="medium.jpg">\n        <img src="small.jpg" alt="Responsive image">\n    </picture>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "responsive picture"}]$$,
$$["picture는 아트 디렉션과 해상도 전환에 사용됩니다"]$$,
$$["multimedia", "picture", "responsive"]$$, 15);

-- Unit 12: 고급 폼 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-input-range$$, $$html$$, $$syntax$$, 56, $$범위 슬라이더$$, $$input type=range$$, $$challenge$$, 2,
$$0-100 범위의 슬라이더를 만드세요.$$,
$$- type="range"\n- min, max, value, step$$,
$$[{"input": "", "output": "슬라이더"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <label>Volume:</label>\n    <!-- range input -->\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <label>Volume:</label>\n    <input type="range" name="volume" min="0" max="100" value="50" step="5">\n</body>\n</html>$func$,
$$[{"input": "", "expected": "range slider"}]$$,
$$["step으로 증가 단위를 조절할 수 있습니다"]$$,
$$["form", "input", "range"]$$, 10),

($$html-input-color$$, $$html$$, $$syntax$$, 57, $$색상 선택$$, $$input type=color$$, $$challenge$$, 2,
$$색상 선택기를 만드세요.$$,
$$- type="color"\n- value는 hex 색상$$,
$$[{"input": "", "output": "색상 선택기"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <label>Pick a color:</label>\n    <!-- color input -->\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <label>Pick a color:</label>\n    <input type="color" name="color" value="#ff0000">\n</body>\n</html>$func$,
$$[{"input": "", "expected": "color picker"}]$$,
$$["color 타입은 색상 선택 UI를 제공합니다"]$$,
$$["form", "input", "color"]$$, 10),

($$html-datalist$$, $$html$$, $$syntax$$, 58, $$datalist$$, $$자동완성 목록$$, $$challenge$$, 2,
$$자동완성이 있는 입력 필드를 만드세요.$$,
$$- <datalist> 태그\n- input의 list 속성과 연결$$,
$$[{"input": "", "output": "자동완성"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <input type="text" name="browser">\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <input type="text" name="browser" list="browsers">\n    <datalist id="browsers">\n        <option value="Chrome">\n        <option value="Firefox">\n        <option value="Safari">\n        <option value="Edge">\n    </datalist>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "input with datalist"}]$$,
$$["datalist는 추천 옵션을 제공하지만 다른 값도 입력 가능합니다"]$$,
$$["form", "datalist"]$$, 12),

($$html-input-file$$, $$html$$, $$syntax$$, 59, $$파일 업로드$$, $$input type=file$$, $$challenge$$, 2,
$$여러 이미지 파일을 업로드할 수 있는 입력을 만드세요.$$,
$$- type="file"\n- accept, multiple 속성$$,
$$[{"input": "", "output": "파일 선택"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Upload images:</label>\n        <!-- file input -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Upload images:</label>\n        <input type="file" name="images" accept="image/*" multiple>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "file input with accept"}]$$,
$$["accept로 파일 유형을, multiple로 여러 파일 선택을 허용합니다"]$$,
$$["form", "input", "file"]$$, 10),

($$html-input-search$$, $$html$$, $$syntax$$, 60, $$검색 입력$$, $$input type=search$$, $$challenge$$, 2,
$$검색창을 만드세요.$$,
$$- type="search"\n- placeholder, autocomplete$$,
$$[{"input": "", "output": "검색창"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <!-- search input -->\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="search" name="q" placeholder="Search..." autocomplete="off">\n        <button type="submit">Search</button>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "search input"}]$$,
$$["search 타입은 검색 의도를 명시하고 X 버튼을 제공합니다"]$$,
$$["form", "input", "search"]$$, 10);

-- Unit 13: 폼 유효성 검사 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-required$$, $$html$$, $$syntax$$, 61, $$필수 입력$$, $$required 속성$$, $$challenge$$, 2,
$$필수 입력 필드를 만드세요.$$,
$$- required 속성\n- 제출 시 자동 검증$$,
$$[{"input": "", "output": "필수 필드"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="text" name="name">\n        <button type="submit">Submit</button>\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="text" name="name" required>\n        <button type="submit">Submit</button>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "required field"}]$$,
$$["required 필드가 비어있으면 폼 제출이 차단됩니다"]$$,
$$["form", "validation", "required"]$$, 8),

($$html-pattern$$, $$html$$, $$syntax$$, 62, $$정규식 검증$$, $$pattern 속성$$, $$challenge$$, 2,
$$전화번호 형식을 정규식으로 검증하세요.$$,
$$- pattern 속성\n- 정규식 사용$$,
$$[{"input": "", "output": "패턴 검증"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="tel" name="phone">\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="tel" name="phone"\n               pattern="[0-9]{3}-[0-9]{4}-[0-9]{4}"\n               placeholder="010-1234-5678"\n               required>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "phone pattern"}]$$,
$$["pattern으로 입력 형식을 제한할 수 있습니다"]$$,
$$["form", "validation", "pattern"]$$, 12),

($$html-minlength-maxlength$$, $$html$$, $$syntax$$, 63, $$길이 제한$$, $$minlength, maxlength$$, $$challenge$$, 2,
$$비밀번호 길이를 8-20자로 제한하세요.$$,
$$- minlength, maxlength 속성\n- 문자열 길이 검증$$,
$$[{"input": "", "output": "길이 제한"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="password" name="password">\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="password" name="password"\n               minlength="8" maxlength="20"\n               required>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "length restriction"}]$$,
$$["minlength와 maxlength로 입력 길이를 제한합니다"]$$,
$$["form", "validation", "length"]$$, 10),

($$html-min-max$$, $$html$$, $$syntax$$, 64, $$값 범위 제한$$, $$min, max$$, $$challenge$$, 2,
$$날짜를 오늘 이후로만 선택 가능하게 하세요.$$,
$$- min 속성에 오늘 날짜\n- 과거 날짜 선택 불가$$,
$$[{"input": "", "output": "날짜 범위 제한"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="date" name="appointment">\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="date" name="appointment"\n               min="2024-01-01"\n               required>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "date min"}]$$,
$$["min과 max로 날짜/숫자 범위를 제한합니다"]$$,
$$["form", "validation", "min-max"]$$, 10),

($$html-novalidate$$, $$html$$, $$syntax$$, 65, $$유효성 검사 비활성화$$, $$novalidate$$, $$challenge$$, 2,
$$폼의 HTML5 유효성 검사를 비활성화하세요.$$,
$$- novalidate 속성\n- form 태그에 추가$$,
$$[{"input": "", "output": "검증 비활성화"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form action="/submit">\n        <input type="email" required>\n        <button type="submit">Submit</button>\n    </form>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <form action="/submit" novalidate>\n        <input type="email" required>\n        <button type="submit">Submit</button>\n    </form>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "novalidate form"}]$$,
$$["novalidate는 커스텀 검증을 사용할 때 유용합니다"]$$,
$$["form", "validation", "novalidate"]$$, 8);

-- Unit 14: 메타 태그와 SEO (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-meta-description$$, $$html$$, $$syntax$$, 66, $$페이지 설명$$, $$meta description$$, $$challenge$$, 2,
$$검색엔진용 페이지 설명을 추가하세요.$$,
$$- meta name="description"\n- content 속성$$,
$$[{"input": "", "output": "SEO 설명"}]$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n    <meta name="description" content="This page provides information about...">\n</head>\n<body></body>\n</html>$func$,
$$[{"input": "", "expected": "meta description"}]$$,
$$["description은 검색 결과에 표시됩니다"]$$,
$$["meta", "seo"]$$, 8),

($$html-meta-keywords$$, $$html$$, $$syntax$$, 67, $$키워드$$, $$meta keywords$$, $$challenge$$, 2,
$$페이지 키워드를 추가하세요.$$,
$$- meta name="keywords"\n- 쉼표로 구분$$,
$$[{"input": "", "output": "키워드"}]$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n    <meta name="keywords" content="html, web, tutorial, programming">\n</head>\n<body></body>\n</html>$func$,
$$[{"input": "", "expected": "meta keywords"}]$$,
$$["keywords는 현대 SEO에서 중요도가 낮아졌습니다"]$$,
$$["meta", "seo"]$$, 8),

($$html-meta-author$$, $$html$$, $$syntax$$, 68, $$저자 정보$$, $$meta author$$, $$challenge$$, 2,
$$페이지 저자 정보를 추가하세요.$$,
$$- meta name="author"\n- 저자 이름$$,
$$[{"input": "", "output": "저자 정보"}]$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n    <meta name="author" content="John Doe">\n</head>\n<body></body>\n</html>$func$,
$$[{"input": "", "expected": "meta author"}]$$,
$$["author 메타 태그는 콘텐츠 제작자를 명시합니다"]$$,
$$["meta", "author"]$$, 8),

($$html-og-tags$$, $$html$$, $$syntax$$, 69, $$Open Graph 태그$$, $$SNS 공유 메타데이터$$, $$challenge$$, 2,
$$페이스북/SNS 공유용 Open Graph 태그를 추가하세요.$$,
$$- og:title, og:description, og:image\n- property 속성 사용$$,
$$[{"input": "", "output": "OG 태그"}]$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n    <meta property="og:title" content="My Awesome Page">\n    <meta property="og:description" content="Check out this page!">\n    <meta property="og:image" content="https://example.com/image.jpg">\n    <meta property="og:url" content="https://example.com/page">\n</head>\n<body></body>\n</html>$func$,
$$[{"input": "", "expected": "og tags"}]$$,
$$["Open Graph는 SNS 공유 시 표시되는 정보를 제어합니다"]$$,
$$["meta", "og", "social"]$$, 15),

($$html-twitter-card$$, $$html$$, $$syntax$$, 70, $$Twitter Card$$, $$트위터 카드 메타데이터$$, $$challenge$$, 2,
$$트위터 카드 메타 태그를 추가하세요.$$,
$$- twitter:card, twitter:title, twitter:description\n- name 속성 사용$$,
$$[{"input": "", "output": "트위터 카드"}]$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n    <meta name="twitter:card" content="summary_large_image">\n    <meta name="twitter:title" content="My Awesome Page">\n    <meta name="twitter:description" content="Check it out!">\n    <meta name="twitter:image" content="https://example.com/image.jpg">\n</head>\n<body></body>\n</html>$func$,
$$[{"input": "", "expected": "twitter card"}]$$,
$$["Twitter Card는 트윗에서 리치 미디어 표시를 제공합니다"]$$,
$$["meta", "twitter", "social"]$$, 15);

-- Unit 15: 시맨틱 고급 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-aside$$, $$html$$, $$syntax$$, 71, $$aside 태그$$, $$사이드바 콘텐츠$$, $$challenge$$, 2,
$$메인 콘텐츠와 별개의 사이드 콘텐츠를 만드세요.$$,
$$- <aside> 태그\n- 관련 링크, 광고 등$$,
$$[{"input": "", "output": "사이드바"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <main>\n        <h1>Main Content</h1>\n    </main>\n    <!-- aside 추가 -->\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <main>\n        <h1>Main Content</h1>\n    </main>\n    <aside>\n        <h2>Related Links</h2>\n        <ul>\n            <li><a href="#">Link 1</a></li>\n            <li><a href="#">Link 2</a></li>\n        </ul>\n    </aside>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "aside element"}]$$,
$$["aside는 메인 콘텐츠와 간접적으로 관련된 내용입니다"]$$,
$$["semantic", "aside"]$$, 10),

($$html-time$$, $$html$$, $$syntax$$, 72, $$time 태그$$, $$날짜/시간 표시$$, $$challenge$$, 2,
$$기계가 읽을 수 있는 시간 정보를 추가하세요.$$,
$$- <time> 태그\n- datetime 속성$$,
$$[{"input": "", "output": "시간 정보"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <p>Published: January 1, 2024</p>\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <p>Published: <time datetime="2024-01-01">January 1, 2024</time></p>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "time with datetime"}]$$,
$$["datetime 속성은 기계가 읽을 수 있는 형식입니다"]$$,
$$["semantic", "time"]$$, 10),

($$html-address$$, $$html$$, $$syntax$$, 73, $$address 태그$$, $$연락처 정보$$, $$challenge$$, 2,
$$저자나 조직의 연락처 정보를 추가하세요.$$,
$$- <address> 태그\n- 이메일, 주소 등$$,
$$[{"input": "", "output": "연락처"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <footer>\n        <!-- address 정보 -->\n    </footer>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <footer>\n        <address>\n            Contact: <a href="mailto:info@example.com">info@example.com</a><br>\n            123 Main St, City, Country\n        </address>\n    </footer>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "address element"}]$$,
$$["address는 연락처 정보를 나타냅니다"]$$,
$$["semantic", "address"]$$, 10),

($$html-details-summary$$, $$html$$, $$syntax$$, 74, $$details와 summary$$, $$접을 수 있는 콘텐츠$$, $$challenge$$, 2,
$$클릭하면 펼쳐지는 상세 정보를 만드세요.$$,
$$- <details> 태그\n- <summary> 제목$$,
$$[{"input": "", "output": "접기/펼치기"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- details/summary 추가 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <details>\n        <summary>Click to expand</summary>\n        <p>This is the hidden content that appears when you click.</p>\n    </details>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "details with summary"}]$$,
$$["details는 JavaScript 없이 접기/펼치기를 제공합니다"]$$,
$$["semantic", "details", "interactive"]$$, 12),

($$html-dialog$$, $$html$$, $$syntax$$, 75, $$dialog 태그$$, $$대화상자$$, $$challenge$$, 2,
$$모달 대화상자를 만드세요.$$,
$$- <dialog> 태그\n- open 속성으로 표시$$,
$$[{"input": "", "output": "대화상자"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- dialog 추가 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <dialog open>\n        <h2>Dialog Title</h2>\n        <p>This is a dialog box.</p>\n        <button>Close</button>\n    </dialog>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "dialog element"}]$$,
$$["dialog는 JavaScript로 showModal()을 호출하여 사용합니다"]$$,
$$["semantic", "dialog", "interactive"]$$, 12);

-- Unit 16: 접근성 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-aria-label$$, $$html$$, $$syntax$$, 76, $$ARIA 라벨$$, $$aria-label 속성$$, $$challenge$$, 3,
$$스크린 리더를 위한 ARIA 라벨을 추가하세요.$$,
$$- aria-label 속성\n- 시각적 텍스트가 없는 요소$$,
$$[{"input": "", "output": "접근 가능한 버튼"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <button>❌</button>\n</body>\n</html>$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <button aria-label="Close">❌</button>\n</body>\n</html>$$,
$$[{"input": "", "expected": "aria-label"}]$$,
$$["아이콘 버튼에는 aria-label이 필수입니다"]$$,
$$["accessibility", "aria", "hard"]$$, 12),

($$html-aria-labelledby$$, $$html$$, $$syntax$$, 77, $$ARIA labelledby$$, $$다른 요소로 라벨링$$, $$challenge$$, 3,
$$aria-labelledby로 요소를 다른 요소와 연결하세요.$$,
$$- aria-labelledby 속성\n- id로 참조$$,
$$[{"input": "", "output": "연결된 라벨"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <h2 id="dialog-title">Confirmation</h2>\n    <div>Are you sure?</div>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <div role="dialog" aria-labelledby="dialog-title">\n        <h2 id="dialog-title">Confirmation</h2>\n        <p>Are you sure?</p>\n    </div>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "aria-labelledby"}]$$,
$$["aria-labelledby는 여러 요소를 공백으로 구분하여 참조할 수 있습니다"]$$,
$$["accessibility", "aria", "hard"]$$, 15),

($$html-role$$, $$html$$, $$syntax$$, 78, $$ARIA role$$, $$역할 정의$$, $$challenge$$, 3,
$$커스텀 위젯에 적절한 ARIA role을 부여하세요.$$,
$$- role 속성\n- navigation, button, tablist 등$$,
$$[{"input": "", "output": "역할이 있는 요소"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <div>\n        <a href="#home">Home</a>\n        <a href="#about">About</a>\n    </div>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <div role="navigation">\n        <a href="#home">Home</a>\n        <a href="#about">About</a>\n    </div>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "navigation role"}]$$,
$$["시맨틱 태그를 사용할 수 없을 때 role을 사용합니다"]$$,
$$["accessibility", "aria", "role", "hard"]$$, 15),

($$html-tabindex$$, $$html$$, $$syntax$$, 79, $$tabindex$$, $$키보드 탐색 순서$$, $$challenge$$, 3,
$$키보드 탐색 순서를 지정하세요.$$,
$$- tabindex 속성\n- 0: 자연스러운 순서, -1: 포커스 불가능, 1+: 우선순위$$,
$$[{"input": "", "output": "탭 순서"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <button>First</button>\n    <div>Important Content</div>\n    <button>Second</button>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <button tabindex="1">First</button>\n    <div tabindex="0">Important Content</div>\n    <button tabindex="2">Second</button>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "tabindex set"}]$$,
$$["tabindex="0"은 자연스러운 순서로 포커스 가능하게 합니다"]$$,
$$["accessibility", "tabindex", "hard"]$$, 15),

($$html-skip-link$$, $$html$$, $$syntax$$, 80, $$스킵 네비게이션$$, $$본문으로 바로가기$$, $$challenge$$, 3,
$$키보드 사용자를 위한 스킵 링크를 추가하세요.$$,
$$- 페이지 최상단에 배치\n- 메인 콘텐츠로 점프$$,
$$[{"input": "", "output": "스킵 링크"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <header>...</header>\n    <nav>...</nav>\n    <main id="main-content">...</main>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <a href="#main-content" class="skip-link">Skip to main content</a>\n    <header>...</header>\n    <nav>...</nav>\n    <main id="main-content">...</main>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "skip link"}]$$,
$$["스킵 링크는 보통 CSS로 숨기고 포커스 시 표시합니다"]$$,
$$["accessibility", "skip-link", "hard"]$$, 18);

-- Unit 17: 외부 리소스 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-link-stylesheet$$, $$html$$, $$syntax$$, 81, $$스타일시트 링크$$, $$link 태그로 CSS 연결$$, $$challenge$$, 3,
$$외부 CSS 파일을 연결하세요.$$,
$$- <link> 태그\n- rel="stylesheet"$$,
$$[{"input": "", "output": "CSS 연결"}]$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n    <link rel="stylesheet" href="styles.css">\n</head>\n<body></body>\n</html>$func$,
$$[{"input": "", "expected": "stylesheet link"}]$$,
$$["link 태그는 head 안에 위치합니다"]$$,
$$["resources", "css", "hard"]$$, 10),

($$html-script-tag$$, $$html$$, $$syntax$$, 82, $$script 태그$$, $$JavaScript 연결$$, $$challenge$$, 3,
$$외부 JavaScript 파일을 defer로 로드하세요.$$,
$$- <script> 태그\n- defer 속성$$,
$$[{"input": "", "output": "JS 연결"}]$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n    <script src="script.js" defer></script>\n</head>\n<body></body>\n</html>$func$,
$$[{"input": "", "expected": "script with defer"}]$$,
$$["defer는 HTML 파싱 후 스크립트를 실행합니다"]$$,
$$["resources", "javascript", "hard"]$$, 12),

($$html-link-preload$$, $$html$$, $$syntax$$, 83, $$preload$$, $$리소스 미리 로드$$, $$challenge$$, 3,
$$중요한 폰트를 preload하세요.$$,
$$- link rel="preload"\n- as 속성으로 타입 지정$$,
$$[{"input": "", "output": "preload"}]$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n    <link rel="preload" href="font.woff2" as="font" type="font/woff2" crossorigin>\n</head>\n<body></body>\n</html>$func$,
$$[{"input": "", "expected": "preload font"}]$$,
$$["preload는 페이지 로딩 성능을 최적화합니다"]$$,
$$["resources", "preload", "performance", "hard"]$$, 18),

($$html-link-prefetch$$, $$html$$, $$syntax$$, 84, $$prefetch$$, $$향후 리소스 미리 가져오기$$, $$challenge$$, 3,
$$다음 페이지의 리소스를 prefetch하세요.$$,
$$- link rel="prefetch"\n- 낮은 우선순위로 로드$$,
$$[{"input": "", "output": "prefetch"}]$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n    <link rel="prefetch" href="next-page.html">\n</head>\n<body></body>\n</html>$func$,
$$[{"input": "", "expected": "prefetch link"}]$$,
$$["prefetch는 사용자가 곧 방문할 페이지를 미리 로드합니다"]$$,
$$["resources", "prefetch", "performance", "hard"]$$, 18),

($$html-link-dns-prefetch$$, $$html$$, $$syntax$$, 85, $$DNS prefetch$$, $$DNS 미리 조회$$, $$challenge$$, 3,
$$외부 도메인의 DNS를 미리 조회하세요.$$,
$$- link rel="dns-prefetch"\n- 외부 리소스 도메인$$,
$$[{"input": "", "output": "dns-prefetch"}]$$,
$$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n    <link rel="dns-prefetch" href="https://fonts.googleapis.com">\n</head>\n<body></body>\n</html>$func$,
$$[{"input": "", "expected": "dns-prefetch"}]$$,
$$["dns-prefetch는 외부 리소스 로딩 시간을 단축합니다"]$$,
$$["resources", "dns-prefetch", "performance", "hard"]$$, 18);

-- Unit 18: 고급 테이블 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-table-thead-tbody$$, $$html$$, $$syntax$$, 86, $$테이블 구조화$$, $$thead, tbody, tfoot$$, $$challenge$$, 3,
$$테이블을 헤더, 본문, 푸터로 구조화하세요.$$,
$$- <thead> 헤더 그룹\n- <tbody> 본문 그룹\n- <tfoot> 푸터 그룹$$,
$$[{"input": "", "output": "구조화된 테이블"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr><th>Name</th><th>Score</th></tr>\n        <tr><td>John</td><td>90</td></tr>\n        <tr><td>Total</td><td>90</td></tr>\n    </table>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <thead>\n            <tr><th>Name</th><th>Score</th></tr>\n        </thead>\n        <tbody>\n            <tr><td>John</td><td>90</td></tr>\n        </tbody>\n        <tfoot>\n            <tr><td>Total</td><td>90</td></tr>\n        </tfoot>\n    </table>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "table with thead tbody tfoot"}]$$,
$$["thead, tbody, tfoot으로 테이블을 의미적으로 구분합니다"]$$,
$$["table", "structure", "hard"]$$, 15),

($$html-table-colgroup$$, $$html$$, $$syntax$$, 87, $$컬럼 그룹$$, $$colgroup과 col$$, $$challenge$$, 3,
$$컬럼 단위로 스타일을 적용하세요.$$,
$$- <colgroup> 태그\n- <col> 각 컬럼$$,
$$[{"input": "", "output": "컬럼 그룹"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr><th>A</th><th>B</th><th>C</th></tr>\n        <tr><td>1</td><td>2</td><td>3</td></tr>\n    </table>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <colgroup>\n            <col style="background-color: lightblue">\n            <col span="2" style="background-color: lightyellow">\n        </colgroup>\n        <tr><th>A</th><th>B</th><th>C</th></tr>\n        <tr><td>1</td><td>2</td><td>3</td></tr>\n    </table>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "colgroup with styles"}]$$,
$$["colgroup은 컬럼 단위 스타일링을 가능하게 합니다"]$$,
$$["table", "colgroup", "hard"]$$, 18),

($$html-table-caption$$, $$html$$, $$syntax$$, 88, $$테이블 캡션$$, $$caption 태그$$, $$challenge$$, 3,
$$테이블에 제목을 추가하세요.$$,
$$- <caption> 태그\n- table 바로 다음$$,
$$[{"input": "", "output": "캡션 있는 테이블"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr><th>Name</th><th>Age</th></tr>\n        <tr><td>John</td><td>30</td></tr>\n    </table>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <caption>User Information</caption>\n        <tr><th>Name</th><th>Age</th></tr>\n        <tr><td>John</td><td>30</td></tr>\n    </table>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "table with caption"}]$$,
$$["caption은 테이블의 제목/설명을 제공합니다"]$$,
$$["table", "caption", "hard"]$$, 12),

($$html-table-scope$$, $$html$$, $$syntax$$, 89, $$scope 속성$$, $$헤더 범위 지정$$, $$challenge$$, 3,
$$th 태그에 scope를 지정하여 접근성을 개선하세요.$$,
$$- scope="col" 또는 "row"\n- 헤더가 적용되는 범위$$,
$$[{"input": "", "output": "scope 속성"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr><th>Name</th><th>Math</th><th>English</th></tr>\n        <tr><th>John</th><td>90</td><td>85</td></tr>\n    </table>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr>\n            <th scope="col">Name</th>\n            <th scope="col">Math</th>\n            <th scope="col">English</th>\n        </tr>\n        <tr>\n            <th scope="row">John</th>\n            <td>90</td>\n            <td>85</td>\n        </tr>\n    </table>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "th with scope"}]$$,
$$["scope는 스크린 리더가 테이블을 이해하는 데 도움을 줍니다"]$$,
$$["table", "scope", "accessibility", "hard"]$$, 18),

($$html-table-complex$$, $$html$$, $$syntax$$, 90, $$복잡한 테이블$$, $$모든 기능 활용$$, $$challenge$$, 3,
$$thead, tbody, colspan, rowspan을 모두 사용한 복잡한 테이블을 만드세요.$$,
$$- 모든 테이블 기능 활용\n- 구조화된 레이아웃$$,
$$[{"input": "", "output": "복잡한 테이블"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- 복잡한 테이블 작성 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <table border="1">\n        <caption>Sales Report</caption>\n        <thead>\n            <tr>\n                <th rowspan="2">Product</th>\n                <th colspan="2">Q1</th>\n                <th colspan="2">Q2</th>\n            </tr>\n            <tr>\n                <th>Sales</th><th>Profit</th>\n                <th>Sales</th><th>Profit</th>\n            </tr>\n        </thead>\n        <tbody>\n            <tr>\n                <th scope="row">Product A</th>\n                <td>100</td><td>30</td>\n                <td>120</td><td>40</td>\n            </tr>\n        </tbody>\n    </table>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "complex table structure"}]$$,
$$["복잡한 테이블은 caption, scope 등으로 접근성을 확보해야 합니다"]$$,
$$["table", "complex", "hard"]$$, 25);

-- Unit 19: Canvas와 SVG (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-canvas-basic$$, $$html$$, $$syntax$$, 91, $$canvas 태그$$, $$캔버스 생성$$, $$challenge$$, 3,
$$그래픽을 그릴 canvas 요소를 만드세요.$$,
$$- <canvas> 태그\n- width, height 속성$$,
$$[{"input": "", "output": "캔버스"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- canvas 추가 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <canvas id="myCanvas" width="400" height="300"></canvas>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "canvas element"}]$$,
$$["canvas는 JavaScript로 그래픽을 그립니다"]$$,
$$["graphics", "canvas", "hard"]$$, 12),

($$html-svg-inline$$, $$html$$, $$syntax$$, 92, $$inline SVG$$, $$SVG 코드 삽입$$, $$challenge$$, 3,
$$인라인 SVG로 원을 그리세요.$$,
$$- <svg> 태그\n- <circle> 요소$$,
$$[{"input": "", "output": "SVG 원"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- SVG 원 그리기 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <svg width="100" height="100">\n        <circle cx="50" cy="50" r="40" fill="blue" />\n    </svg>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "svg circle"}]$$,
$$["SVG는 벡터 그래픽으로 확대해도 깨지지 않습니다"]$$,
$$["graphics", "svg", "hard"]$$, 15),

($$html-svg-path$$, $$html$$, $$syntax$$, 93, $$SVG path$$, $$복잡한 도형$$, $$challenge$$, 3,
$$SVG path로 삼각형을 그리세요.$$,
$$- <path> 요소\n- d 속성에 경로 데이터$$,
$$[{"input": "", "output": "SVG 삼각형"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <svg width="100" height="100">\n        <!-- path로 삼각형 -->\n    </svg>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <svg width="100" height="100">\n        <path d="M 50 10 L 90 90 L 10 90 Z" fill="red" />\n    </svg>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "svg triangle"}]$$,
$$["M은 이동, L은 선 그리기, Z는 경로 닫기입니다"]$$,
$$["graphics", "svg", "path", "hard"]$$, 20),

($$html-svg-text$$, $$html$$, $$syntax$$, 94, $$SVG 텍스트$$, $$SVG에 텍스트 추가$$, $$challenge$$, 3,
$$SVG 내에 스타일이 적용된 텍스트를 추가하세요.$$,
$$- <text> 요소\n- x, y, fill, font-size$$,
$$[{"input": "", "output": "SVG 텍스트"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <svg width="200" height="100">\n        <!-- text 추가 -->\n    </svg>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <svg width="200" height="100">\n        <text x="10" y="50" fill="purple" font-size="24">Hello SVG</text>\n    </svg>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "svg text"}]$$,
$$["SVG 텍스트는 벡터이므로 확대/축소가 자유롭습니다"]$$,
$$["graphics", "svg", "text", "hard"]$$, 15),

($$html-svg-animation$$, $$html$$, $$syntax$$, 95, $$SVG 애니메이션$$, $$animate 요소$$, $$challenge$$, 3,
$$SVG 요소에 애니메이션을 추가하세요.$$,
$$- <animate> 요소\n- attributeName, from, to, dur$$,
$$[{"input": "", "output": "애니메이션 SVG"}]$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <svg width="100" height="100">\n        <circle cx="50" cy="50" r="20" fill="green" />\n    </svg>\n</body>\n</html>$func$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <svg width="100" height="100">\n        <circle cx="50" cy="50" r="20" fill="green">\n            <animate attributeName="r" from="20" to="40" dur="1s" repeatCount="indefinite" />\n        </circle>\n    </svg>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "animated svg"}]$$,
$$["SVG는 SMIL 애니메이션을 지원합니다"]$$,
$$["graphics", "svg", "animation", "hard"]$$, 20);

-- Unit 20: 고급 기능 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
($$html-data-attributes$$, $$html$$, $$syntax$$, 96, $$data 속성$$, $$커스텀 데이터 속성$$, $$challenge$$, 3,
$$요소에 커스텀 데이터를 저장하세요.$$,
$$- data-* 속성\n- JavaScript에서 접근 가능$$,
$$[{"input": "", "output": "data 속성"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <div>Product: Laptop</div>\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <div data-product-id="12345" data-category="electronics" data-price="999">Product: Laptop</div>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "data attributes"}]$$,
$$["data-* 속성은 JavaScript dataset으로 접근합니다"]$$,
$$["advanced", "data-attributes", "hard"]$$, 15),

($$html-contenteditable$$, $$html$$, $$syntax$$, 97, $$contenteditable$$, $$편집 가능한 콘텐츠$$, $$challenge$$, 3,
$$사용자가 편집할 수 있는 요소를 만드세요.$$,
$$- contenteditable="true"\n- div, p 등에 적용$$,
$$[{"input": "", "output": "편집 가능 영역"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <div>Edit this text</div>\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <div contenteditable="true">Edit this text</div>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "contenteditable div"}]$$,
$$["contenteditable은 간단한 에디터를 만들 때 유용합니다"]$$,
$$["advanced", "contenteditable", "hard"]$$, 15),

($$html-draggable$$, $$html$$, $$syntax$$, 98, $$draggable$$, $$드래그 가능한 요소$$, $$challenge$$, 3,
$$드래그 앤 드롭이 가능한 요소를 만드세요.$$,
$$- draggable="true"\n- ondragstart 이벤트$$,
$$[{"input": "", "output": "드래그 가능"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <div id="item">Drag me</div>\n</body>\n</html>$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <div id="item" draggable="true">Drag me</div>\n</body>\n</html>$$,
$$[{"input": "", "expected": "draggable element"}]$$,
$$["draggable은 drag & drop API와 함께 사용됩니다"]$$,
$$["advanced", "draggable", "hard"]$$, 18),

($$html-progress$$, $$html$$, $$syntax$$, 99, $$progress 바$$, $$진행률 표시$$, $$challenge$$, 3,
$$진행률을 나타내는 progress 바를 만드세요.$$,
$$- <progress> 태그\n- value, max 속성$$,
$$[{"input": "", "output": "진행률 바"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- progress 바 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <label>Upload progress:</label>\n    <progress value="70" max="100">70%</progress>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "progress bar"}]$$,
$$["progress는 작업 진행률을 시각적으로 표시합니다"]$$,
$$["advanced", "progress", "hard"]$$, 12),

($$html-template$$, $$html$$, $$syntax$$, 100, $$template 태그$$, $$HTML 템플릿$$, $$challenge$$, 3,
$$재사용 가능한 HTML 템플릿을 만드세요.$$,
$$- <template> 태그\n- JavaScript로 복제하여 사용$$,
$$[{"input": "", "output": "템플릿"}]$$,
$$<!DOCTYPE html>\n<html>\n<body>\n    <!-- template 추가 -->\n</body>\n</html>$$,
$func$<!DOCTYPE html>\n<html>\n<body>\n    <template id="card-template">\n        <div class="card">\n            <h3></h3>\n            <p></p>\n        </div>\n    </template>\n</body>\n</html>$func$,
$$[{"input": "", "expected": "template element"}]$$,
$$["template 내용은 렌더링되지 않고 JavaScript로 복제합니다"]$$,
$$["advanced", "template", "hard"]$$, 18);

-- ====================================
-- 완료 메시지
-- ====================================

