-- ====================================
-- CSS Language Challenges - Part 2
-- Levels 51-100 (MEDIUM 30�?+ HARD 20�?
-- ====================================

-- Unit 11: 고급 Flexbox (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('css-flex-wrap', 'css', 'syntax', 51, 'Flex 줄바�?, 'flex-wrap', 'challenge', 2,
'?�이?�이 ?�치�??�음 줄로 ?�기?�요.',
'- flex-wrap: wrap\n- ?�러 �??�용',
'[{"input": "", "output": "줄바�?flex"}]',
'.container {\n    display: flex;\n    /* 줄바�??�용 */\n}',
'.container {\n    display: flex;\n    flex-wrap: wrap;\n}',
'[{"input": "", "expected": "flex wrap"}]',
'["nowrap(기본), wrap, wrap-reverse 값을 ?�용?????�습?�다"]',
ARRAY['flexbox', 'wrap'], 10),

('css-flex-grow', 'css', 'syntax', 52, 'Flex ?�장', 'flex-grow', 'challenge', 2,
'?�정 ?�이?�이 ?��? 공간??모두 차�??�게 ?�세??',
'- flex-grow: 1\n- ?�장 비율',
'[{"input": "", "output": "?�장?�는 ?�이??}]',
'.item {\n    /* ?��? 공간 차�? */\n}',
'.item {\n    flex-grow: 1;\n}',
'[{"input": "", "expected": "flex-grow 1"}]',
'["flex-grow???��? 공간??비율�??�눕?�다"]',
ARRAY['flexbox', 'flex-grow'], 12),

('css-flex-shrink', 'css', 'syntax', 53, 'Flex 축소', 'flex-shrink', 'challenge', 2,
'?�이?�이 축소?��? ?�게 ?�세??',
'- flex-shrink: 0\n- 축소 방�?',
'[{"input": "", "output": "축소 ????}]',
'.item {\n    /* 축소 방�? */\n}',
'.item {\n    flex-shrink: 0;\n}',
'[{"input": "", "expected": "no shrink"}]',
'["flex-shrink: 0?� 고정 ?�기 ?�이?�을 만듭?�다"]',
ARRAY['flexbox', 'flex-shrink'], 12),

('css-align-self', 'css', 'syntax', 54, '개별 ?�렬', 'align-self', 'challenge', 2,
'?�정 ?�이?�만 ?�르�??�렬?�세??',
'- align-self: flex-end\n- 개별 ?�이???�렬',
'[{"input": "", "output": "개별 ?�렬"}]',
'.special {\n    /* ?�단 ?�렬 */\n}',
'.special {\n    align-self: flex-end;\n}',
'[{"input": "", "expected": "align-self end"}]',
'["align-self??개별 ?�이?�의 align-items�??�정?�합?�다"]',
ARRAY['flexbox', 'align-self'], 12),

('css-order', 'css', 'syntax', 55, 'Flex ?�서', 'order ?�성', 'challenge', 2,
'?�이?�의 ?�각???�서�?변경하?�요.',
'- order: -1\n- ?�시 ?�서 조정',
'[{"input": "", "output": "?�서 변�?}]',
'.first {\n    /* �??�으�?*/\n}',
'.first {\n    order: -1;\n}',
'[{"input": "", "expected": "order -1"}]',
'["order 값이 ?�을?�록 ?�에 배치?�니??]',
ARRAY['flexbox', 'order'], 12);

-- Unit 12: Grid 기본 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('css-grid-container', 'css', 'syntax', 56, 'Grid 컨테?�너', 'display: grid', 'challenge', 2,
'Grid ?�이?�웃???�성?�하?�요.',
'- display: grid\n- grid 컨테?�너 ?�성',
'[{"input": "", "output": "grid 컨테?�너"}]',
'.container {\n    /* grid ?�성??*/\n}',
'.container {\n    display: grid;\n}',
'[{"input": "", "expected": "grid container"}]',
'["display: grid??2차원 ?�이?�웃??만듭?�다"]',
ARRAY['grid', 'basics'], 10),

('css-grid-template-columns', 'css', 'syntax', 57, 'Grid ??, 'grid-template-columns', 'challenge', 2,
'3개의 ?�일???�비 ?�을 만드?�요.',
'- grid-template-columns: 1fr 1fr 1fr\n- ?�는 repeat(3, 1fr)',
'[{"input": "", "output": "3??그리??}]',
'.container {\n    display: grid;\n    /* 3�???*/\n}',
'.container {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n}',
'[{"input": "", "expected": "3 columns"}]',
'["fr?� fraction ?�위�?비율???��??�니??]',
ARRAY['grid', 'columns'], 12),

('css-grid-gap', 'css', 'syntax', 58, 'Grid 간격', 'gap', 'challenge', 2,
'그리???�이???�이??20px 간격??추�??�세??',
'- gap: 20px\n- ?�과 ??간격',
'[{"input": "", "output": "20px 간격"}]',
'.container {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n    /* 간격 추�? */\n}',
'.container {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n    gap: 20px;\n}',
'[{"input": "", "expected": "20px gap"}]',
'["gap?� row-gap�?column-gap???�축 ?�성?�니??]',
ARRAY['grid', 'gap'], 10),

('css-grid-column-span', 'css', 'syntax', 59, '??병합', 'grid-column', 'challenge', 2,
'?�이?�이 2�??�을 차�??�게 ?�세??',
'- grid-column: span 2\n- ??병합',
'[{"input": "", "output": "2??병합"}]',
'.wide {\n    /* 2??차�? */\n}',
'.wide {\n    grid-column: span 2;\n}',
'[{"input": "", "expected": "span 2 columns"}]',
'["span?� �?개의 ?�??차�??��? 지?�합?�다"]',
ARRAY['grid', 'span'], 12),

('css-grid-template-areas', 'css', 'syntax', 60, 'Grid ?�역', 'grid-template-areas', 'challenge', 2,
'?�름???�는 그리???�역???�의?�세??',
'- grid-template-areas\n- ?�각???�이?�웃 ?�의',
'[{"input": "", "output": "명명???�역"}]',
'.container {\n    display: grid;\n    /* ?�역 ?�의 */\n}',
'.container {\n    display: grid;\n    grid-template-areas:\n        "header header"\n        "sidebar main"\n        "footer footer";\n}',
'[{"input": "", "expected": "template areas"}]',
'["grid-area�??�소�??�역??배치?�니??]',
ARRAY['grid', 'areas'], 15);

-- Unit 13: 변?�과 ?�니메이??(5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('css-transform-rotate', 'css', 'syntax', 61, '?�전 변??, 'transform: rotate', 'challenge', 2,
'?�소�?45???�전?�세??',
'- transform: rotate(45deg)\n- ?�전 변??,
'[{"input": "", "output": "45???�전"}]',
'.rotated {\n    /* 45???�전 */\n}',
'.rotated {\n    transform: rotate(45deg);\n}',
'[{"input": "", "expected": "45deg rotation"}]',
'["deg, rad, turn ?�위�??�용?????�습?�다"]',
ARRAY['transform', 'rotate'], 10),

('css-transform-scale', 'css', 'syntax', 62, '?�기 변??, 'transform: scale', 'challenge', 2,
'?�버 ???�소�?1.2�??��??�세??',
'- transform: scale(1.2)\n- ?�기 조정',
'[{"input": "", "output": "?��? ?�과"}]',
'.card:hover {\n    /* 1.2�??��? */\n}',
'.card:hover {\n    transform: scale(1.2);\n}',
'[{"input": "", "expected": "scale 1.2"}]',
'["scale(x, y)�?가로세�??�르�??��??????�습?�다"]',
ARRAY['transform', 'scale'], 10),

('css-transition', 'css', 'syntax', 63, '?�환 ?�과', 'transition', 'challenge', 2,
'모든 ?�성 변?�에 0.3�??�환 ?�과�?추�??�세??',
'- transition: all 0.3s\n- 부?�러??변??,
'[{"input": "", "output": "?�환 ?�과"}]',
'.button {\n    /* ?�환 ?�과 */\n}',
'.button {\n    transition: all 0.3s;\n}',
'[{"input": "", "expected": "transition 0.3s"}]',
'["transition?� ?�성, ?�간, ?�?�밍 ?�수�?지?�합?�다"]',
ARRAY['transition', 'animation'], 12),

('css-keyframes', 'css', 'syntax', 64, '?�프?�임 ?�니메이??, '@keyframes', 'challenge', 2,
'?�이?�인 ?�니메이?�을 ?�의?�세??',
'- @keyframes 규칙\n- opacity 변??,
'[{"input": "", "output": "?�이?�인"}]',
'/* ?�이?�인 ?�니메이??*/\n',
'@keyframes fadeIn {\n    from {\n        opacity: 0;\n    }\n    to {\n        opacity: 1;\n    }\n}',
'[{"input": "", "expected": "fadeIn keyframes"}]',
'["from/to ?�는 0%/100% ?�워?��? ?�용?�니??]',
ARRAY['animation', 'keyframes'], 15),

('css-animation', 'css', 'syntax', 65, '?�니메이???�용', 'animation', 'challenge', 2,
'fadeIn ?�니메이?�을 1�??�안 ?�생?�세??',
'- animation: fadeIn 1s\n- ?�니메이???�행',
'[{"input": "", "output": "?�니메이???�행"}]',
'.element {\n    /* ?�니메이???�용 */\n}',
'.element {\n    animation: fadeIn 1s;\n}',
'[{"input": "", "expected": "animation applied"}]',
'["animation?� ?�름, ?�간, ?�?�밍, 반복 ?�을 지?�합?�다"]',
ARRAY['animation', 'apply'], 12);

-- Unit 14: 반응???�자??(5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('css-media-query-basic', 'css', 'syntax', 66, '미디??쿼리', '@media', 'challenge', 2,
'?�면??768px ?�하????글???�기�?14px�?변경하?�요.',
'- @media (max-width: 768px)\n- 반응??중단??,
'[{"input": "", "output": "모바??글???�기"}]',
'body {\n    font-size: 16px;\n}\n\n/* 768px ?�하 */\n',
'body {\n    font-size: 16px;\n}\n\n@media (max-width: 768px) {\n    body {\n        font-size: 14px;\n    }\n}',
'[{"input": "", "expected": "media query"}]',
'["max-width???�하, min-width???�상???��??�니??]',
ARRAY['responsive', 'media-query'], 12),

('css-mobile-first', 'css', 'syntax', 67, '모바???�선', 'min-width 미디??쿼리', 'challenge', 2,
'모바???�선?�로 ?�블�??�상?�서 3??그리?��? 만드?�요.',
'- 기본: 1??n- min-width: 768px?�서 3??,
'[{"input": "", "output": "모바???�선"}]',
'.container {\n    /* 기본: 1??*/\n}\n\n/* 768px ?�상 */\n',
'.container {\n    display: grid;\n    grid-template-columns: 1fr;\n}\n\n@media (min-width: 768px) {\n    .container {\n        grid-template-columns: repeat(3, 1fr);\n    }\n}',
'[{"input": "", "expected": "mobile first grid"}]',
'["모바???�선?� min-width�??�용?�니??]',
ARRAY['responsive', 'mobile-first'], 15),

('css-responsive-images', 'css', 'syntax', 68, '반응???��?지', 'max-width: 100%', 'challenge', 2,
'?��?지가 부모�? ?��? ?�게 ?�세??',
'- max-width: 100%\n- height: auto',
'[{"input": "", "output": "반응???��?지"}]',
'/* Code */
img {\n    /* 반응???�정 */\n}',
'img {\n    max-width: 100%;\n    height: auto;\n}',
'[{"input": "", "expected": "responsive img"}]',
'["max-width: 100%???��?지가 부모�? ?��? ?�게 ?�니??]',
ARRAY['responsive', 'images'], 10),

('css-container-query', 'css', 'syntax', 69, '컨테?�너 쿼리', '@container', 'challenge', 2,
'컨테?�너 ?�비 기�??�로 ?��??�을 변경하?�요.',
'- container-type: inline-size\n- @container 쿼리',
'[{"input": "", "output": "컨테?�너 쿼리"}]',
'.parent {\n    /* 컨테?�너 ?�정 */\n}\n\n/* 컨테?�너 400px ?�상 */\n',
'.parent {\n    container-type: inline-size;\n}\n\n@container (min-width: 400px) {\n    .child {\n        font-size: 18px;\n    }\n}',
'[{"input": "", "expected": "container query"}]',
'["컨테?�너 쿼리??부�??�기 기�??�로 반응?�니??]',
ARRAY['responsive', 'container-query'], 18),

('css-clamp', 'css', 'syntax', 70, '?�동???�기', 'clamp() ?�수', 'challenge', 2,
'글???�기�?최소 16px, 최�? 24px�??�한?�세??',
'- clamp(min, preferred, max)\n- ?�동???�기',
'[{"input": "", "output": "clamp ?�기"}]',
'h1 {\n    /* clamp ?�용 */\n}',
'h1 {\n    font-size: clamp(16px, 5vw, 24px);\n}',
'[{"input": "", "expected": "clamp font size"}]',
'["clamp??최소, ?�호, 최�? �??�이�??��??�니??]',
ARRAY['responsive', 'clamp'], 15);

-- Unit 15: 고급 ?�택??(5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('css-descendant-selector', 'css', 'syntax', 71, '?�손 ?�택??, '공백 ?�택??, 'challenge', 2,
'nav ?�의 모든 a ?�그�??�택?�세??',
'- 공백?�로 ?�손 ?�택\n- nav a',
'[{"input": "", "output": "nav 링크"}]',
'',
'nav a {\n    color: blue;\n}',
'[{"input": "", "expected": "nav a selected"}]',
'["?�손 ?�택?�는 모든 ?�위 ?�소�??�택?�니??]',
ARRAY['selector', 'descendant'], 10),

('css-child-selector', 'css', 'syntax', 72, '?�식 ?�택??, '> ?�택??, 'challenge', 2,
'div??직접 ?�식??p�??�택?�세??',
'- > ?�택??n- 직접 ?�식�?,
'[{"input": "", "output": "직접 ?�식"}]',
'/* div > p */\n',
'div > p {\n    margin-bottom: 10px;\n}',
'[{"input": "", "expected": "direct children"}]',
'["?�식 ?�택?�는 직접 ?�식�??�택?�니??]',
ARRAY['selector', 'child'], 10),

('css-adjacent-sibling', 'css', 'syntax', 73, '?�접 ?�제 ?�택??, '+ ?�택??, 'challenge', 2,
'h2 바로 ?�음??p�??�택?�세??',
'- + ?�택??n- 바로 ?�음 ?�제',
'[{"input": "", "output": "?�접 ?�제"}]',
'',
'h2 + p {\n    margin-top: 0;\n}',
'[{"input": "", "expected": "adjacent sibling"}]',
'["+??바로 ?�음 ?�제�??�택?�니??]',
ARRAY['selector', 'adjacent'], 12),

('css-general-sibling', 'css', 'syntax', 74, '?�반 ?�제 ?�택??, '~ ?�택??, 'challenge', 2,
'h2 ?�후??모든 p�??�택?�세??',
'- ~ ?�택??n- ?�의 모든 ?�제',
'[{"input": "", "output": "모든 ?�제"}]',
'/* h2 ~ p */\n',
'h2 ~ p {\n    color: gray;\n}',
'[{"input": "", "expected": "general siblings"}]',
'["~???�후??모든 ?�제�??�택?�니??]',
ARRAY['selector', 'sibling'], 12),

('css-attribute-selector', 'css', 'syntax', 75, '?�성 ?�택??, '[?�성] ?�택??, 'challenge', 2,
'target ?�성???�는 a ?�그�??�택?�세??',
'- [?�성] ?�택??n- ?�성 존재 ?�인',
'[{"input": "", "output": "?�성 ?�택"}]',
'',
'a[target] {\n    font-weight: bold;\n}',
'[{"input": "", "expected": "attribute selector"}]',
'["[?�성=�?, [?�성^=�?, [?�성$=�? ???�양???�태가 ?�습?�다"]',
ARRAY['selector', 'attribute'], 12);

-- Unit 16: 가???�소 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('css-before', 'css', 'syntax', 76, '::before 가???�소', '?�에 콘텐�?추�?', 'challenge', 3,
'모든 링크 ?�에 "?? ?�이콘을 추�??�세??',
'- ::before 가???�소\n- content ?�성',
'[{"input": "", "output": "?�이�?추�?"}]',
'a {\n    /* before 추�? */\n}',
'a::before {\n    content: "??";\n}',
'[{"input": "", "expected": "before content"}]',
'["::before???�소 ?�에 콘텐츠�? ?�입?�니??]',
ARRAY['pseudo-element', 'before', 'hard'], 15),

('css-after', 'css', 'syntax', 77, '::after 가???�소', '?�에 콘텐�?추�?', 'challenge', 3,
'?��? 링크 ?�에 "?? ?�이콘을 추�??�세??',
'- ::after 가???�소\n- [target="_blank"] ?�택??,
'[{"input": "", "output": "?��? 링크 ?�시"}]',
'a[target="_blank"] {\n    /* after 추�? */\n}',
'a[target="_blank"]::after {\n    content: " ??;\n}',
'[{"input": "", "expected": "after content"}]',
'["::after???�소 ?�에 콘텐츠�? ?�입?�니??]',
ARRAY['pseudo-element', 'after', 'hard'], 15),

('css-first-letter', 'css', 'syntax', 78, '::first-letter', '�?글???��???, 'challenge', 3,
'문단??�?글?��? ?�게 만드?�요.',
'- ::first-letter\n- font-size, color 변�?,
'[{"input": "", "output": "?�롭�?}]',
'p::first-letter {\n    /* �?글???��???*/\n}',
'p::first-letter {\n    font-size: 2em;\n    font-weight: bold;\n}',
'[{"input": "", "expected": "first letter styled"}]',
'["::first-letter???�롭�??�과�?만듭?�다"]',
ARRAY['pseudo-element', 'first-letter', 'hard'], 15),

('css-selection', 'css', 'syntax', 79, '::selection', '?�택 ?�역 ?��???, 'challenge', 3,
'?�스???�택 ??배경?�을 ?��??�으�?변경하?�요.',
'- ::selection 가???�소\n- background-color',
'[{"input": "", "output": "?�택 ?��???}]',
'::selection {\n    /* ?�택 ?��???*/\n}',
'::selection {\n    background-color: yellow;\n    color: black;\n}',
'[{"input": "", "expected": "selection styled"}]',
'["::selection?� ?�용?��? ?�택???�스?�에 ?�용?�니??]',
ARRAY['pseudo-element', 'selection', 'hard'], 15),

('css-placeholder', 'css', 'syntax', 80, '::placeholder', '?�레?�스?�???��???, 'challenge', 3,
'input??placeholder ?�상???�색?�로 변경하?�요.',
'- ::placeholder 가???�소\n- color 변�?,
'[{"input": "", "output": "placeholder ?��???}]',
'input::placeholder {\n    /* placeholder ?�상 */\n}',
'input::placeholder {\n    color: gray;\n    opacity: 0.7;\n}',
'[{"input": "", "expected": "placeholder styled"}]',
'["::placeholder???�력 ?�트 ?�스?��? ?��??�링?�니??]',
ARRAY['pseudo-element', 'placeholder', 'hard'], 15);

-- Unit 17: 고급 ?�이?�웃 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('css-position-sticky', 'css', 'syntax', 81, 'Sticky ?�치', 'position: sticky', 'challenge', 3,
'?�크�????�더�??�단??고정?�세??',
'- position: sticky\n- top: 0',
'[{"input": "", "output": "고정 ?�더"}]',
'/* Code */
header {\n    /* sticky ?�치 */\n}',
'header {\n    position: sticky;\n    top: 0;\n    background: white;\n}',
'[{"input": "", "expected": "sticky header"}]',
'["sticky???�크롤에 ?�라 relative?� fixed ?�이�??�환?�니??]',
ARRAY['layout', 'position', 'sticky', 'hard'], 18),

('css-z-index', 'css', 'syntax', 82, '?�임 ?�서', 'z-index', 'challenge', 3,
'모달???�른 ?�소 ?�에 배치?�세??',
'- z-index: 1000\n- position ?�수',
'[{"input": "", "output": "최상??모달"}]',
'.modal {\n    position: fixed;\n    /* z-index ?�정 */\n}',
'.modal {\n    position: fixed;\n    z-index: 1000;\n}',
'[{"input": "", "expected": "high z-index"}]',
'["z-index??position??static???�닐 ?�만 ?�작?�니??]',
ARRAY['layout', 'z-index', 'hard'], 15),

('css-columns', 'css', 'syntax', 83, '?�단 ?�이?�웃', 'columns', 'challenge', 3,
'?�스?��? 3?�으�??�누?�요.',
'- columns: 3\n- column-gap ?�정',
'[{"input": "", "output": "3???�이?�웃"}]',
'.article {\n    /* 3???�이?�웃 */\n}',
'.article {\n    columns: 3;\n    column-gap: 2em;\n}',
'[{"input": "", "expected": "3 columns"}]',
'["columns???�문 ?��????�이?�웃??만듭?�다"]',
ARRAY['layout', 'columns', 'hard'], 18),

('css-aspect-ratio', 'css', 'syntax', 84, '종횡�?, 'aspect-ratio', 'challenge', 3,
'?�소??종횡비�? 16:9�??��??�세??',
'- aspect-ratio: 16 / 9\n- 비율 ?��?',
'[{"input": "", "output": "16:9 비율"}]',
'.video-container {\n    /* 16:9 비율 */\n}',
'.video-container {\n    aspect-ratio: 16 / 9;\n}',
'[{"input": "", "expected": "16:9 aspect ratio"}]',
'["aspect-ratio???�비??맞춰 ?�이�??�동 조정?�니??]',
ARRAY['layout', 'aspect-ratio', 'hard'], 18),

('css-object-fit', 'css', 'syntax', 85, '객체 맞춤', 'object-fit', 'challenge', 3,
'?��?지가 컨테?�너�?�?채우??비율???��??�세??',
'- object-fit: cover\n- 비율 ?��??�며 채우�?,
'[{"input": "", "output": "cover ?��?지"}]',
'/* Code */
img {\n    width: 100%;\n    height: 300px;\n    /* object-fit */\n}',
'img {\n    width: 100%;\n    height: 300px;\n    object-fit: cover;\n}',
'[{"input": "", "expected": "object-fit cover"}]',
'["contain, cover, fill, none, scale-down 값이 ?�습?�다"]',
ARRAY['layout', 'object-fit', 'hard'], 18);

-- Unit 18: 고급 ?�과 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('css-filter', 'css', 'syntax', 86, 'Filter ?�과', 'filter ?�성', 'challenge', 3,
'?��?지???�림 ?�과�?추�??�세??',
'- filter: blur(5px)\n- ?�각 ?�과',
'[{"input": "", "output": "?�림 ?��?지"}]',
'/* Code */
img {\n    /* ?�림 ?�과 */\n}',
'img {\n    filter: blur(5px);\n}',
'[{"input": "", "expected": "blur filter"}]',
'["blur, brightness, contrast, grayscale ???�양???�터가 ?�습?�다"]',
ARRAY['effects', 'filter', 'hard'], 18),

('css-backdrop-filter', 'css', 'syntax', 87, '배경 ?�터', 'backdrop-filter', 'challenge', 3,
'배경???�리�??�는 ?�리 ?�과�?만드?�요.',
'- backdrop-filter: blur(10px)\n- 배경 ?�과',
'[{"input": "", "output": "?�리 ?�과"}]',
'.glass {\n    /* 배경 ?�림 */\n}',
'.glass {\n    background: rgba(255, 255, 255, 0.5);\n    backdrop-filter: blur(10px);\n}',
'[{"input": "", "expected": "backdrop blur"}]',
'["backdrop-filter???�소 ?�의 배경???�과�??�용?�니??]',
ARRAY['effects', 'backdrop-filter', 'hard'], 20),

('css-text-shadow', 'css', 'syntax', 88, '?�스??그림??, 'text-shadow', 'challenge', 3,
'?�스?�에 그림?��? 추�??�세??',
'- text-shadow: x y blur color\n- ?�스???�과',
'[{"input": "", "output": "그림???�스??}]',
'h1 {\n    /* ?�스??그림??*/\n}',
'h1 {\n    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);\n}',
'[{"input": "", "expected": "text shadow"}]',
'["?�러 그림?��? ?�표�?구분?�여 추�??????�습?�다"]',
ARRAY['effects', 'text-shadow', 'hard'], 15),

('css-gradient', 'css', 'syntax', 89, '그라?�언??, 'linear-gradient', 'challenge', 3,
'?�형 그라?�언??배경??만드?�요.',
'- background: linear-gradient()\n- ?�상 ?�환',
'[{"input": "", "output": "그라?�언??배경"}]',
'.hero {\n    /* 그라?�언??배경 */\n}',
'.hero {\n    background: linear-gradient(to right, #667eea, #764ba2);\n}',
'[{"input": "", "expected": "gradient bg"}]',
'["linear-gradient, radial-gradient, conic-gradient가 ?�습?�다"]',
ARRAY['effects', 'gradient', 'hard'], 18),

('css-blend-mode', 'css', 'syntax', 90, '?�합 모드', 'mix-blend-mode', 'challenge', 3,
'?�소�?배경�??�합?�세??',
'- mix-blend-mode: multiply\n- ?�이???�합',
'[{"input": "", "output": "?�합 ?�과"}]',
'.overlay {\n    /* ?�합 모드 */\n}',
'.overlay {\n    mix-blend-mode: multiply;\n}',
'[{"input": "", "expected": "blend mode"}]',
'["multiply, screen, overlay, darken, lighten ?�이 ?�습?�다"]',
ARRAY['effects', 'blend-mode', 'hard'], 20);

-- Unit 19: 변?��? ?�수 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('css-variables', 'css', 'syntax', 91, 'CSS 변??, '커스?� ?�성', 'challenge', 3,
'CSS 변?�로 메인 ?�상???�의?�고 ?�용?�세??',
'- --변?�명: �?n- var(--변?�명) ?�용',
'[{"input": "", "output": "CSS 변??}]',
':root {\n    /* 변???�의 */\n}\n\n.button {\n    /* 변???�용 */\n}',
':root {\n    --primary-color: #007bff;\n}\n\n.button {\n    background-color: var(--primary-color);\n}',
'[{"input": "", "expected": "css variables"}]',
'[":root???�의?�면 ?�역?�서 ?�용?????�습?�다"]',
ARRAY['advanced', 'variables', 'hard'], 18),

('css-var-fallback', 'css', 'syntax', 92, '변???�백', 'var() 기본�?, 'challenge', 3,
'변?��? ?�을 ???�백 값을 지?�하?�요.',
'- var(--변?? ?�백�?\n- 기본�??�공',
'[{"input": "", "output": "?�백 �?}]',
'.element {\n    /* ?�백 ?�함 */\n}',
'.element {\n    color: var(--text-color, black);\n}',
'[{"input": "", "expected": "var with fallback"}]',
'["var()????번째 ?�자�??�백 값을 지?�합?�다"]',
ARRAY['advanced', 'variables', 'hard'], 18),

('css-min-max', 'css', 'syntax', 93, 'min/max ?�수', '최소/최�? �?, 'challenge', 3,
'?�비�?최소 300px, 최�? 50%�??�한?�세??',
'- min(), max() ?�수\n- �??�한',
'[{"input": "", "output": "min/max ?�한"}]',
'.container {\n    /* min/max ?�용 */\n}',
'.container {\n    width: min(50%, 600px);\n}',
'[{"input": "", "expected": "min width"}]',
'["min()?� 가???��? 값을, max()??가????값을 ?�택?�니??]',
ARRAY['advanced', 'functions', 'hard'], 20),

('css-attr', 'css', 'syntax', 94, 'attr() ?�수', '?�성 �??�용', 'challenge', 3,
'data ?�성??값을 content�??�시?�세??',
'- attr() ?�수\n- HTML ?�성 ?�근',
'[{"input": "", "output": "?�성 �??�시"}]',
'a::after {\n    /* data-label ?�시 */\n}',
'a::after {\n    content: " (" attr(data-label) ")";\n}',
'[{"input": "", "expected": "attr content"}]',
'["attr()�?HTML ?�성 값을 CSS?�서 ?�용?????�습?�다"]',
ARRAY['advanced', 'functions', 'hard'], 20),

('css-counter', 'css', 'syntax', 95, 'CSS 카운??, 'counter() ?�수', 'challenge', 3,
'?�션 번호�??�동?�로 매기?�요.',
'- counter-reset\n- counter-increment\n- counter()',
'[{"input": "", "output": "?�동 번호"}]',
'body {\n    /* 카운??리셋 */\n}\n\nsection::before {\n    /* 카운???�용 */\n}',
'body {\n    counter-reset: section;\n}\n\nsection {\n    counter-increment: section;\n}\n\nsection::before {\n    content: "Section " counter(section) ": ";\n}',
'[{"input": "", "expected": "counter numbering"}]',
'["CSS 카운?�로 ?�동 번호 매기기�? 구현?????�습?�다"]',
ARRAY['advanced', 'counter', 'hard'], 25);

-- Unit 20: 최신 CSS (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('css-subgrid', 'css', 'syntax', 96, 'Subgrid', '중첩 그리???�렬', 'challenge', 3,
'?�식 그리?��? 부�?그리???�인???�르�??�세??',
'- grid-template-columns: subgrid\n- 부�?그리???�속',
'[{"input": "", "output": "subgrid"}]',
'.child {\n    display: grid;\n    /* subgrid ?�용 */\n}',
'.child {\n    display: grid;\n    grid-template-columns: subgrid;\n}',
'[{"input": "", "expected": "subgrid layout"}]',
'["subgrid???�식??부모의 그리???�랙???�속?�니??]',
ARRAY['modern', 'grid', 'subgrid', 'hard'], 25),

('css-is-where', 'css', 'syntax', 97, ':is()?� :where()', '?�택??목록', 'challenge', 3,
':is()�??�러 ?�택?��? 간결?�게 ?�성?�세??',
'- :is() 가???�래??n- ?�택??그룹??,
'[{"input": "", "output": "is selector"}]',
'/* h1, h2, h3??a�??�택 */\n',
':is(h1, h2, h3) a {\n    color: blue;\n}',
'[{"input": "", "expected": "is selector"}]',
'[":is()??명시?��? 가지지�?:where()??명시?��? 0?�니??]',
ARRAY['modern', 'selector', 'is', 'hard'], 20),

('css-has', 'css', 'syntax', 98, ':has() ?�택??, '부�??�택??, 'challenge', 3,
'?��?지가 ?�는 article???�택?�세??',
'- :has() 가???�래??n- ?�식 기�? 부�??�택',
'[{"input": "", "output": "has selector"}]',
'',
'article:has(img) {\n    border: 2px solid blue;\n}',
'[{"input": "", "expected": "has img selector"}]',
'[":has()??부�??�택?�로, ?�정 ?�식??가�??�소�??�택?�니??]',
ARRAY['modern', 'selector', 'has', 'hard'], 25),

('css-scroll-snap', 'css', 'syntax', 99, 'Scroll Snap', '?�크�??�냅', 'challenge', 3,
'?�크�????�션???�냅?�게 ?�세??',
'- scroll-snap-type\n- scroll-snap-align',
'[{"input": "", "output": "scroll snap"}]',
'.container {\n    /* scroll snap container */\n}\n\n.section {\n    /* snap point */\n}',
'.container {\n    scroll-snap-type: y mandatory;\n    overflow-y: scroll;\n}\n\n.section {\n    scroll-snap-align: start;\n}',
'[{"input": "", "expected": "scroll snap"}]',
'["scroll-snap?� ?� ?�이지 ?�크롤이??캐러?�???�용?�니??]',
ARRAY['modern', 'scroll', 'hard'], 25),

('css-layer', 'css', 'syntax', 100, '@layer', '?�이???�서', 'challenge', 3,
'CSS ?�이?�로 명시?��? 관리하?�요.',
'- @layer 규칙\n- ?�이???�서 ?�의',
'[{"input": "", "output": "cascade layers"}]',
'/* ?�이???�의 */\n',
'@layer reset, base, components;\n\n@layer reset {\n    * { margin: 0; }\n}\n\n@layer base {\n    body { font-family: sans-serif; }\n}',
'[{"input": "", "expected": "layer defined"}]',
'["@layer??명시???�???�서�??�선?�위�?관리합?�다"]',
ARRAY['modern', 'layer', 'hard'], 25);

-- ====================================
-- ?�료 메시지
-- ====================================


