-- ====================================
-- HTML Language Challenges - Part 2
-- Levels 51-100 (MEDIUM 30�?+ HARD 20�?
-- ====================================

-- Unit 11: 멀?��??�어 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-video', 'html', 'syntax', 51, 'video ?�그', '비디???�입', 'challenge', 2,
'controls?� ?�러 ?�스�?가�?비디?��? ?�입?�세??',
'- <video> ?�그\n- controls, width, height\n- ?�러 source ?�그',
'[{"input": "", "output": "비디???�레?�어"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- video ?�그�?추�??�세??-->\n</body>\n</html>',
'',
'[{"input": "", "expected": "video with controls"}]',
'["?�러 ?�맷???�공?�면 브라?��?가 지?�하??것을 ?�택?�니??]',
ARRAY['multimedia', 'video'], 10),

('html-audio', 'html', 'syntax', 52, 'audio ?�그', '?�디???�입', 'challenge', 2,
'autoplay?� loop가 ?�는 ?�디?��? ?�입?�세??',
'- <audio> ?�그\n- controls, autoplay, loop',
'[{"input": "", "output": "?�디???�레?�어"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- audio ?�그 추�? -->\n</body>\n</html>',
'',
'[{"input": "", "expected": "audio with autoplay"}]',
'["autoplay???�용??경험???�중???�용?�야 ?�니??]',
ARRAY['multimedia', 'audio'], 10),

('html-iframe', 'html', 'syntax', 53, 'iframe', '?��? 콘텐�??�베??, 'challenge', 2,
'YouTube 비디?��? iframe?�로 ?�입?�세??',
'- <iframe> ?�그\n- src, width, height\n- frameborder, allowfullscreen',
'[{"input": "", "output": "?�베?�드 비디??}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- YouTube iframe 추�? -->\n</body>\n</html>',
'',
'[{"input": "", "expected": "youtube iframe"}]',
'["iframe?� ?�른 HTML ?�이지�??�입?????�습?�다"]',
ARRAY['multimedia', 'iframe'], 12),

('html-figure-figcaption', 'html', 'syntax', 54, 'figure?� figcaption', '?��?지 캡션', 'challenge', 2,
'?��?지??캡션??추�??�세??',
'- <figure> ?�그\n- <figcaption> ?�명',
'[{"input": "", "output": "캡션 ?�는 ?��?지"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <img src="photo.jpg" alt="Photo">\n    <p>Photo description</p>\n</body>\n</html>',
'',
'[{"input": "", "expected": "figure with figcaption"}]',
'["figure???��?지, ?�이?�그?? 코드 ?�을 감쌉?�다"]',
ARRAY['multimedia', 'figure'], 10),

('html-picture', 'html', 'syntax', 55, 'picture ?�그', '반응???��?지', 'challenge', 2,
'?�면 ?�기???�라 ?�른 ?��?지�?보여주세??',
'- <picture> ?�그\n- <source> media 쿼리\n- <img> ?�백',
'[{"input": "", "output": "반응???��?지"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- picture ?�그�?반응???��?지 -->\n</body>\n</html>',
'',
'[{"input": "", "expected": "responsive picture"}]',
'["picture???�트 ?�렉?�과 ?�상???�환???�용?�니??]',
ARRAY['multimedia', 'picture', 'responsive'], 15);

-- Unit 12: 고급 ??(5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-input-range', 'html', 'syntax', 56, '범위 ?�라?�더', 'input type=range', 'challenge', 2,
'0-100 범위???�라?�더�?만드?�요.',
'- type="range"\n- min, max, value, step',
'[{"input": "", "output": "?�라?�더"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <label>Volume:</label>\n    <!-- range input -->\n</body>\n</html>',
'',
'[{"input": "", "expected": "range slider"}]',
'["step?�로 증�? ?�위�?조절?????�습?�다"]',
ARRAY['form', 'input', 'range'], 10),

('html-input-color', 'html', 'syntax', 57, '?�상 ?�택', 'input type=color', 'challenge', 2,
'?�상 ?�택기�? 만드?�요.',
'- type="color"\n- value??hex ?�상',
'[{"input": "", "output": "?�상 ?�택�?}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <label>Pick a color:</label>\n    <!-- color input -->\n</body>\n</html>',
'',
'[{"input": "", "expected": "color picker"}]',
'["color ?�?��? ?�상 ?�택 UI�??�공?�니??]',
ARRAY['form', 'input', 'color'], 10),

('html-datalist', 'html', 'syntax', 58, 'datalist', '?�동?�성 목록', 'challenge', 2,
'?�동?�성???�는 ?�력 ?�드�?만드?�요.',
'- <datalist> ?�그\n- input??list ?�성�??�결',
'[{"input": "", "output": "?�동?�성"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <input type="text" name="browser">\n</body>\n</html>',
'',
'[{"input": "", "expected": "input with datalist"}]',
'["datalist??추천 ?�션???�공?��?�??�른 값도 ?�력 가?�합?�다"]',
ARRAY['form', 'datalist'], 12),

('html-input-file', 'html', 'syntax', 59, '?�일 ?�로??, 'input type=file', 'challenge', 2,
'?�러 ?��?지 ?�일???�로?�할 ???�는 ?�력??만드?�요.',
'- type="file"\n- accept, multiple ?�성',
'[{"input": "", "output": "?�일 ?�택"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Upload images:</label>\n        <!-- file input -->\n    </form>\n</body>\n</html>',
'',
'[{"input": "", "expected": "file input with accept"}]',
'["accept�??�일 ?�형?? multiple�??�러 ?�일 ?�택???�용?�니??]',
ARRAY['form', 'input', 'file'], 10),

('html-input-search', 'html', 'syntax', 60, '검???�력', 'input type=search', 'challenge', 2,
'검?�창??만드?�요.',
'- type="search"\n- placeholder, autocomplete',
'[{"input": "", "output": "검?�창"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <!-- search input -->\n    </form>\n</body>\n</html>',
'',
'[{"input": "", "expected": "search input"}]',
'["search ?�?��? 검???�도�?명시?�고 X 버튼???�공?�니??]',
ARRAY['form', 'input', 'search'], 10);

-- Unit 13: ???�효??검??(5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-required', 'html', 'syntax', 61, '?�수 ?�력', 'required ?�성', 'challenge', 2,
'?�수 ?�력 ?�드�?만드?�요.',
'- required ?�성\n- ?�출 ???�동 검�?,
'[{"input": "", "output": "?�수 ?�드"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="text" name="name">\n        <button type="submit">Submit</button>\n    </form>\n</body>\n</html>',
'',
'[{"input": "", "expected": "required field"}]',
'["required ?�드가 비어?�으�????�출??차단?�니??]',
ARRAY['form', 'validation', 'required'], 8),

('html-pattern', 'html', 'syntax', 62, '?�규??검�?, 'pattern ?�성', 'challenge', 2,
'?�화번호 ?�식???�규?�으�?검증하?�요.',
'- pattern ?�성\n- ?�규???�용',
'[{"input": "", "output": "?�턴 검�?}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="tel" name="phone">\n    </form>\n</body>\n</html>',
'',
'[{"input": "", "expected": "phone pattern"}]',
'["pattern?�로 ?�력 ?�식???�한?????�습?�다"]',
ARRAY['form', 'validation', 'pattern'], 12),

('html-minlength-maxlength', 'html', 'syntax', 63, '길이 ?�한', 'minlength, maxlength', 'challenge', 2,
'비�?번호 길이�?8-20?�로 ?�한?�세??',
'- minlength, maxlength ?�성\n- 문자??길이 검�?,
'[{"input": "", "output": "길이 ?�한"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="password" name="password">\n    </form>\n</body>\n</html>',
'',
'[{"input": "", "expected": "length restriction"}]',
'["minlength?� maxlength�??�력 길이�??�한?�니??]',
ARRAY['form', 'validation', 'length'], 10),

('html-min-max', 'html', 'syntax', 64, '�?범위 ?�한', 'min, max', 'challenge', 2,
'?�짜�??�늘 ?�후로만 ?�택 가?�하�??�세??',
'- min ?�성???�늘 ?�짜\n- 과거 ?�짜 ?�택 불�?',
'[{"input": "", "output": "?�짜 범위 ?�한"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="date" name="appointment">\n    </form>\n</body>\n</html>',
'',
'[{"input": "", "expected": "date min"}]',
'["min�?max�??�짜/?�자 범위�??�한?�니??]',
ARRAY['form', 'validation', 'min-max'], 10),

('html-novalidate', 'html', 'syntax', 65, '?�효??검??비활?�화', 'novalidate', 'challenge', 2,
'?�의 HTML5 ?�효??검?��? 비활?�화?�세??',
'- novalidate ?�성\n- form ?�그??추�?',
'[{"input": "", "output": "검�?비활?�화"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <form action="/submit">\n        <input type="email" required>\n        <button type="submit">Submit</button>\n    </form>\n</body>\n</html>',
'',
'[{"input": "", "expected": "novalidate form"}]',
'["novalidate??커스?� 검증을 ?�용?????�용?�니??]',
ARRAY['form', 'validation', 'novalidate'], 8);

-- Unit 14: 메�? ?�그?� SEO (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-meta-description', 'html', 'syntax', 66, '?�이지 ?�명', 'meta description', 'challenge', 2,
'검?�엔진용 ?�이지 ?�명??추�??�세??',
'- meta name="description"\n- content ?�성',
'[{"input": "", "output": "SEO ?�명"}]',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>',
'',
'[{"input": "", "expected": "meta description"}]',
'["description?� 검??결과???�시?�니??]',
ARRAY['meta', 'seo'], 8),

('html-meta-keywords', 'html', 'syntax', 67, '?�워??, 'meta keywords', 'challenge', 2,
'?�이지 ?�워?��? 추�??�세??',
'- meta name="keywords"\n- ?�표�?구분',
'[{"input": "", "output": "?�워??}]',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>',
'',
'[{"input": "", "expected": "meta keywords"}]',
'["keywords???��? SEO?�서 중요?��? ??��졌습?�다"]',
ARRAY['meta', 'seo'], 8),

('html-meta-author', 'html', 'syntax', 68, '?�???�보', 'meta author', 'challenge', 2,
'?�이지 ?�???�보�?추�??�세??',
'- meta name="author"\n- ?�???�름',
'[{"input": "", "output": "?�???�보"}]',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>',
'',
'[{"input": "", "expected": "meta author"}]',
'["author 메�? ?�그??콘텐�??�작?��? 명시?�니??]',
ARRAY['meta', 'author'], 8),

('html-og-tags', 'html', 'syntax', 69, 'Open Graph ?�그', 'SNS 공유 메�??�이??, 'challenge', 2,
'?�이?�북/SNS 공유??Open Graph ?�그�?추�??�세??',
'- og:title, og:description, og:image\n- property ?�성 ?�용',
'[{"input": "", "output": "OG ?�그"}]',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>',
'',
'[{"input": "", "expected": "og tags"}]',
'["Open Graph??SNS 공유 ???�시?�는 ?�보�??�어?�니??]',
ARRAY['meta', 'og', 'social'], 15),

('html-twitter-card', 'html', 'syntax', 70, 'Twitter Card', '?�위??카드 메�??�이??, 'challenge', 2,
'?�위??카드 메�? ?�그�?추�??�세??',
'- twitter:card, twitter:title, twitter:description\n- name ?�성 ?�용',
'[{"input": "", "output": "?�위??카드"}]',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>',
'',
'[{"input": "", "expected": "twitter card"}]',
'["Twitter Card???�윗?�서 리치 미디???�시�??�공?�니??]',
ARRAY['meta', 'twitter', 'social'], 15);

-- Unit 15: ?�맨??고급 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-aside', 'html', 'syntax', 71, 'aside ?�그', '?�이?�바 콘텐�?, 'challenge', 2,
'메인 콘텐츠�? 별개???�이??콘텐츠�? 만드?�요.',
'- <aside> ?�그\n- 관??링크, 광고 ??,
'[{"input": "", "output": "?�이?�바"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <main>\n        <h1>Main Content</h1>\n    </main>\n    <!-- aside 추�? -->\n</body>\n</html>',
'',
'[{"input": "", "expected": "aside element"}]',
'["aside??메인 콘텐츠�? 간접?�으�?관?�된 ?�용?�니??]',
ARRAY['semantic', 'aside'], 10),

('html-time', 'html', 'syntax', 72, 'time ?�그', '?�짜/?�간 ?�시', 'challenge', 2,
'기계가 ?�을 ???�는 ?�간 ?�보�?추�??�세??',
'- <time> ?�그\n- datetime ?�성',
'[{"input": "", "output": "?�간 ?�보"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <p>Published: January 1, 2024</p>\n</body>\n</html>',
'',
'[{"input": "", "expected": "time with datetime"}]',
'["datetime ?�성?� 기계가 ?�을 ???�는 ?�식?�니??]',
ARRAY['semantic', 'time'], 10),

('html-address', 'html', 'syntax', 73, 'address ?�그', '?�락�??�보', 'challenge', 2,
'?�?�나 조직???�락�??�보�?추�??�세??',
'- <address> ?�그\n- ?�메?? 주소 ??,
'[{"input": "", "output": "?�락�?}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <footer>\n        <!-- address ?�보 -->\n    </footer>\n</body>\n</html>',
'',
'[{"input": "", "expected": "address element"}]',
'["address???�락�??�보�??��??�니??]',
ARRAY['semantic', 'address'], 10),

('html-details-summary', 'html', 'syntax', 74, 'details?� summary', '?�을 ???�는 콘텐�?, 'challenge', 2,
'?�릭?�면 ?�쳐지???�세 ?�보�?만드?�요.',
'- <details> ?�그\n- <summary> ?�목',
'[{"input": "", "output": "?�기/?�치�?}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- details/summary 추�? -->\n</body>\n</html>',
'',
'[{"input": "", "expected": "details with summary"}]',
'["details??JavaScript ?�이 ?�기/?�치기�? ?�공?�니??]',
ARRAY['semantic', 'details', 'interactive'], 12),

('html-dialog', 'html', 'syntax', 75, 'dialog ?�그', '?�?�상??, 'challenge', 2,
'모달 ?�?�상?��? 만드?�요.',
'- <dialog> ?�그\n- open ?�성?�로 ?�시',
'[{"input": "", "output": "?�?�상??}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- dialog 추�? -->\n</body>\n</html>',
'',
'[{"input": "", "expected": "dialog element"}]',
'["dialog??JavaScript�?showModal()???�출?�여 ?�용?�니??]',
ARRAY['semantic', 'dialog', 'interactive'], 12);

-- Unit 16: ?�근??(5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-aria-label', 'html', 'syntax', 76, 'ARIA ?�벨', 'aria-label ?�성', 'challenge', 3,
'?�크�?리더�??�한 ARIA ?�벨??추�??�세??',
'- aria-label ?�성\n- ?�각???�스?��? ?�는 ?�소',
'[{"input": "", "output": "?�근 가?�한 버튼"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <button>??/button>\n</body>\n</html>',
'',
'[{"input": "", "expected": "aria-label"}]',
'["?�이�?버튼?�는 aria-label???�수?�니??]',
ARRAY['accessibility', 'aria', 'hard'], 12),

('html-aria-labelledby', 'html', 'syntax', 77, 'ARIA labelledby', '?�른 ?�소�??�벨�?, 'challenge', 3,
'aria-labelledby�??�소�??�른 ?�소?� ?�결?�세??',
'- aria-labelledby ?�성\n- id�?참조',
'[{"input": "", "output": "?�결???�벨"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <h2 id="dialog-title">Confirmation</h2>\n    <div>Are you sure?</div>\n</body>\n</html>',
'',
'[{"input": "", "expected": "aria-labelledby"}]',
'["aria-labelledby???�러 ?�소�?공백?�로 구분?�여 참조?????�습?�다"]',
ARRAY['accessibility', 'aria', 'hard'], 15),

('html-role', 'html', 'syntax', 78, 'ARIA role', '??�� ?�의', 'challenge', 3,
'커스?� ?�젯???�절??ARIA role??부?�하?�요.',
'- role ?�성\n- navigation, button, tablist ??,
'[{"input": "", "output": "??��???�는 ?�소"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <div>\n        <a href="#home">Home</a>\n        <a href="#about">About</a>\n    </div>\n</body>\n</html>',
'',
'[{"input": "", "expected": "navigation role"}]',
'["?�맨???�그�??�용?????�을 ??role???�용?�니??]',
ARRAY['accessibility', 'aria', 'role', 'hard'], 15),

('html-tabindex', 'html', 'syntax', 79, 'tabindex', '?�보???�색 ?�서', 'challenge', 3,
'?�보???�색 ?�서�?지?�하?�요.',
'- tabindex ?�성\n- 0: ?�연?�러???�서, -1: ?�커??불�??? 1+: ?�선?�위',
'[{"input": "", "output": "???�서"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <button>First</button>\n    <div>Important Content</div>\n    <button>Second</button>\n</body>\n</html>',
'',
'[{"input": "", "expected": "tabindex set"}]',
'["tabindex=0?� ?�연?�러???�서�??�커??가?�하�??�니??]',
ARRAY['accessibility', 'tabindex', 'hard'], 15),

('html-skip-link', 'html', 'syntax', 80, '?�킵 ?�비게이??, '본문?�로 바로가�?, 'challenge', 3,
'?�보???�용?��? ?�한 ?�킵 링크�?추�??�세??',
'- ?�이지 최상?�에 배치\n- 메인 콘텐츠로 ?�프',
'[{"input": "", "output": "?�킵 링크"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <header>...</header>\n    <nav>...</nav>\n    <main id="main-content">...</main>\n</body>\n</html>',
'',
'[{"input": "", "expected": "skip link"}]',
'["?�킵 링크??보통 CSS�??�기�??�커?????�시?�니??]',
ARRAY['accessibility', 'skip-link', 'hard'], 18);

-- Unit 17: ?��? 리소??(5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-link-stylesheet', 'html', 'syntax', 81, '?��??�시??링크', 'link ?�그�?CSS ?�결', 'challenge', 3,
'?��? CSS ?�일???�결?�세??',
'- <link> ?�그\n- rel="stylesheet"',
'[{"input": "", "output": "CSS ?�결"}]',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>',
'',
'[{"input": "", "expected": "stylesheet link"}]',
'["link ?�그??head ?�에 ?�치?�니??]',
ARRAY['resources', 'css', 'hard'], 10),

('html-script-tag', 'html', 'syntax', 82, 'script ?�그', 'JavaScript ?�결', 'challenge', 3,
'?��? JavaScript ?�일??defer�?로드?�세??',
'- <script> ?�그\n- defer ?�성',
'[{"input": "", "output": "JS ?�결"}]',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>',
'',
'[{"input": "", "expected": "script with defer"}]',
'["defer??HTML ?�싱 ???�크립트�??�행?�니??]',
ARRAY['resources', 'javascript', 'hard'], 12),

('html-link-preload', 'html', 'syntax', 83, 'preload', '리소??미리 로드', 'challenge', 3,
'중요???�트�?preload?�세??',
'- link rel="preload"\n- as ?�성?�로 ?�??지??,
'[{"input": "", "output": "preload"}]',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>',
'',
'[{"input": "", "expected": "preload font"}]',
'["preload???�이지 로딩 ?�능??최적?�합?�다"]',
ARRAY['resources', 'preload', 'performance', 'hard'], 18),

('html-link-prefetch', 'html', 'syntax', 84, 'prefetch', '?�후 리소??미리 가?�오�?, 'challenge', 3,
'?�음 ?�이지??리소?��? prefetch?�세??',
'- link rel="prefetch"\n- ??? ?�선?�위�?로드',
'[{"input": "", "output": "prefetch"}]',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>',
'',
'[{"input": "", "expected": "prefetch link"}]',
'["prefetch???�용?��? �?방문???�이지�?미리 로드?�니??]',
ARRAY['resources', 'prefetch', 'performance', 'hard'], 18),

('html-link-dns-prefetch', 'html', 'syntax', 85, 'DNS prefetch', 'DNS 미리 조회', 'challenge', 3,
'?��? ?�메?�의 DNS�?미리 조회?�세??',
'- link rel="dns-prefetch"\n- ?��? 리소???�메??,
'[{"input": "", "output": "dns-prefetch"}]',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My Page</title>\n</head>\n<body></body>\n</html>',
'',
'[{"input": "", "expected": "dns-prefetch"}]',
'["dns-prefetch???��? 리소??로딩 ?�간???�축?�니??]',
ARRAY['resources', 'dns-prefetch', 'performance', 'hard'], 18);

-- Unit 18: 고급 ?�이�?(5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-table-thead-tbody', 'html', 'syntax', 86, '?�이�?구조??, 'thead, tbody, tfoot', 'challenge', 3,
'?�이블을 ?�더, 본문, ?�터�?구조?�하?�요.',
'- <thead> ?�더 그룹\n- <tbody> 본문 그룹\n- <tfoot> ?�터 그룹',
'[{"input": "", "output": "구조?�된 ?�이�?}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr><th>Name</th><th>Score</th></tr>\n        <tr><td>John</td><td>90</td></tr>\n        <tr><td>Total</td><td>90</td></tr>\n    </table>\n</body>\n</html>',
'',
'[{"input": "", "expected": "table with thead tbody tfoot"}]',
'["thead, tbody, tfoot?�로 ?�이블을 ?��??�으�?구분?�니??]',
ARRAY['table', 'structure', 'hard'], 15),

('html-table-colgroup', 'html', 'syntax', 87, '컬럼 그룹', 'colgroup�?col', 'challenge', 3,
'컬럼 ?�위�??��??�을 ?�용?�세??',
'- <colgroup> ?�그\n- <col> �?컬럼',
'[{"input": "", "output": "컬럼 그룹"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr><th>A</th><th>B</th><th>C</th></tr>\n        <tr><td>1</td><td>2</td><td>3</td></tr>\n    </table>\n</body>\n</html>',
'',
'[{"input": "", "expected": "colgroup with styles"}]',
'["colgroup?� 컬럼 ?�위 ?��??�링??가?�하�??�니??]',
ARRAY['table', 'colgroup', 'hard'], 18),

('html-table-caption', 'html', 'syntax', 88, '?�이�?캡션', 'caption ?�그', 'challenge', 3,
'?�이블에 ?�목??추�??�세??',
'- <caption> ?�그\n- table 바로 ?�음',
'[{"input": "", "output": "캡션 ?�는 ?�이�?}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr><th>Name</th><th>Age</th></tr>\n        <tr><td>John</td><td>30</td></tr>\n    </table>\n</body>\n</html>',
'',
'[{"input": "", "expected": "table with caption"}]',
'["caption?� ?�이블의 ?�목/?�명???�공?�니??]',
ARRAY['table', 'caption', 'hard'], 12),

('html-table-scope', 'html', 'syntax', 89, 'scope ?�성', '?�더 범위 지??, 'challenge', 3,
'th ?�그??scope�?지?�하???�근?�을 개선?�세??',
'- scope="col" ?�는 "row"\n- ?�더가 ?�용?�는 범위',
'[{"input": "", "output": "scope ?�성"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr><th>Name</th><th>Math</th><th>English</th></tr>\n        <tr><th>John</th><td>90</td><td>85</td></tr>\n    </table>\n</body>\n</html>',
'',
'[{"input": "", "expected": "th with scope"}]',
'["scope???�크�?리더가 ?�이블을 ?�해?�는 ???��???줍니??]',
ARRAY['table', 'scope', 'accessibility', 'hard'], 18),

('html-table-complex', 'html', 'syntax', 90, '복잡???�이�?, '모든 기능 ?�용', 'challenge', 3,
'thead, tbody, colspan, rowspan??모두 ?�용??복잡???�이블을 만드?�요.',
'- 모든 ?�이�?기능 ?�용\n- 구조?�된 ?�이?�웃',
'[{"input": "", "output": "복잡???�이�?}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- 복잡???�이�??�성 -->\n</body>\n</html>',
'',
'[{"input": "", "expected": "complex table structure"}]',
'["복잡???�이블�? caption, scope ?�으�??�근?�을 ?�보?�야 ?�니??]',
ARRAY['table', 'complex', 'hard'], 25);

-- Unit 19: Canvas?� SVG (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-canvas-basic', 'html', 'syntax', 91, 'canvas ?�그', '캔버???�성', 'challenge', 3,
'그래?�을 그릴 canvas ?�소�?만드?�요.',
'- <canvas> ?�그\n- width, height ?�성',
'[{"input": "", "output": "캔버??}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- canvas 추�? -->\n</body>\n</html>',
'',
'[{"input": "", "expected": "canvas element"}]',
'["canvas??JavaScript�?그래?�을 그립?�다"]',
ARRAY['graphics', 'canvas', 'hard'], 12),

('html-svg-inline', 'html', 'syntax', 92, 'inline SVG', 'SVG 코드 ?�입', 'challenge', 3,
'?�라??SVG�??�을 그리?�요.',
'- <svg> ?�그\n- <circle> ?�소',
'[{"input": "", "output": "SVG ??}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- SVG ??그리�?-->\n</body>\n</html>',
'',
'[{"input": "", "expected": "svg circle"}]',
'["SVG??벡터 그래?�으�??��??�도 깨�?지 ?�습?�다"]',
ARRAY['graphics', 'svg', 'hard'], 15),

('html-svg-path', 'html', 'syntax', 93, 'SVG path', '복잡???�형', 'challenge', 3,
'SVG path�??�각?�을 그리?�요.',
'- <path> ?�소\n- d ?�성??경로 ?�이??,
'[{"input": "", "output": "SVG ?�각??}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <svg width="100" height="100">\n        <!-- path�??�각??-->\n    </svg>\n</body>\n</html>',
'',
'[{"input": "", "expected": "svg triangle"}]',
'["M?� ?�동, L?� ??그리�? Z??경로 ?�기?�니??]',
ARRAY['graphics', 'svg', 'path', 'hard'], 20),

('html-svg-text', 'html', 'syntax', 94, 'SVG ?�스??, 'SVG???�스??추�?', 'challenge', 3,
'SVG ?�에 ?��??�이 ?�용???�스?��? 추�??�세??',
'- <text> ?�소\n- x, y, fill, font-size',
'[{"input": "", "output": "SVG ?�스??}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <svg width="200" height="100">\n        <!-- text 추�? -->\n    </svg>\n</body>\n</html>',
'',
'[{"input": "", "expected": "svg text"}]',
'["SVG ?�스?�는 벡터?��?�??��?/축소가 ?�유�?��?�다"]',
ARRAY['graphics', 'svg', 'text', 'hard'], 15),

('html-svg-animation', 'html', 'syntax', 95, 'SVG ?�니메이??, 'animate ?�소', 'challenge', 3,
'SVG ?�소???�니메이?�을 추�??�세??',
'- <animate> ?�소\n- attributeName, from, to, dur',
'[{"input": "", "output": "?�니메이??SVG"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <svg width="100" height="100">\n        <circle cx="50" cy="50" r="20" fill="green" />\n    </svg>\n</body>\n</html>',
'',
'[{"input": "", "expected": "animated svg"}]',
'["SVG??SMIL ?�니메이?�을 지?�합?�다"]',
ARRAY['graphics', 'svg', 'animation', 'hard'], 20);

-- Unit 20: 고급 기능 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-data-attributes', 'html', 'syntax', 96, 'data ?�성', '커스?� ?�이???�성', 'challenge', 3,
'?�소??커스?� ?�이?��? ?�?�하?�요.',
'- data-* ?�성\n- JavaScript?�서 ?�근 가??,
'[{"input": "", "output": "data ?�성"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <div>Product: Laptop</div>\n</body>\n</html>',
'',
'[{"input": "", "expected": "data attributes"}]',
'["data-* ?�성?� JavaScript dataset?�로 ?�근?�니??]',
ARRAY['advanced', 'data-attributes', 'hard'], 15),

('html-contenteditable', 'html', 'syntax', 97, 'contenteditable', '?�집 가?�한 콘텐�?, 'challenge', 3,
'?�용?��? ?�집?????�는 ?�소�?만드?�요.',
'- contenteditable="true"\n- div, p ?�에 ?�용',
'[{"input": "", "output": "?�집 가???�역"}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <div>Edit this text</div>\n</body>\n</html>',
'',
'[{"input": "", "expected": "contenteditable div"}]',
'["contenteditable?� 간단???�디?��? 만들 ???�용?�니??]',
ARRAY['advanced', 'contenteditable', 'hard'], 15),

('html-draggable', 'html', 'syntax', 98, 'draggable', '?�래�?가?�한 ?�소', 'challenge', 3,
'?�래�????�롭??가?�한 ?�소�?만드?�요.',
'- draggable="true"\n- ondragstart ?�벤??,
'[{"input": "", "output": "?�래�?가??}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <div id="item">Drag me</div>\n</body>\n</html>',
'',
'[{"input": "", "expected": "draggable element"}]',
'["draggable?� drag & drop API?� ?�께 ?�용?�니??]',
ARRAY['advanced', 'draggable', 'hard'], 18),

('html-progress', 'html', 'syntax', 99, 'progress �?, '진행�??�시', 'challenge', 3,
'진행률을 ?��??�는 progress 바�? 만드?�요.',
'- <progress> ?�그\n- value, max ?�성',
'[{"input": "", "output": "진행�?�?}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- progress �?-->\n</body>\n</html>',
'',
'[{"input": "", "expected": "progress bar"}]',
'["progress???�업 진행률을 ?�각?�으�??�시?�니??]',
ARRAY['advanced', 'progress', 'hard'], 12),

('html-template', 'html', 'syntax', 100, 'template ?�그', 'HTML ?�플�?, 'challenge', 3,
'?�사??가?�한 HTML ?�플릿을 만드?�요.',
'- <template> ?�그\n- JavaScript�?복제?�여 ?�용',
'[{"input": "", "output": "?�플�?}]',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- template 추�? -->\n</body>\n</html>',
'',
'[{"input": "", "expected": "template element"}]',
'["template ?�용?� ?�더링되지 ?�고 JavaScript�?복제?�니??]',
ARRAY['advanced', 'template', 'hard'], 18);

-- ====================================
-- ?�료 메시지
-- ====================================


