-- ====================================
-- HTML Language Challenges - Part 1
-- Levels 1-50 (EASY 50�?
-- ====================================

-- Unit 1: 기본 구조 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-basic-structure', 'html', 'syntax', 1, '기본 HTML 문서', '�?HTML 문서 ?�성?�기', 'challenge', 1,
'가??기본?�인 HTML 문서 구조�??�성?�세??',
'- <!DOCTYPE html> ?�언\n- html, head, body ?�그 ?�용',
'[{"input": "", "output": "기본 HTML 구조"}]',
'<!-- HTML 기본 구조�??�성?�세??-->\n',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My First Page</title>\n</head>\n<body>\n    <h1>Hello, World!</h1>\n</body>\n</html>',
'[{"input": "", "expected": "valid html structure"}]',
'["DOCTYPE?� HTML5�??��??�니??, "html ?�그가 모든 것을 감싸???�니??]',
ARRAY['basics', 'structure'], 5),

('html-title-tag', 'html', 'syntax', 2, '?�이지 ?�목', 'title ?�그 ?�용', 'challenge', 1,
'?�이지 ?�목??"My Website"�??�정?�세??',
'- <title> ?�그??head ?�에\n- 브라?��? ??�� ?�시?�는 ?�목',
'[{"input": "", "output": "?�이지 ?�목 ?�정"}]',
'',
'<!DOCTYPE html>\n<html>\n<head>\n    <title>My Website</title>\n</head>\n<body>\n</body>\n</html>',
'[{"input": "", "expected": "title is My Website"}]',
'["title ?�그??head ?�션???�치?�니??]',
ARRAY['basics', 'title'], 5),

('html-meta-charset', 'html', 'syntax', 3, '문자 ?�코??, 'meta charset ?�정', 'challenge', 1,
'UTF-8 문자 ?�코?�을 ?�정?�세??',
'- <meta charset="UTF-8">\n- head ?�그 ?�에 ?�치',
'[{"input": "", "output": "UTF-8 ?�코???�정"}]',
'',
'<!DOCTYPE html>\n<html>\n<head>\n    <meta charset="UTF-8">\n</head>\n<body>\n</body>\n</html>',
'[{"input": "", "expected": "charset utf-8"}]',
'["meta ?�그??self-closing?�니??]',
ARRAY['basics', 'meta'], 5),

('html-viewport', 'html', 'syntax', 4, '뷰포???�정', '반응??메�? ?�그', 'challenge', 1,
'반응???�을 ?�한 viewport 메�? ?�그�?추�??�세??',
'- name="viewport"\n- content="width=device-width, initial-scale=1.0"',
'[{"input": "", "output": "viewport ?�정"}]',
'',
'<!DOCTYPE html>\n<html>\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n</head>\n<body>\n</body>\n</html>',
'[{"input": "", "expected": "responsive viewport"}]',
'["viewport??모바??반응?�에 ?�수?�니??]',
ARRAY['basics', 'viewport', 'responsive'], 5),

('html-comment', 'html', 'syntax', 5, 'HTML 주석', '주석 ?�성?�기', 'challenge', 1,
'"This is a comment"?�는 주석??추�??�세??',
'- <!-- 주석 ?�용 -->\n- 브라?��????�시?��? ?�음',
'[{"input": "", "output": "주석 추�?"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <!-- This is a comment -->\n</body>\n</html>',
'[{"input": "", "expected": "comment exists"}]',
'["주석?� <!-- �??�작?�고 -->�??�납?�다"]',
ARRAY['basics', 'comment'], 3);

-- Unit 2: ?�스???�그 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-heading-h1', 'html', 'syntax', 6, '?�목 ?�그', 'h1 ?�그 ?�용', 'challenge', 1,
'"Welcome"?�라??h1 ?�목??만드?�요.',
'- <h1> ?�그 ?�용\n- 가??중요???�목',
'[{"input": "", "output": "h1 ?�목"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <h1>Welcome</h1>\n</body>\n</html>',
'[{"input": "", "expected": "h1 with Welcome"}]',
'["h1?� ???�이지???�나�??�용?�는 것이 좋습?�다"]',
ARRAY['text', 'heading'], 5),

('html-multiple-headings', 'html', 'syntax', 7, '?�러 ?�목 ?�벨', 'h1~h6 계층', 'challenge', 1,
'h1부??h3까�? ?�목??만드?�요.',
'- h1: "Main Title"\n- h2: "Subtitle"\n- h3: "Section"',
'[{"input": "", "output": "?�목 계층 구조"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <h1>Main Title</h1>\n    <h2>Subtitle</h2>\n    <h3>Section</h3>\n</body>\n</html>',
'[{"input": "", "expected": "h1 h2 h3 hierarchy"}]',
'["?�목?� h1부??h6까�? ?�으�? ?�자가 ?�수�??�습?�다"]',
ARRAY['text', 'heading'], 5),

('html-paragraph', 'html', 'syntax', 8, '문단 ?�그', 'p ?�그 ?�용', 'challenge', 1,
'"This is a paragraph."?�는 문단??만드?�요.',
'- <p> ?�그 ?�용\n- ?�스??블록 ?�현',
'[{"input": "", "output": "p ?�그�?문단"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <p>This is a paragraph.</p>\n</body>\n</html>',
'[{"input": "", "expected": "paragraph element"}]',
'["p ?�그???�동?�로 ?�아???�백??만듭?�다"]',
ARRAY['text', 'paragraph'], 5),

('html-line-break', 'html', 'syntax', 9, '줄바�?, 'br ?�그', 'challenge', 1,
'??줄의 ?�스?��? br ?�그�?구분?�세??',
'- <br> ?�그 ?�용\n- self-closing ?�그',
'[{"input": "", "output": "줄바�?}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <p>\n        First line<br>\n        Second line\n    </p>\n</body>\n</html>',
'[{"input": "", "expected": "line break"}]',
'["br ?�그???�는 ?�그가 ?�습?�다"]',
ARRAY['text', 'line-break'], 5),

('html-horizontal-rule', 'html', 'syntax', 10, '?�평??, 'hr ?�그', 'challenge', 1,
'??문단 ?�이???�평?�을 추�??�세??',
'- <hr> ?�그 ?�용\n- 콘텐�?구분??,
'[{"input": "", "output": "?�평??}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <p>Above the line</p>\n    <hr>\n    <p>Below the line</p>\n</body>\n</html>',
'[{"input": "", "expected": "horizontal rule"}]',
'["hr?� ?�마??구분???��??�니??]',
ARRAY['text', 'hr'], 5);

-- Unit 3: ?�스???�식 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-bold', 'html', 'syntax', 11, '굵�? ?�스??, 'strong ?�그', 'challenge', 1,
'"Important"�?굵게 ?�시?�세??',
'- <strong> ?�그 ?�용\n- ?��??�으�?중요???�스??,
'[{"input": "", "output": "굵�? ?�스??}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <p>This is <strong>Important</strong>.</p>\n</body>\n</html>',
'[{"input": "", "expected": "strong tag"}]',
'["strong?� ?��???중요?��?, b???�순 ?��??�입?�다"]',
ARRAY['text', 'formatting', 'strong'], 5),

('html-italic', 'html', 'syntax', 12, '?�탤�??�스??, 'em ?�그', 'challenge', 1,
'"emphasized"�??�탤�?���??�시?�세??',
'- <em> ?�그 ?�용\n- 강조 ?��?',
'[{"input": "", "output": "?�탤�??�스??}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <p>This is <em>emphasized</em>.</p>\n</body>\n</html>',
'[{"input": "", "expected": "em tag"}]',
'["em?� 강조�? i???�순 ?��??�입?�다"]',
ARRAY['text', 'formatting', 'em'], 5),

('html-mark', 'html', 'syntax', 13, '?�이?�이??, 'mark ?�그', 'challenge', 1,
'"highlighted"�??�이?�이???�시?�세??',
'- <mark> ?�그 ?�용\n- 배경?�이 ?�는 강조',
'[{"input": "", "output": "?�이?�이??}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <p>This is <mark>highlighted</mark> text.</p>\n</body>\n</html>',
'[{"input": "", "expected": "mark tag"}]',
'["mark??주로 ?��? 배경?�으�??�시?�니??]',
ARRAY['text', 'formatting', 'mark'], 5),

('html-small', 'html', 'syntax', 14, '?��? ?�스??, 'small ?�그', 'challenge', 1,
'부가 ?�보�?small ?�그�??�시?�세??',
'- <small> ?�그 ?�용\n- ???��? 글??,
'[{"input": "", "output": "?��? ?�스??}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <p>Regular text <small>small print</small></p>\n</body>\n</html>',
'[{"input": "", "expected": "small tag"}]',
'["small?� 법적 고�????�?�권 ?�시???�주 ?�용?�니??]',
ARRAY['text', 'formatting', 'small'], 5),

('html-del-ins', 'html', 'syntax', 15, '??��/?�입', 'del�?ins ?�그', 'challenge', 1,
'??��???�스?��? ?�입???�스?��? ?�시?�세??',
'- <del> ??��??n- <ins> 밑줄',
'[{"input": "", "output": "del, ins ?�그"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <p>Price: <del>$100</del> <ins>$80</ins></p>\n</body>\n</html>',
'[{"input": "", "expected": "del and ins tags"}]',
'["del?� ??��?? ins??밑줄�??�시?�니??]',
ARRAY['text', 'formatting', 'del', 'ins'], 5);

-- Unit 4: 링크?� ?��?지 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-link-basic', 'html', 'syntax', 16, '기본 링크', 'a ?�그 ?�용', 'challenge', 1,
'"Visit Google"?�라???�스?�로 구�? 링크�?만드?�요.',
'- <a> ?�그 ?�용\n- href ?�성??URL',
'[{"input": "", "output": "?�이?�링??}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <a href="https://www.google.com">Visit Google</a>\n</body>\n</html>',
'[{"input": "", "expected": "link to google"}]',
'["href??hypertext reference???�자?�니??]',
ARRAY['link', 'anchor'], 5),

('html-link-target', 'html', 'syntax', 17, '????��???�기', 'target ?�성', 'challenge', 1,
'링크�?????��???�리?�록 ?�정?�세??',
'- target="_blank"\n- ??�???��???�림',
'[{"input": "", "output": "????링크"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <a href="https://example.com" target="_blank">Example</a>\n</body>\n</html>',
'[{"input": "", "expected": "target blank"}]',
'["_blank????브라?�징 컨텍?�트�??��??�니??]',
ARRAY['link', 'target'], 5),

('html-image-basic', 'html', 'syntax', 18, '?��?지 ?�입', 'img ?�그', 'challenge', 1,
'?��?지�??�입?�세??',
'- <img> ?�그 ?�용\n- src?� alt ?�성 ?�수',
'[{"input": "", "output": "?��?지"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <img src="image.jpg" alt="Description">\n</body>\n</html>',
'[{"input": "", "expected": "img tag"}]',
'["alt???�근?�을 ?�해 ?�수?�니??]',
ARRAY['image', 'img'], 5),

('html-image-size', 'html', 'syntax', 19, '?��?지 ?�기', 'width?� height', 'challenge', 1,
'?��?지 ?�기�?300x200?�로 ?�정?�세??',
'- width?� height ?�성\n- ?��? ?�위',
'[{"input": "", "output": "?�기 지???��?지"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <img src="photo.jpg" alt="Photo" width="300" height="200">\n</body>\n</html>',
'[{"input": "", "expected": "300x200 image"}]',
'["width?� height�??�이?�웃 ?�프?��? 방�??????�습?�다"]',
ARRAY['image', 'size'], 5),

('html-link-image', 'html', 'syntax', 20, '?��?지 링크', '?��?지�??�릭 가?�하�?, 'challenge', 1,
'?��?지�??�릭?�면 링크�??�동?�게 만드?�요.',
'- a ?�그 ?�에 img ?�그\n- ?��?지가 링크 ??��',
'[{"input": "", "output": "?�릭 가?�한 ?��?지"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <a href="https://example.com">\n        <img src="logo.png" alt="Logo">\n    </a>\n</body>\n</html>',
'[{"input": "", "expected": "clickable image"}]',
'["a ?�그�?img�?감싸�??��?지가 링크가 ?�니??]',
ARRAY['link', 'image'], 8);

-- Unit 5: 리스??(5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-ul-list', 'html', 'syntax', 21, '?�서 ?�는 목록', 'ul�?li', 'challenge', 1,
'3�???��???�서 ?�는 목록??만드?�요.',
'- <ul> ?�그 ?�용\n- <li> ??��??,
'[{"input": "", "output": "불릿 목록"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <ul>\n        <li>Item 1</li>\n        <li>Item 2</li>\n        <li>Item 3</li>\n    </ul>\n</body>\n</html>',
'[{"input": "", "expected": "ul with 3 li"}]',
'["ul?� unordered list???�자?�니??]',
ARRAY['list', 'ul'], 5),

('html-ol-list', 'html', 'syntax', 22, '?�서 ?�는 목록', 'ol�?li', 'challenge', 1,
'3�???��???�서 ?�는 목록??만드?�요.',
'- <ol> ?�그 ?�용\n- ?�동?�로 번호 매�?',
'[{"input": "", "output": "번호 목록"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <ol>\n        <li>First</li>\n        <li>Second</li>\n        <li>Third</li>\n    </ol>\n</body>\n</html>',
'[{"input": "", "expected": "ol with 3 li"}]',
'["ol?� ordered list???�자?�니??]',
ARRAY['list', 'ol'], 5),

('html-nested-list', 'html', 'syntax', 23, '중첩 목록', '목록 ?�의 목록', 'challenge', 1,
'목록 ??�� ?�에 ?�른 목록???�으?�요.',
'- li ?�에 ul ?�는 ol\n- 계층 구조 ?�현',
'[{"input": "", "output": "중첩 목록"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <ul>\n        <li>Main item\n            <ul>\n                <li>Sub item 1</li>\n                <li>Sub item 2</li>\n            </ul>\n        </li>\n    </ul>\n</body>\n</html>',
'[{"input": "", "expected": "nested list"}]',
'["중첩 목록?� li ?�그 ?�에 ?�로??ul/ol???�습?�다"]',
ARRAY['list', 'nested'], 8),

('html-dl-list', 'html', 'syntax', 24, '?�의 목록', 'dl, dt, dd', 'challenge', 1,
'?�어?� ?�명?�로 구성???�의 목록??만드?�요.',
'- <dl> ?�의 목록\n- <dt> ?�어, <dd> ?�명',
'[{"input": "", "output": "?�의 목록"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <dl>\n        <dt>HTML</dt>\n        <dd>Hypertext Markup Language</dd>\n        <dt>CSS</dt>\n        <dd>Cascading Style Sheets</dd>\n    </dl>\n</body>\n</html>',
'[{"input": "", "expected": "definition list"}]',
'["dl?� definition list, dt??term, dd??description?�니??]',
ARRAY['list', 'dl'], 8),

('html-ol-start', 'html', 'syntax', 25, '목록 ?�작 번호', 'start ?�성', 'challenge', 1,
'5번�????�작?�는 ?�서 목록??만드?�요.',
'- <ol start="5">\n- ?�작 번호 지??,
'[{"input": "", "output": "5번�????�작"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <ol start="5">\n        <li>Item</li>\n        <li>Item</li>\n    </ol>\n</body>\n</html>',
'[{"input": "", "expected": "ol starting at 5"}]',
'["start ?�성?�로 ?�작 번호�?변경할 ???�습?�다"]',
ARRAY['list', 'ol', 'start'], 5);

-- Unit 6: ?�이�?(5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-table-basic', 'html', 'syntax', 26, '기본 ?�이�?, 'table, tr, td', 'challenge', 1,
'2x2 ?�이블을 만드?�요.',
'- <table> ?�그\n- <tr> ?? <td> ?�',
'[{"input": "", "output": "간단???�이�?}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr>\n            <td>Cell 1</td>\n            <td>Cell 2</td>\n        </tr>\n        <tr>\n            <td>Cell 3</td>\n            <td>Cell 4</td>\n        </tr>\n    </table>\n</body>\n</html>',
'[{"input": "", "expected": "2x2 table"}]',
'["tr?� table row, td??table data?�니??]',
ARRAY['table', 'basics'], 8),

('html-table-header', 'html', 'syntax', 27, '?�이�??�더', 'th ?�그', 'challenge', 1,
'?�더가 ?�는 ?�이블을 만드?�요.',
'- <th> ?�그 ?�용\n- �??�을 ?�더�?,
'[{"input": "", "output": "?�더 ?�이�?}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <table>\n        <tr>\n            <th>Name</th>\n            <th>Age</th>\n        </tr>\n        <tr>\n            <td>John</td>\n            <td>30</td>\n        </tr>\n    </table>\n</body>\n</html>',
'[{"input": "", "expected": "table with th"}]',
'["th??table header�?기본?�으�?굵게 ?�시?�니??]',
ARRAY['table', 'th'], 8),

('html-table-border', 'html', 'syntax', 28, '?�이�??�두�?, 'border ?�성', 'challenge', 1,
'?�두리�? ?�는 ?�이블을 만드?�요.',
'- border="1"\n- CSS ?�이 간단???�두�?,
'[{"input": "", "output": "?�두�??�이�?}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <table border="1">\n        <tr><td>A</td><td>B</td></tr>\n    </table>\n</body>\n</html>',
'[{"input": "", "expected": "table with border"}]',
'["border ?�성?� HTML5?�서??CSS�??�용?�는 것이 권장?�니??]',
ARRAY['table', 'border'], 5),

('html-table-colspan', 'html', 'syntax', 29, '?� 병합 (가�?', 'colspan ?�성', 'challenge', 1,
'2�??�을 병합???�??만드?�요.',
'- colspan="2"\n- 가로로 ?� 병합',
'[{"input": "", "output": "colspan ?�이�?}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <table border="1">\n        <tr>\n            <td colspan="2">Merged Cell</td>\n        </tr>\n        <tr>\n            <td>A</td><td>B</td>\n        </tr>\n    </table>\n</body>\n</html>',
'[{"input": "", "expected": "colspan 2"}]',
'["colspan?� column span?�로 ?�을 병합?�니??]',
ARRAY['table', 'colspan'], 8),

('html-table-rowspan', 'html', 'syntax', 30, '?� 병합 (?�로)', 'rowspan ?�성', 'challenge', 1,
'2�??�을 병합???�??만드?�요.',
'- rowspan="2"\n- ?�로�??� 병합',
'[{"input": "", "output": "rowspan ?�이�?}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <table border="1">\n        <tr>\n            <td rowspan="2">A</td>\n            <td>B</td>\n        </tr>\n        <tr>\n            <td>D</td>\n        </tr>\n    </table>\n</body>\n</html>',
'[{"input": "", "expected": "rowspan 2"}]',
'["rowspan?� row span?�로 ?�을 병합?�니??]',
ARRAY['table', 'rowspan'], 8);

-- Unit 7: ??기본 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-form-basic', 'html', 'syntax', 31, '기본 ??, 'form ?�그', 'challenge', 1,
'기본 ?�을 만드?�요.',
'- <form> ?�그\n- action�?method ?�성',
'[{"input": "", "output": "??구조"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form action="/submit" method="post">\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "form with action and method"}]',
'["action?� ?�이?��? 보낼 URL, method??HTTP 메서?�입?�다"]',
ARRAY['form', 'basics'], 5),

('html-input-text', 'html', 'syntax', 32, '?�스???�력', 'input type=text', 'challenge', 1,
'?�름???�력받는 ?�스???�드�?만드?�요.',
'- <input type="text">\n- name�?placeholder ?�성',
'[{"input": "", "output": "?�스???�력 ?�드"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="text" name="username" placeholder="Enter name">\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "text input"}]',
'["placeholder???�트 ?�스?�입?�다"]',
ARRAY['form', 'input', 'text'], 5),

('html-label', 'html', 'syntax', 33, '?�벨', 'label ?�그', 'challenge', 1,
'?�력 ?�드???�벨???�결?�세??',
'- <label> ?�그\n- for ?�성�?input id ?�결',
'[{"input": "", "output": "?�벨�??�력"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label for="email">Email:</label>\n        <input type="text" id="email" name="email">\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "label with for"}]',
'["label??for?� input??id�?같게 ?�면 ?�결?�니??]',
ARRAY['form', 'label'], 8),

('html-input-password', 'html', 'syntax', 34, '비�?번호 ?�력', 'input type=password', 'challenge', 1,
'비�?번호 ?�력 ?�드�?만드?�요.',
'- type="password"\n- ?�력 ?�용 ?��? ?�시',
'[{"input": "", "output": "비�?번호 ?�드"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label for="pwd">Password:</label>\n        <input type="password" id="pwd" name="password">\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "password input"}]',
'["password ?�?��? ?�력 값을 ?�으�??�시?�니??]',
ARRAY['form', 'input', 'password'], 5),

('html-submit-button', 'html', 'syntax', 35, '?�출 버튼', 'input type=submit', 'challenge', 1,
'???�출 버튼??만드?�요.',
'- type="submit"\n- value�?버튼 ?�스??,
'[{"input": "", "output": "?�출 버튼"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="text" name="name">\n        <input type="submit" value="Submit">\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "submit button"}]',
'["submit 버튼???�릭?�면 ?�이 ?�출?�니??]',
ARRAY['form', 'button', 'submit'], 5);

-- Unit 8: ???�력 ?�??(5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-input-email', 'html', 'syntax', 36, '?�메???�력', 'input type=email', 'challenge', 1,
'?�메???�력 ?�드�?만드?�요.',
'- type="email"\n- ?�동 ?�효??검??,
'[{"input": "", "output": "?�메???�드"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Email:</label>\n        <input type="email" name="email" required>\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "email input"}]',
'["email ?�?��? @ ?�함 ?��?�??�동 검증합?�다"]',
ARRAY['form', 'input', 'email'], 5),

('html-input-number', 'html', 'syntax', 37, '?�자 ?�력', 'input type=number', 'challenge', 1,
'?�이�??�력받는 ?�자 ?�드�?만드?�요 (1-100).',
'- type="number"\n- min, max ?�성',
'[{"input": "", "output": "?�자 ?�드"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Age:</label>\n        <input type="number" name="age" min="1" max="100">\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "number input 1-100"}]',
'["min�?max�?범위�??�한?????�습?�다"]',
ARRAY['form', 'input', 'number'], 5),

('html-input-date', 'html', 'syntax', 38, '?�짜 ?�력', 'input type=date', 'challenge', 1,
'?�짜 ?�택 ?�드�?만드?�요.',
'- type="date"\n- ?�력 UI ?�공',
'[{"input": "", "output": "?�짜 ?�드"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Birth Date:</label>\n        <input type="date" name="birthdate">\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "date input"}]',
'["date ?�?��? 브라?��?가 ?�력???�공?�니??]',
ARRAY['form', 'input', 'date'], 5),

('html-input-checkbox', 'html', 'syntax', 39, '체크박스', 'input type=checkbox', 'challenge', 1,
'?��? ?�의 체크박스�?만드?�요.',
'- type="checkbox"\n- checked ?�성?�로 기본 ?�택',
'[{"input": "", "output": "체크박스"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="checkbox" id="agree" name="agree">\n        <label for="agree">I agree to terms</label>\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "checkbox"}]',
'["체크박스??on/off ?�택???�용?�니??]',
ARRAY['form', 'input', 'checkbox'], 5),

('html-input-radio', 'html', 'syntax', 40, '?�디??버튼', 'input type=radio', 'challenge', 1,
'?�별 ?�택 ?�디??버튼??만드?�요.',
'- type="radio"\n- 같�? name?�로 그룹??,
'[{"input": "", "output": "?�디??버튼"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <input type="radio" id="male" name="gender" value="male">\n        <label for="male">Male</label>\n        <input type="radio" id="female" name="gender" value="female">\n        <label for="female">Female</label>\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "radio buttons"}]',
'["같�? name??가�??�디?�는 ?�나�??�택?�니??]',
ARRAY['form', 'input', 'radio'], 8);

-- Unit 9: ???�소 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-textarea', 'html', 'syntax', 41, '?�스???�역', 'textarea ?�그', 'challenge', 1,
'?�러 �??�스???�력 ?�역??만드?�요.',
'- <textarea> ?�그\n- rows?� cols ?�성',
'[{"input": "", "output": "?�스???�역"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Comments:</label>\n        <textarea name="comments" rows="4" cols="50"></textarea>\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "textarea"}]',
'["textarea???�러 �??�력???�용?�니??]',
ARRAY['form', 'textarea'], 5),

('html-select', 'html', 'syntax', 42, '?�롭?�운', 'select?� option', 'challenge', 1,
'�?? ?�택 ?�롭?�운??만드?�요.',
'- <select> ?�그\n- <option> ?�택지??,
'[{"input": "", "output": "?�롭?�운"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <label>Country:</label>\n        <select name="country">\n            <option value="kr">Korea</option>\n            <option value="us">USA</option>\n            <option value="jp">Japan</option>\n        </select>\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "select with options"}]',
'["option??value???�버�??�송?�는 값입?�다"]',
ARRAY['form', 'select'], 8),

('html-select-selected', 'html', 'syntax', 43, '기본 ?�택�?, 'selected ?�성', 'challenge', 1,
'?�롭?�운??기본 ?�택값을 ?�정?�세??',
'- selected ?�성\n- option??추�?',
'[{"input": "", "output": "기본�??�는 ?�롭?�운"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <select>\n        <option value="1">Option 1</option>\n        <option value="2" selected>Option 2</option>\n    </select>\n</body>\n</html>',
'[{"input": "", "expected": "option 2 selected"}]',
'["selected ?�성?�로 기본 ?�택??지?�합?�다"]',
ARRAY['form', 'select', 'selected'], 5),

('html-button', 'html', 'syntax', 44, 'button ?�그', '버튼 만들�?, 'challenge', 1,
'?�릭 가?�한 버튼??만드?�요.',
'- <button> ?�그\n- type ?�성 (button, submit, reset)',
'[{"input": "", "output": "버튼"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <button type="button">Click Me</button>\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "button element"}]',
'["button ?�그??input type=button보다 ?��??�링???�습?�다"]',
ARRAY['form', 'button'], 5),

('html-fieldset', 'html', 'syntax', 45, '?�드??, 'fieldset�?legend', 'challenge', 1,
'???�소�?그룹?�하?�요.',
'- <fieldset> ?�그�?그룹??n- <legend> ?�목',
'[{"input": "", "output": "그룹?�된 ??}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <form>\n        <fieldset>\n            <legend>Personal Info</legend>\n            <input type="text" name="name">\n            <input type="email" name="email">\n        </fieldset>\n    </form>\n</body>\n</html>',
'[{"input": "", "expected": "fieldset with legend"}]',
'["fieldset?� 관?????�소�??�각?�으�?그룹?�합?�다"]',
ARRAY['form', 'fieldset'], 8);

-- Unit 10: ?�맨???�그 (5 problems - EASY)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('html-header', 'html', 'syntax', 46, 'header ?�그', '?�이지 ?�더', 'challenge', 1,
'?�이지 ?�단 ?�더�?만드?�요.',
'- <header> ?�그\n- 로고, ?�비게이?????�함',
'[{"input": "", "output": "?�맨???�더"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <header>\n        <h1>My Website</h1>\n        <nav>Navigation</nav>\n    </header>\n</body>\n</html>',
'[{"input": "", "expected": "header element"}]',
'["header???�개 콘텐츠나 ?�비게이?�을 ?�습?�다"]',
ARRAY['semantic', 'header'], 5),

('html-nav', 'html', 'syntax', 47, 'nav ?�그', '?�비게이??, 'challenge', 1,
'?�비게이??메뉴�?만드?�요.',
'- <nav> ?�그\n- 주요 링크 모음',
'[{"input": "", "output": "?�비게이??}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <nav>\n        <a href="#home">Home</a>\n        <a href="#about">About</a>\n        <a href="#contact">Contact</a>\n    </nav>\n</body>\n</html>',
'[{"input": "", "expected": "nav with links"}]',
'["nav??주요 ?�비게이??링크 블록???��??�니??]',
ARRAY['semantic', 'nav'], 5),

('html-main', 'html', 'syntax', 48, 'main ?�그', '주요 콘텐�?, 'challenge', 1,
'?�이지??주요 콘텐�??�역??만드?�요.',
'- <main> ?�그\n- ?�이지???�나�?,
'[{"input": "", "output": "main 콘텐�?}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <header>Header</header>\n    <main>\n        <h1>Main Content</h1>\n        <p>This is the primary content.</p>\n    </main>\n    <footer>Footer</footer>\n</body>\n</html>',
'[{"input": "", "expected": "main element"}]',
'["main?� 문서??주요 콘텐츠�? ?��??�니??]',
ARRAY['semantic', 'main'], 5),

('html-footer', 'html', 'syntax', 49, 'footer ?�그', '?�이지 ?�단', 'challenge', 1,
'?�이지 ?�단 ?�터�?만드?�요.',
'- <footer> ?�그\n- ?�?�권, ?�락�???,
'[{"input": "", "output": "?�터"}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <main>Content</main>\n    <footer>\n        <p>&copy; 2024 My Website</p>\n    </footer>\n</body>\n</html>',
'[{"input": "", "expected": "footer element"}]',
'["footer??문서???�션???�단 ?�보�??�습?�다"]',
ARRAY['semantic', 'footer'], 5),

('html-article-section', 'html', 'syntax', 50, 'article�?section', '콘텐�?구조??, 'challenge', 1,
'article�?section???�용?�여 콘텐츠�? 구조?�하?�요.',
'- <article> ?�립?�인 콘텐�?n- <section> 주제�?그룹',
'[{"input": "", "output": "구조?�된 콘텐�?}]',
'',
'<!DOCTYPE html>\n<html>\n<body>\n    <main>\n        <article>\n            <h2>Article Title</h2>\n            <section>\n                <h3>Section 1</h3>\n                <p>Content here</p>\n            </section>\n            <section>\n                <h3>Section 2</h3>\n                <p>More content</p>\n            </section>\n        </article>\n    </main>\n</body>\n</html>',
'[{"input": "", "expected": "article with sections"}]',
'["article?� ?�립??콘텐�? section?� 주제�?그룹?�니??]',
ARRAY['semantic', 'article', 'section'], 10);

-- ====================================
-- ?�료 메시지
-- ====================================


