-- ====================================
-- SQL Language Challenges - Part 2
-- Levels 51-100 (MEDIUM 30�?+ HARD 20�?
-- ====================================

-- Unit 11: 복잡??JOIN (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('sql-right-join', 'sql', 'syntax', 51, 'RIGHT JOIN ?�용', '?�른�??�이�?기�? 조인', 'challenge', 2,
'departments ?�이블을 기�??�로 employees?� RIGHT JOIN?�여 부?�명�?직원명을 조회?�세??',
'- RIGHT JOIN ?�용\n- 부?��? ?��?�?직원???�는 경우???�함',
'[{"input": "", "output": "부?�명, 직원�?NULL ?�함)"}]',
'-- departments?� employees�?RIGHT JOIN?�세??n',
'SELECT d.dept_name, e.emp_name\nFROM employees e\nRIGHT JOIN departments d ON e.dept_id = d.dept_id;',
'[{"input": "", "expected": "right join result"}]',
'["RIGHT JOIN?� ?�른�??�이블의 모든 ?�을 ?�함?�니??]',
ARRAY['join', 'right-join'], 10),

('sql-full-outer-join', 'sql', 'syntax', 52, 'FULL OUTER JOIN', '?�쪽 모두 ?�함?�는 조인', 'challenge', 2,
'employees?� departments�?FULL OUTER JOIN?�여 모든 직원�?모든 부?��? 조회?�세??',
'- FULL OUTER JOIN ?�는 FULL JOIN ?�용\n- 매칭?��? ?�는 경우 NULL',
'[{"input": "", "output": "직원�? 부?�명 (모두 ?�함)"}]',
'-- employees?� departments�?FULL OUTER JOIN?�세??n',
'SELECT e.emp_name, d.dept_name\nFROM employees e\nFULL OUTER JOIN departments d ON e.dept_id = d.dept_id;',
'[{"input": "", "expected": "full outer join result"}]',
'["FULL OUTER JOIN?� ?�쪽 ?�이블의 모든 ?�을 ?�함?�니??]',
ARRAY['join', 'full-outer-join'], 10),

('sql-self-join', 'sql', 'syntax', 53, 'SELF JOIN', '같�? ?�이블끼�?조인', 'challenge', 2,
'employees ?�이블을 ?�기 ?�신�?조인?�여 직원�?그의 매니?� ?�름??조회?�세??',
'- 같�? ?�이블을 ?�로 ?�른 별칭?�로 조인\n- manager_id�?조인',
'[{"input": "", "output": "직원�? 매니?��?}]',
'-- employees�?self join?�여 직원�?매니?��?조회?�세??n',
'SELECT e.emp_name AS employee, m.emp_name AS manager\nFROM employees e\nLEFT JOIN employees m ON e.manager_id = m.emp_id;',
'[{"input": "", "expected": "employee-manager pairs"}]',
'["같�? ?�이블에 ?�로 ?�른 별칭???�용?�세??]',
ARRAY['join', 'self-join'], 12),

('sql-cross-join', 'sql', 'syntax', 54, 'CROSS JOIN', '카티??�?조인', 'challenge', 2,
'products?� colors ?�이블을 CROSS JOIN?�여 모든 조합??만드?�요.',
'- CROSS JOIN ?�용\n- 모든 가?�한 조합 ?�성',
'[{"input": "", "output": "?�품�? ?�상 모든 조합"}]',
'-- products?� colors�?CROSS JOIN?�세??n',
'SELECT p.product_name, c.color_name\nFROM products p\nCROSS JOIN colors c;',
'[{"input": "", "expected": "all combinations"}]',
'["CROSS JOIN?� ON 조건 ?�이 모든 조합??만듭?�다"]',
ARRAY['join', 'cross-join'], 10),

('sql-multiple-join', 'sql', 'syntax', 55, '?�중 ?�이�?조인', '3�??�상 ?�이�?조인', 'challenge', 2,
'orders, customers, products ?�이블을 조인?�여 주문 ?�보�??�세??조회?�세??',
'- 3�??�이블을 ?�차?�으�?JOIN\n- 고객�? ?�품�? 주문??출력',
'[{"input": "", "output": "고객�? ?�품�? 주문??}]',
'-- orders, customers, products�?조인?�세??n',
'SELECT c.customer_name, p.product_name, o.order_date\nFROM orders o\nJOIN customers c ON o.customer_id = c.customer_id\nJOIN products p ON o.product_id = p.product_id;',
'[{"input": "", "expected": "detailed order info"}]',
'["�?번째 JOIN 결과???�시 JOIN??추�??�세??]',
ARRAY['join', 'multiple-tables'], 12);

-- Unit 12: 고급 ?�브쿼리 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('sql-correlated-subquery', 'sql', 'syntax', 56, '?��? ?�브쿼리', '?��? 쿼리?� ?��????�브쿼리', 'challenge', 2,
'�?부?�별�??�균 급여보다 ?��? 급여�?받는 직원??조회?�세??',
'- ?��? ?�브쿼리 ?�용\n- ?��? 쿼리??dept_id�??�브쿼리?�서 참조',
'[{"input": "", "output": "직원�? 급여, 부?�ID"}]',
'-- 부?�별 ?�균보다 ?��? 급여�?받는 직원 조회\n',
'SELECT emp_name, salary, dept_id\nFROM employees e1\nWHERE salary > (SELECT AVG(salary) FROM employees e2 WHERE e2.dept_id = e1.dept_id);',
'[{"input": "", "expected": "employees above dept average"}]',
'["?�브쿼리?�서 ?��? ?�이블의 컬럼??참조?�세??]',
ARRAY['subquery', 'correlated'], 15),

('sql-exists-not-exists', 'sql', 'syntax', 57, 'EXISTS?� NOT EXISTS', '존재 ?��? ?�인', 'challenge', 2,
'주문????번이?�도 ?�는 고객�?조회?�세??',
'- EXISTS ?�용\n- ?�브쿼리?�서 orders ?�이�??�인',
'[{"input": "", "output": "고객�?}]',
'-- 주문???�는 고객??EXISTS�?조회?�세??n',
'SELECT customer_name\nFROM customers c\nWHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.customer_id);',
'[{"input": "", "expected": "customers with orders"}]',
'["EXISTS??결과가 ?�나?�도 ?�으�?TRUE�?반환?�니??]',
ARRAY['subquery', 'exists'], 12),

('sql-any-all', 'sql', 'syntax', 58, 'ANY?� ALL ?�산??, '?�브쿼리 결과?� 비교', 'challenge', 2,
'?�업부?�의 ?�떤 직원보다??급여가 ?��? ?�른 부??직원??조회?�세??',
'- ALL ?�산???�용\n- ?�브쿼리�??�업부 급여 조회',
'[{"input": "", "output": "직원�? 급여"}]',
'-- ?�업부 모든 직원보다 급여가 ?��? 직원 조회\n',
'SELECT emp_name, salary\nFROM employees\nWHERE salary > ALL (SELECT salary FROM employees WHERE dept_name = \''?�업부\'');',
'[{"input": "", "expected": "employees with higher salary"}]',
'["ALL?� ?�브쿼리??모든 값보??커야 ?�니??]',
ARRAY['subquery', 'all'], 12),

('sql-scalar-subquery', 'sql', 'syntax', 59, '?�칼???�브쿼리', 'SELECT?�의 ?�브쿼리', 'challenge', 2,
'직원 ?�보?� ?�께 �?직원??부???�균 급여�??�께 출력?�세??',
'- SELECT?�에 ?�브쿼리 ?�용\n- ?�일 �?반환',
'[{"input": "", "output": "직원�? 급여, 부?�평균급??}]',
'-- SELECT?�에 ?�브쿼리�??�용?�세??n',
'SELECT emp_name, salary,\n  (SELECT AVG(salary) FROM employees e2 WHERE e2.dept_id = e1.dept_id) AS dept_avg\nFROM employees e1;',
'[{"input": "", "expected": "employees with dept average"}]',
'["SELECT?�의 ?�브쿼리???�나??값만 반환?�야 ?�니??]',
ARRAY['subquery', 'scalar'], 15),

('sql-derived-table', 'sql', 'syntax', 60, '?�생 ?�이�?, 'FROM?�의 ?�브쿼리', 'challenge', 2,
'부?�별 ?�균 급여�?구한 ?? �?�?500만원 ?�상??부?�만 조회?�세??',
'- FROM?�에 ?�브쿼리 ?�용\n- ?�브쿼리??별칭 부??,
'[{"input": "", "output": "부?�ID, ?�균급여"}]',
'-- FROM?�에 ?�브쿼리�??�용?�세??n',
'SELECT dept_id, avg_salary\nFROM (SELECT dept_id, AVG(salary) AS avg_salary FROM employees GROUP BY dept_id) AS dept_avg\nWHERE avg_salary >= 5000000;',
'[{"input": "", "expected": "high average salary depts"}]',
'["FROM?�의 ?�브쿼리??반드??별칭??가?�야 ?�니??]',
ARRAY['subquery', 'derived-table'], 15);

-- Unit 13: 집합 ?�산 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('sql-union', 'sql', 'syntax', 61, 'UNION ?�용', '중복 ?�거 ?�집??, 'challenge', 2,
'2023??주문�?2024??주문??고객 목록??중복 ?�이 조회?�세??',
'- UNION ?�용\n- 중복 ?�동 ?�거',
'[{"input": "", "output": "고객ID (중복 ?�거)"}]',
'-- 2023?�과 2024??주문 고객??UNION?�로 조회\n',
'SELECT customer_id FROM orders WHERE YEAR(order_date) = 2023\nUNION\nSELECT customer_id FROM orders WHERE YEAR(order_date) = 2024;',
'[{"input": "", "expected": "unique customers"}]',
'["UNION?� ?�동?�로 중복???�거?�니??]',
ARRAY['set-operations', 'union'], 10),

('sql-union-all', 'sql', 'syntax', 62, 'UNION ALL', '중복 ?�함 ?�집??, 'challenge', 2,
'모든 ?�품�?모든 ?�비?�의 ?�름??중복 ?�함?�여 조회?�세??',
'- UNION ALL ?�용\n- 중복 ?��?',
'[{"input": "", "output": "?�름 (중복 ?�함)"}]',
'-- products?� services???�름??UNION ALL�?조회\n',
'SELECT product_name AS name FROM products\nUNION ALL\nSELECT service_name AS name FROM services;',
'[{"input": "", "expected": "all names with duplicates"}]',
'["UNION ALL?� 중복???�거?��? ?�습?�다"]',
ARRAY['set-operations', 'union-all'], 10),

('sql-intersect', 'sql', 'syntax', 63, 'INTERSECT ?�용', '교집??, 'challenge', 2,
'2023?�과 2024??모두 주문??고객??조회?�세??',
'- INTERSECT ?�용\n- ?�쪽??모두 존재?�는 ??,
'[{"input": "", "output": "고객ID"}]',
'-- 2023?�과 2024??모두 주문??고객??INTERSECT�?조회\n',
'SELECT customer_id FROM orders WHERE YEAR(order_date) = 2023\nINTERSECT\nSELECT customer_id FROM orders WHERE YEAR(order_date) = 2024;',
'[{"input": "", "expected": "customers in both years"}]',
'["INTERSECT???�쪽??모두 ?�는 ?�만 반환?�니??]',
ARRAY['set-operations', 'intersect'], 12),

('sql-except', 'sql', 'syntax', 64, 'EXCEPT/MINUS', '차집??, 'challenge', 2,
'2023?�에??주문?��?�?2024?�에??주문?��? ?��? 고객??조회?�세??',
'- EXCEPT ?�는 MINUS ?�용\n- �?번째 집합?�만 ?�는 ??,
'[{"input": "", "output": "고객ID"}]',
'-- 2023?�에�?주문??고객??EXCEPT�?조회\n',
'SELECT customer_id FROM orders WHERE YEAR(order_date) = 2023\nEXCEPT\nSELECT customer_id FROM orders WHERE YEAR(order_date) = 2024;',
'[{"input": "", "expected": "customers only in 2023"}]',
'["EXCEPT??�?번째 집합?�서 ??번째 집합??뺍니??]',
ARRAY['set-operations', 'except'], 12),

('sql-set-operations-complex', 'sql', 'syntax', 65, '복합 집합 ?�산', '?�러 집합 ?�산 조합', 'challenge', 2,
'(A UNION B) INTERSECT C ?�태??복합 집합 ?�산???�행?�세??',
'- 괄호�??�산 ?�서 지??n- ?�러 집합 ?�산 조합',
'[{"input": "", "output": "결과 집합"}]',
'-- 복합 집합 ?�산???�행?�세??n',
'(SELECT id FROM table_a UNION SELECT id FROM table_b)\nINTERSECT\nSELECT id FROM table_c;',
'[{"input": "", "expected": "complex set result"}]',
'["괄호�??�용?�여 ?�산 ?�서�?지?�하?�요"]',
ARRAY['set-operations', 'complex'], 15);

-- Unit 14: ?�도???�수 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('sql-row-number', 'sql', 'syntax', 66, 'ROW_NUMBER ?�수', '??번호 부??, 'challenge', 2,
'�?부?�별�?급여 ?�으�??�위�?매기?�요.',
'- ROW_NUMBER() OVER ?�용\n- PARTITION BY?� ORDER BY',
'[{"input": "", "output": "직원�? 부?? 급여, ?�위"}]',
'-- ROW_NUMBER�?부?�별 급여 ?�위�?매기?�요\n',
'SELECT emp_name, dept_id, salary,\n  ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rank\nFROM employees;',
'[{"input": "", "expected": "ranked employees"}]',
'["PARTITION BY�?그룹???�누�?ORDER BY�??�렬?�세??]',
ARRAY['window-function', 'row-number'], 15),

('sql-rank-dense-rank', 'sql', 'syntax', 67, 'RANK?� DENSE_RANK', '?�위 ?�수', 'challenge', 2,
'?�체 직원??급여 ?�위�?RANK?� DENSE_RANK�?각각 구하?�요.',
'- RANK()?� DENSE_RANK() 비교\n- ?�점 처리 방식 차이',
'[{"input": "", "output": "직원�? 급여, rank, dense_rank"}]',
'-- RANK?� DENSE_RANK�?급여 ?�위�?구하?�요\n',
'SELECT emp_name, salary,\n  RANK() OVER (ORDER BY salary DESC) AS rank,\n  DENSE_RANK() OVER (ORDER BY salary DESC) AS dense_rank\nFROM employees;',
'[{"input": "", "expected": "ranks comparison"}]',
'["RANK???�점 ???�음 ?�위�?건너?�고, DENSE_RANK??건너?��? ?�습?�다"]',
ARRAY['window-function', 'rank'], 15),

('sql-lag-lead', 'sql', 'syntax', 68, 'LAG?� LEAD', '?�전/?�음 ??참조', 'challenge', 2,
'�?직원??급여?� ?�전 직원??급여�??�께 출력?�세??',
'- LAG() ?�수 ?�용\n- ?�렬 ?�서???�른 ?�전 �?참조',
'[{"input": "", "output": "직원�? 급여, ?�전급여"}]',
'-- LAG�??�전 직원??급여�?조회?�세??n',
'SELECT emp_name, salary,\n  LAG(salary) OVER (ORDER BY emp_id) AS prev_salary\nFROM employees;',
'[{"input": "", "expected": "salary with previous"}]',
'["LAG???�전 ?? LEAD???�음 ?�을 참조?�니??]',
ARRAY['window-function', 'lag-lead'], 15),

('sql-sum-over', 'sql', 'syntax', 69, '?�적 ?�계', 'SUM OVER ?�도???�수', 'challenge', 2,
'?�짜�?매출???�적 ?�계�?구하?�요.',
'- SUM() OVER ?�용\n- ROWS BETWEEN?�로 범위 지??,
'[{"input": "", "output": "?�짜, 매출, ?�적?�계"}]',
'-- ?�짜�?매출???�적 ?�계�?구하?�요\n',
'SELECT sale_date, amount,\n  SUM(amount) OVER (ORDER BY sale_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_sum\nFROM sales;',
'[{"input": "", "expected": "cumulative sales"}]',
'["ROWS BETWEEN?�로 �??��????�재 ?�까지 ?�계�?구하?�요"]',
ARRAY['window-function', 'sum-over'], 15),

('sql-ntile', 'sql', 'syntax', 70, 'NTILE ?�수', '그룹 분할', 'challenge', 2,
'직원??급여 기�??�로 4�?그룹(?�분???�로 ?�누?�요.',
'- NTILE(4) ?�용\n- 균등 분할',
'[{"input": "", "output": "직원�? 급여, ?�분??}]',
'-- NTILE�?직원??4�?그룹?�로 ?�누?�요\n',
'SELECT emp_name, salary,\n  NTILE(4) OVER (ORDER BY salary DESC) AS quartile\nFROM employees;',
'[{"input": "", "expected": "employees in quartiles"}]',
'["NTILE(n)?� ?�이?��? n개의 균등??그룹?�로 ?�눕?�다"]',
ARRAY['window-function', 'ntile'], 12);

-- Unit 15: CTE?� ?��? 쿼리 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('sql-simple-cte', 'sql', 'syntax', 71, '기본 CTE', 'WITH ???�용', 'challenge', 2,
'WITH ?�을 ?�용?�여 부?�별 ?�균 급여�?구하�? �?결과�??�시 ?�용?�세??',
'- WITH ... AS (...) ?�용\n- CTE�?SELECT?�서 참조',
'[{"input": "", "output": "부?�ID, ?�균급여"}]',
'-- WITH ?�로 CTE�?만드?�요\n',
'WITH dept_avg AS (\n  SELECT dept_id, AVG(salary) AS avg_salary\n  FROM employees\n  GROUP BY dept_id\n)\nSELECT * FROM dept_avg WHERE avg_salary >= 5000000;',
'[{"input": "", "expected": "high average depts"}]',
'["WITH�??�시 결과�?만들�??�름??부?�하?�요"]',
ARRAY['cte', 'with'], 12),

('sql-multiple-cte', 'sql', 'syntax', 72, '?�중 CTE', '?�러 CTE ?�의', 'challenge', 2,
'2개의 CTE�??�의?�고 조인?�여 ?�용?�세??',
'- WITH cte1 AS (...), cte2 AS (...)\n- CTE?�리 조인',
'[{"input": "", "output": "조인 결과"}]',
'-- ?�러 CTE�??�의?�고 조인?�세??n',
'WITH high_salary AS (\n  SELECT emp_id, emp_name FROM employees WHERE salary > 5000000\n),\ndept_info AS (\n  SELECT dept_id, dept_name FROM departments\n)\nSELECT h.emp_name, d.dept_name\nFROM high_salary h\nJOIN employees e ON h.emp_id = e.emp_id\nJOIN dept_info d ON e.dept_id = d.dept_id;',
'[{"input": "", "expected": "joined cte result"}]',
'["?�러 CTE???�표�?구분?�여 ?�의?�니??]',
ARRAY['cte', 'multiple'], 15),

('sql-recursive-cte', 'sql', 'syntax', 73, '?��? CTE', '계층 구조 조회', 'challenge', 2,
'?��? CTE�??�용?�여 1부??10까�? ?�자�??�성?�세??',
'- WITH RECURSIVE ?�용\n- UNION ALL�??��? ?�출',
'[{"input": "", "output": "1부??10까�?"}]',
'-- ?��? CTE�?1부??10까�? ?�성?�세??n',
'WITH RECURSIVE numbers AS (\n  SELECT 1 AS n\n  UNION ALL\n  SELECT n + 1 FROM numbers WHERE n < 10\n)\nSELECT * FROM numbers;',
'[{"input": "", "expected": "numbers 1 to 10"}]',
'["기본 케?�스?� ?��? 케?�스�?UNION ALL�??�결?�세??]',
ARRAY['cte', 'recursive'], 18),

('sql-hierarchy-query', 'sql', 'syntax', 74, '조직??조회', '?��?�?계층 구조', 'challenge', 2,
'?��? CTE�?직원???�체 ?�위 관리자 체인??조회?�세??',
'- 직원-매니?� 관계�? ?��?�??�색\n- 최상?�까지 ?�라가�?,
'[{"input": "", "output": "직원�? ?�벨, 경로"}]',
'-- ?��? CTE�?조직?��? 조회?�세??n',
'WITH RECURSIVE org_chart AS (\n  SELECT emp_id, emp_name, manager_id, 1 AS level\n  FROM employees\n  WHERE manager_id IS NULL\n  UNION ALL\n  SELECT e.emp_id, e.emp_name, e.manager_id, o.level + 1\n  FROM employees e\n  JOIN org_chart o ON e.manager_id = o.emp_id\n)\nSELECT * FROM org_chart;',
'[{"input": "", "expected": "org hierarchy"}]',
'["최상??manager_id IS NULL)부???�작?�여 ?�위�??�려가?�요"]',
ARRAY['cte', 'hierarchy'], 20),

('sql-cte-update', 'sql', 'syntax', 75, 'CTE�?UPDATE', 'CTE�?DML???�용', 'challenge', 2,
'CTE�??�용?�여 부???�균보다 ??? 급여�?가�?직원??급여�?10% ?�상?�세??',
'- WITH ????UPDATE ?�용\n- CTE 결과�?WHERE ?�에??참조',
'[{"input": "", "output": "?�데?�트??????}]',
'-- CTE�??�?�을 ?�하�?UPDATE?�세??n',
'WITH dept_avg AS (\n  SELECT dept_id, AVG(salary) AS avg_salary\n  FROM employees\n  GROUP BY dept_id\n)\nUPDATE employees e\nSET salary = salary * 1.1\nFROM dept_avg d\nWHERE e.dept_id = d.dept_id AND e.salary < d.avg_salary;',
'[{"input": "", "expected": "updated rows"}]',
'["CTE 결과�?UPDATE??FROM ?�에???�용?????�습?�다"]',
ARRAY['cte', 'update'], 15);

-- Unit 16: CASE 문과 조건 로직 (5 problems - MEDIUM)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('sql-simple-case', 'sql', 'syntax', 76, 'CASE WHEN 기본', '조건부 �?반환', 'challenge', 2,
'급여 구간???�라 ?�급??부?�하?�요 (5백만 ?�상: A, 3백만 ?�상: B, ?�머지: C).',
'- CASE WHEN ... THEN ... END\n- ?�러 조건 분기',
'[{"input": "", "output": "직원�? 급여, ?�급"}]',
'-- CASE WHEN?�로 급여 ?�급??부?�하?�요\n',
'SELECT emp_name, salary,\n  CASE\n    WHEN salary >= 5000000 THEN \''A\''\n    WHEN salary >= 3000000 THEN \''B\''\n    ELSE \''C\''\n  END AS grade\nFROM employees;',
'[{"input": "", "expected": "employees with grades"}]',
'["CASE???�에?��????�서?��?조건???��??�니??]',
ARRAY['case', 'conditional'], 12),

('sql-searched-case', 'sql', 'syntax', 77, 'Searched CASE', '복잡??조건 분기', 'challenge', 2,
'부?��? 급여�??�시??고려??복합 ?�급??부?�하?�요.',
'- ?�러 컬럼??조건?�로 ?�용\n- AND/OR 조합',
'[{"input": "", "output": "직원�? 부?? 급여, ?�급"}]',
'-- 부?��? 급여�??�께 고려?�여 ?�급??부?�하?�요\n',
'SELECT emp_name, dept_name, salary,\n  CASE\n    WHEN dept_name = \''?�업부\'' AND salary >= 5000000 THEN \''?�업A\''\n    WHEN dept_name = \''개발부\'' AND salary >= 6000000 THEN \''개발A\''\n    WHEN salary >= 4000000 THEN \''?�반A\''\n    ELSE \''?�반B\''\n  END AS grade\nFROM employees;',
'[{"input": "", "expected": "complex grades"}]',
'["AND�??�러 조건??결합?????�습?�다"]',
ARRAY['case', 'complex'], 15),

('sql-case-in-aggregate', 'sql', 'syntax', 78, '집계 ?�수??CASE', '조건부 집계', 'challenge', 2,
'부?�별�?고급??500�??�상)?� ?�급여(500�?미만) 직원 ?��? 각각 구하?�요.',
'- SUM(CASE ...) ?�턴\n- 조건부 카운??,
'[{"input": "", "output": "부?? 고급?�수, ?�급여??}]',
'-- CASE�?집계 ?�수 ?�에???�용?�세??n',
'SELECT dept_id,\n  SUM(CASE WHEN salary >= 5000000 THEN 1 ELSE 0 END) AS high_salary_count,\n  SUM(CASE WHEN salary < 5000000 THEN 1 ELSE 0 END) AS low_salary_count\nFROM employees\nGROUP BY dept_id;',
'[{"input": "", "expected": "conditional counts"}]',
'["CASE�?조건??맞으�?1, ?�니�?0??반환?�여 ?�계�?구하?�요"]',
ARRAY['case', 'aggregate'], 15),

('sql-case-in-order-by', 'sql', 'syntax', 79, 'ORDER BY??CASE', '조건부 ?�렬', 'challenge', 2,
'부?��? "?�업부"�?급여 ?�림차순, ?�머지???�름 ?�름차순?�로 ?�렬?�세??',
'- ORDER BY CASE ...\n- 조건???�른 ?�렬 방식 변�?,
'[{"input": "", "output": "?�렬??직원 목록"}]',
'-- ORDER BY??CASE�??�용?�세??n',
'SELECT emp_name, dept_name, salary\nFROM employees\nORDER BY\n  CASE WHEN dept_name = \''?�업부\'' THEN salary END DESC,\n  CASE WHEN dept_name != \''?�업부\'' THEN emp_name END ASC;',
'[{"input": "", "expected": "conditionally sorted"}]',
'["ORDER BY???�러 CASE�??�용?�여 조건별로 ?�른 ?�렬???�용?�세??]',
ARRAY['case', 'order-by'], 15),

('sql-pivot-with-case', 'sql', 'syntax', 80, 'CASE�??�벗', '?�을 ?�로 변??, 'challenge', 2,
'?�별 매출???�로 ?�쳐???�시?�세??(1?? 2?? 3??컬럼).',
'- CASE�?조건부 �??�당\n- 집계 ?�수?� ?�께 ?�용',
'[{"input": "", "output": "?�품, 1?? 2?? 3??}]',
'-- CASE�??�별 매출???�벗?�세??n',
'SELECT product_id,\n  SUM(CASE WHEN MONTH(sale_date) = 1 THEN amount ELSE 0 END) AS jan,\n  SUM(CASE WHEN MONTH(sale_date) = 2 THEN amount ELSE 0 END) AS feb,\n  SUM(CASE WHEN MONTH(sale_date) = 3 THEN amount ELSE 0 END) AS mar\nFROM sales\nGROUP BY product_id;',
'[{"input": "", "expected": "pivoted sales"}]',
'["�??�에 ?�당?�는 CASE�?만들??SUM?�로 집계?�세??]',
ARRAY['case', 'pivot'], 18);

-- Unit 17: 문자???�수 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('sql-string-manipulation', 'sql', 'syntax', 81, '문자??가�?, 'CONCAT, SUBSTRING ??, 'challenge', 3,
'?�메??주소?�서 ?�메??부분만 추출?�고, ?�문자�?변?�하?�요.',
'- SUBSTRING, POSITION, UPPER ?�용\n- @ ?�후 문자??추출',
'[{"input": "", "output": "?�메?? ?�메??}]',
'-- ?�메?�에???�메?�을 추출?�고 ?�문자�?변?�하?�요\n',
'SELECT email,\n  UPPER(SUBSTRING(email FROM POSITION(\''@\'' IN email) + 1)) AS domain\nFROM users;',
'[{"input": "", "expected": "extracted domains"}]',
'["POSITION?�로 @???�치�?찾고, SUBSTRING?�로 �??�후�?추출?�세??]',
ARRAY['string-function', 'hard'], 20),

('sql-pattern-matching', 'sql', 'syntax', 82, '?�턴 매칭', 'LIKE, REGEXP', 'challenge', 3,
'?�화번호 ?�식???�바른�? 검증하?�요 (###-####-####).',
'- REGEXP ?�는 ?�규???�용\n- ?�턴 ?�치 ?�인',
'[{"input": "", "output": "?�름, ?�화번호, ?�효??}]',
'-- ?�화번호가 ?�턴??맞는지 ?�인?�세??n',
'SELECT name, phone,\n  CASE\n    WHEN phone ~ \''^[0-9]{3}-[0-9]{4}-[0-9]{4}$\'' THEN \''?�효\''\n    ELSE \''무효\''\n  END AS validity\nFROM users;',
'[{"input": "", "expected": "validated phones"}]',
'["?�규??~�??�용?�여 ?�턴??검증하?�요"]',
ARRAY['string-function', 'regexp', 'hard'], 20),

('sql-string-aggregation', 'sql', 'syntax', 83, '문자??집계', 'STRING_AGG, GROUP_CONCAT', 'challenge', 3,
'부?�별�?직원 ?�름???�표�??�결?�여 ?�나??문자?�로 만드?�요.',
'- STRING_AGG ?�는 GROUP_CONCAT\n- 구분??지??,
'[{"input": "", "output": "부?? 직원목록"}]',
'-- STRING_AGG�?직원 ?�름???�결?�세??n',
'SELECT dept_id,\n  STRING_AGG(emp_name, \'', \'' ORDER BY emp_name) AS employees\nFROM employees\nGROUP BY dept_id;',
'[{"input": "", "expected": "concatenated names"}]',
'["STRING_AGG(컬럼, 구분??�?그룹??값들???�결?�세??]',
ARRAY['string-function', 'aggregation', 'hard'], 18),

('sql-split-string', 'sql', 'syntax', 84, '문자??분리', 'SPLIT_PART, UNNEST', 'challenge', 3,
'?�표�?구분???�그 문자?�을 개별 ?�으�?분리?�세??',
'- STRING_TO_ARRAY, UNNEST ?�용\n- ?�나???�을 ?�러 ?�으�??�장',
'[{"input": "", "output": "ID, 개별?�그"}]',
'-- ?�그 문자?�을 개별 ?�으�?분리?�세??n',
'SELECT id, UNNEST(STRING_TO_ARRAY(tags, \'',\'')) AS tag\nFROM posts;',
'[{"input": "", "expected": "split tags"}]',
'["STRING_TO_ARRAY�?배열??만들�?UNNEST�??�으�??�장?�세??]',
ARRAY['string-function', 'split', 'hard'], 20),

('sql-levenshtein-distance', 'sql', 'syntax', 85, '?�사 문자??찾기', '?�집 거리 계산', 'challenge', 3,
'Levenshtein 거리�??�용?�여 ?�름???�사??고객??찾으?�요.',
'- LEVENSHTEIN ?�수 ?�는 ?�사???�수\n- 거리 3 ?�내',
'[{"input": "", "output": "고객1, 고객2, 거리"}]',
'-- ?�사???�름??가�?고객 ?�을 찾으?�요\n',
'SELECT c1.name AS name1, c2.name AS name2,\n  LEVENSHTEIN(c1.name, c2.name) AS distance\nFROM customers c1\nJOIN customers c2 ON c1.id < c2.id\nWHERE LEVENSHTEIN(c1.name, c2.name) <= 3;',
'[{"input": "", "expected": "similar name pairs"}]',
'["LEVENSHTEIN ?�수�???문자??�??�집 거리�?계산?�세??]',
ARRAY['string-function', 'similarity', 'hard'], 25);

-- Unit 18: ?�짜/?�간 ?�수 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('sql-date-calculation', 'sql', 'syntax', 86, '?�짜 계산', '?�짜 ?�산', 'challenge', 3,
'�?주문?�로부??30?????�짜?� ?��? ?�수�?계산?�세??',
'- DATE_ADD, DATEDIFF ?�용\n- CURRENT_DATE?� 비교',
'[{"input": "", "output": "주문?? 만료?? ?��??�수"}]',
'-- 주문?�로부??30???��? ?��? ?�수�?계산?�세??n',
'SELECT order_date,\n  order_date + INTERVAL \''30 days\'' AS expiry_date,\n  (order_date + INTERVAL \''30 days\'') - CURRENT_DATE AS days_left\nFROM orders;',
'[{"input": "", "expected": "date calculations"}]',
'["INTERVAL�??�짜???�수�??�하�? ?�짜?�리 빼서 차이�?구하?�요"]',
ARRAY['date-function', 'hard'], 18),

('sql-extract-date-parts', 'sql', 'syntax', 87, '?�짜 부�?추출', 'EXTRACT, DATE_PART', 'challenge', 3,
'주문 ?�짜?�서 ?? ?? ?�일, 주차�?각각 추출?�세??',
'- EXTRACT ?�는 DATE_PART ?�용\n- YEAR, MONTH, DOW, WEEK',
'[{"input": "", "output": "주문?? ?? ?? ?�일, 주차"}]',
'-- ?�짜?�서 ?�러 부분을 추출?�세??n',
'SELECT order_date,\n  EXTRACT(YEAR FROM order_date) AS year,\n  EXTRACT(MONTH FROM order_date) AS month,\n  EXTRACT(DOW FROM order_date) AS day_of_week,\n  EXTRACT(WEEK FROM order_date) AS week\nFROM orders;',
'[{"input": "", "expected": "extracted date parts"}]',
'["EXTRACT(부�?FROM ?�짜) ?�식?�로 ?�용?�세??]',
ARRAY['date-function', 'extract', 'hard'], 18),

('sql-time-series-gap', 'sql', 'syntax', 88, '?�계??간격 찾기', '?�속?��? ?��? ?�짜', 'challenge', 3,
'?�별 ?�매 ?�이?�에???�매가 ?�는 ?�짜�?찾으?�요.',
'- ?�짜 ?�리�??�성\n- LEFT JOIN?�로 ?�락 ?�짜 찾기',
'[{"input": "", "output": "?�락???�짜"}]',
'-- ?�매가 ?�는 ?�짜�?찾으?�요\n',
'WITH date_series AS (\n  SELECT generate_series(\n    (SELECT MIN(sale_date) FROM sales),\n    (SELECT MAX(sale_date) FROM sales),\n    ''1 day''::interval\n  )::date AS date\n)\nSELECT d.date AS missing_date\nFROM date_series d\nLEFT JOIN sales s ON d.date = s.sale_date\nWHERE s.sale_date IS NULL;',
'[{"input": "", "expected": "missing dates"}]',
'["generate_series�??�속???�짜�?만들�?LEFT JOIN?�로 ?�락??찾으?�요"]',
ARRAY['date-function', 'time-series', 'hard'], 25),

('sql-moving-average', 'sql', 'syntax', 89, '?�동 ?�균', '?�짜 기반 ?�도??, 'challenge', 3,
'최근 7?�간??매출 ?�동 ?�균??계산?�세??',
'- ?�도???�수 ?�용\n- RANGE BETWEEN?�로 ?�짜 범위 지??,
'[{"input": "", "output": "?�짜, 매출, 7?�평�?}]',
'-- 7???�동 ?�균??계산?�세??n',
'SELECT sale_date, amount,\n  AVG(amount) OVER (\n    ORDER BY sale_date\n    RANGE BETWEEN INTERVAL \''6 days\'' PRECEDING AND CURRENT ROW\n  ) AS moving_avg_7d\nFROM sales;',
'[{"input": "", "expected": "moving averages"}]',
'["RANGE BETWEEN?�로 ?�짜 기�? 범위�?지?�하?�요"]',
ARRAY['date-function', 'window', 'hard'], 22),

('sql-fiscal-year', 'sql', 'syntax', 90, '?�계?�도 계산', '커스?� ?�도 ?�의', 'challenge', 3,
'?�계?�도(4???�작)�?기�??�로 ?�이?��? 그룹?�하?�요.',
'- CASE�??�계?�도 계산\n- 4??3?�을 ???�도�?,
'[{"input": "", "output": "?�계?�도, 총매�?}]',
'-- ?�계?�도�?매출??집계?�세??n',
'SELECT\n  CASE\n    WHEN EXTRACT(MONTH FROM sale_date) >= 4 THEN EXTRACT(YEAR FROM sale_date)\n    ELSE EXTRACT(YEAR FROM sale_date) - 1\n  END AS fiscal_year,\n  SUM(amount) AS total_sales\nFROM sales\nGROUP BY fiscal_year\nORDER BY fiscal_year;',
'[{"input": "", "expected": "fiscal year sales"}]',
'["4???�후�??�당 ?�도, 1~3?�이�??�년?��? ?�계?�도�??�세??]',
ARRAY['date-function', 'fiscal', 'hard'], 20);

-- Unit 19: JSON �?배열 (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('sql-json-extract', 'sql', 'syntax', 91, 'JSON ?�이??추출', 'JSON ?�드 ?�근', 'challenge', 3,
'JSON 컬럼?�서 ?�정 ?�의 값을 추출?�세??',
'- -> ?�는 ->> ?�산???�용\n- JSON 경로 지??,
'[{"input": "", "output": "ID, ?�름(JSON?�서 추출)"}]',
'-- JSON 컬럼?�서 name ?��? 추출?�세??n',
'SELECT id, data->>\''name\'' AS name\nFROM users;',
'[{"input": "", "expected": "extracted json values"}]',
'["->>???�스?�로, ->??JSON 객체�?반환?�니??]',
ARRAY['json', 'hard'], 18),

('sql-json-array-elements', 'sql', 'syntax', 92, 'JSON 배열 ?�장', 'JSON 배열???�으�?, 'challenge', 3,
'JSON 배열 ?�드�?개별 ?�으�??�장?�세??',
'- json_array_elements ?�용\n- LATERAL JOIN',
'[{"input": "", "output": "ID, 배열?�소"}]',
'-- JSON 배열??개별 ?�으�??�장?�세??n',
'SELECT id, elem->>\''value\'' AS item\nFROM products,\n  LATERAL json_array_elements(data->\''items\'') AS elem;',
'[{"input": "", "expected": "expanded array"}]',
'["json_array_elements�?배열??�??�소�??�으�?만드?�요"]',
ARRAY['json', 'array', 'hard'], 22),

('sql-jsonb-aggregation', 'sql', 'syntax', 93, 'JSON 집계', 'json_agg ?�용', 'challenge', 3,
'그룹�??�들??JSON 배열�?집계?�세??',
'- json_agg ?�는 jsonb_agg\n- JSON 객체�?변??,
'[{"input": "", "output": "부?? 직원배열(JSON)"}]',
'-- 부?�별 직원??JSON 배열�?집계?�세??n',
'SELECT dept_id,\n  jsonb_agg(jsonb_build_object(\''name\'', emp_name, \''salary\'', salary)) AS employees\nFROM employees\nGROUP BY dept_id;',
'[{"input": "", "expected": "json aggregated"}]',
'["jsonb_build_object�?객체�?만들�?jsonb_agg�?배열??만드?�요"]',
ARRAY['json', 'aggregation', 'hard'], 22),

('sql-array-operations', 'sql', 'syntax', 94, '배열 ?�산', 'ARRAY ?�수', 'challenge', 3,
'배열 컬럼?�서 ?�정 값이 ?�함???�을 찾으?�요.',
'- ANY, ALL ?�는 @> ?�산??n- 배열 ?�함 ?��? ?�인',
'[{"input": "", "output": "ID, ?�그배열"}]',
'-- ?�그 배열??''sql''???�함??게시물을 찾으?�요\n',
'SELECT id, tags\nFROM posts\nWHERE ''sql'' = ANY(tags);\n-- ?�는: WHERE tags @> ARRAY[''sql''];',
'[{"input": "", "expected": "posts with sql tag"}]',
'["ANY(배열)??배열???�느 ?�소?� ?�치?�는지 ?�인?�니??]',
ARRAY['array', 'hard'], 18),

('sql-array-unnest-filter', 'sql', 'syntax', 95, '배열 ?�터�?, 'UNNEST?� 조건', 'challenge', 3,
'배열???�친 ??조건??맞는 ?�소�??�시 배열�??�집?�세??',
'- UNNEST�??�장\n- WHERE�??�터\n- ARRAY_AGG�??�수�?,
'[{"input": "", "output": "ID, ?�터링된배열"}]',
'-- ?�수 배열?�서 80???�상�??�기?�요\n',
'SELECT id,\n  ARRAY_AGG(score) AS high_scores\nFROM (\n  SELECT id, UNNEST(scores) AS score\n  FROM students\n) AS expanded\nWHERE score >= 80\nGROUP BY id;',
'[{"input": "", "expected": "filtered arrays"}]',
'["UNNEST�??�치�? WHERE�??�터?�고, ARRAY_AGG�??�시 모으?�요"]',
ARRAY['array', 'filter', 'hard'], 25);

-- Unit 20: ?�랜??���?고급 DML (5 problems - HARD)
INSERT INTO challenges (slug, language, kind, level, title, description, category, difficulty, problem_description, constraints, examples, initial_code, solution_code, test_cases, hints, tags, estimated_time) VALUES
('sql-upsert', 'sql', 'syntax', 96, 'UPSERT 구현', 'INSERT ON CONFLICT', 'challenge', 3,
'존재?�면 UPDATE, ?�으�?INSERT?�는 UPSERT�?구현?�세??',
'- INSERT ... ON CONFLICT ?�용\n- DO UPDATE SET',
'[{"input": "", "output": "처리????}]',
'-- UPSERT�?구현?�세??n',
'INSERT INTO products (id, name, price)\nVALUES (1, \''Product A\'', 1000)\nON CONFLICT (id)\nDO UPDATE SET\n  name = EXCLUDED.name,\n  price = EXCLUDED.price;',
'[{"input": "", "expected": "upserted row"}]',
'["ON CONFLICT (??�?충돌 ???�작??지?�하?�요"]',
ARRAY['dml', 'upsert', 'hard'], 20),

('sql-merge-statement', 'sql', 'syntax', 97, 'MERGE �?, '조건부 INSERT/UPDATE/DELETE', 'challenge', 3,
'MERGE 문으�??�스 ?�이블을 ?��??�이블에 ?�기?�하?�요.',
'- MERGE INTO ?�용\n- WHEN MATCHED / NOT MATCHED',
'[{"input": "", "output": "병합 결과"}]',
'-- MERGE�????�이블을 ?�기?�하?�요\n',
'MERGE INTO target t\nUSING source s ON t.id = s.id\nWHEN MATCHED THEN\n  UPDATE SET t.value = s.value\nWHEN NOT MATCHED THEN\n  INSERT (id, value) VALUES (s.id, s.value);',
'[{"input": "", "expected": "merged data"}]',
'["MERGE??매칭 ?��????�라 ?�른 ?�작???�행?�니??]',
ARRAY['dml', 'merge', 'hard'], 25),

('sql-returning-clause', 'sql', 'syntax', 98, 'RETURNING ??, 'DML 결과 반환', 'challenge', 3,
'INSERT/UPDATE/DELETE ??변경된 ?�의 ?�보�?반환?�세??',
'- RETURNING * ?�는 ?�정 컬럼\n- DML �??�에 추�?',
'[{"input": "", "output": "?�입/?�정/??��????}]',
'-- UPDATE ??변경된 ?�을 반환?�세??n',
'UPDATE employees\nSET salary = salary * 1.1\nWHERE dept_id = 10\nRETURNING emp_id, emp_name, salary;',
'[{"input": "", "expected": "updated rows"}]',
'["RETURNING?�로 DML 결과�?즉시 조회?????�습?�다"]',
ARRAY['dml', 'returning', 'hard'], 18),

('sql-cte-delete', 'sql', 'syntax', 99, 'CTE�?복잡??DELETE', '조건부 ??��', 'challenge', 3,
'CTE�??�용?�여 ?�정 조건??만족?�는 중복 ?�만 ??��?�세??',
'- WITH ... DELETE ?�용\n- ROW_NUMBER�?중복 ?�별',
'[{"input": "", "output": "??��??????}]',
'-- ?�메??중복 �?최신 것만 ?�기�???��?�세??n',
'WITH ranked AS (\n  SELECT id,\n    ROW_NUMBER() OVER (PARTITION BY email ORDER BY created_at DESC) AS rn\n  FROM users\n)\nDELETE FROM users\nWHERE id IN (SELECT id FROM ranked WHERE rn > 1);',
'[{"input": "", "expected": "deleted duplicates"}]',
'["CTE�???��???�?�을 먼�? ?�정?�세??]',
ARRAY['dml', 'delete', 'hard'], 25),

('sql-multi-table-update', 'sql', 'syntax', 100, '?�중 ?�이�?UPDATE', '조인???�한 ?�정', 'challenge', 3,
'?�른 ?�이블의 ?�보�?기반?�로 ?�러 컬럼???�시??UPDATE?�세??',
'- UPDATE ... FROM ?�용\n- ?�브쿼리 ?�는 조인 ?�용',
'[{"input": "", "output": "?�정??????}]',
'-- 부???�보�?기반?�로 직원 ?�보�??�데?�트?�세??n',
'UPDATE employees e\nSET\n  dept_name = d.dept_name,\n  location = d.location\nFROM departments d\nWHERE e.dept_id = d.dept_id\n  AND d.status = \''active\'';',
'[{"input": "", "expected": "updated employees"}]',
'["FROM ?�로 ?�른 ?�이블을 참조?�여 UPDATE?????�습?�다"]',
ARRAY['dml', 'update', 'hard'], 22);

-- ====================================
-- ?�료 메시지
-- ====================================
DO $$
BEGIN
  RAISE NOTICE '??SQL Part 2 ?�료 (50 challenges: 30 MEDIUM + 20 HARD)';
  RAISE NOTICE '?�� SQL ?�체 ?�료: 100 challenges';
END $$;

